import * as THREE from 'three';
import {OrbitControls} from '../18-attention-3d/vendor/OrbitControls.js';
import {TinyTransformer,examples,vocab} from './model.js';
import {mountTerrain} from './terrain.js';
let terrain=null,terrainVisible=false;
const $=s=>document.querySelector(s),model=new TinyTransformer();let ex=examples[0],trace,selected=ex.tokens.length-1,mode='predict',history=[],running=false,previous=null,inspected=null,gradientValid=false;
const colors=['#dddddd','#5cd0b3','#b294ee','#58c4dd'];
examples.forEach((e,i)=>$('#example').add(new Option(e.text+' ___',i)));
function parameters(){const el=$('#parameter');el.replaceChildren();model.params.forEach((p,i)=>el.add(new Option(p.name,i)));el.value=String(model.params.findIndex(p=>p.name==='Unembedding[0,'+vocab.indexOf(ex.target)+']'));$('#parameter-count').textContent=model.params.length+' trainable numbers'}parameters();
const host=$('#stage'),scene=new THREE.Scene();scene.background=new THREE.Color('#030405');const camera=new THREE.PerspectiveCamera(42,1,.1,100);camera.position.set(9,5.5,14);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.prepend(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.4,2.6);controls.enableDamping=true;controls.minDistance=4;controls.maxDistance=28;let root=new THREE.Group();scene.add(root);let targets=[],labels=[];
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down;
renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>6)return;const r=host.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(targets)[0];if(hit){inspected=hit.object.userData.cell;if(inspected.layer<3)selected=inspected.token;draw()}});
function resize(){const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(host);
function textSprite(text,color,width=.62,height=.30,bg=null){const c=document.createElement('canvas');c.width=256;c.height=110;const x=c.getContext('2d');if(bg){x.fillStyle=bg;x.fillRect(0,0,256,110)}let fs=76;x.font=fs+'px Georgia';while(x.measureText(text).width>242&&fs>28){fs-=2;x.font=fs+'px Georgia'}x.textAlign='center';x.textBaseline='middle';x.fillStyle=color;x.fillText(text,128,56);const t=new THREE.CanvasTexture(c);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,depthTest:false,transparent:true}));s.scale.set(width,height,1);s.renderOrder=5;root.add(s);return s}
function line(points,color,opacity=.3){const g=new THREE.BufferGeometry().setFromPoints(points.map(p=>new THREE.Vector3(...p)));const l=new THREE.Line(g,new THREE.LineBasicMaterial({color,transparent:true,opacity}));root.add(l)}
function sheet(w,h,z,color){const g=new THREE.PlaneGeometry(w,h),m=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.035,side:THREE.DoubleSide,depthWrite:false});const p=new THREE.Mesh(g,m);p.position.set(0,.1,z);root.add(p);const edge=new THREE.LineSegments(new THREE.EdgesGeometry(g),new THREE.LineBasicMaterial({color,transparent:true,opacity:.45}));p.add(edge)}
function clear(){root.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose()}});scene.remove(root);root=new THREE.Group();scene.add(root);targets=[];labels=[];$('#labels').replaceChildren()}
function label(text,p,color){const el=document.createElement('span');el.className='layer-label';el.textContent=text;el.style.color=color;$('#labels').append(el);labels.push({el,p:new THREE.Vector3(...p)})}
function build(){clear();const n=ex.tokens.length,spacing=.55+Number($('#expand').value)*2.4,zs=[0,spacing,spacing*2,spacing*3],width=Math.max(5,n*.88);const names=['Embedding + Position','Attention + Residual','MLP + Residual','Unembedding → Logits'],arrays=[trace.x,trace.attn,trace.hidden];for(let l=0;l<4;l++){const z=zs[l];sheet(width+1,3.65,z,colors[l]);label(names[l],[0,2.4,z],colors[l]);if(l<3){for(let t=0;t<n;t++){const x=(t-(n-1)/2)*.88;textSprite(ex.tokens[t],t===selected?'#ffff62':'#999999',.72,.26).position.set(x,1.55,z);for(let d=0;d<4;d++){const value=arrays[l][t][d],y=.95-d*.53;let color=t===selected?'#ffff62':'#c5ccd0',bg=t===selected?'#343521':'#13171b';const old=previous?.[ ['x','attn','hidden'][l] ]?.[t]?.[d];if(old!==undefined&&Math.abs(old-value)>1e-5)bg=value>old?'#193a31':'#412327';const cell=textSprite(t===selected?value.toFixed(2):'·',t===selected?color:'#777e86',t===selected?.76:.46,t===selected?.40:.25,t===selected?bg:'#11151a');cell.position.set(x,y,z+.02);cell.userData.cell={layer:l,token:t,dim:d};targets.push(cell)}if(l<2)line([[x,-.9,z],[x,-.9,zs[l+1]]],t===selected?'#ffff62':'#777777',t===selected?.65:.14)}}else{for(let v=0;v<vocab.length;v++){const col=v%4,row=Math.floor(v/4),x=(col-1.5)*.50,y=1.08-row*.43;const isTarget=vocab[v]===ex.target;const s=textSprite(isTarget?trace.logits[v].toFixed(2):'·',isTarget?'#ffff62':'#6e929e',isTarget?.58:.34,.26,isTarget?'#343521':'#101a20');s.position.set(x,y,z+.02);s.userData.cell={layer:3,token:0,dim:v};targets.push(s)}textSprite('last token → next token','#8bb9ca',2.5,.28).position.set(0,1.65,z);}}
// Attention sends information from earlier positions into the selected query.
for(let j=0;j<=selected;j++){const w=trace.attention[selected][j],a=new THREE.Vector3((j-(n-1)/2)*.88,-.65,zs[0]),b=new THREE.Vector3((selected-(n-1)/2)*.88,-.65,zs[1]);const mid=a.clone().lerp(b,.5);mid.y-=.65;const curve=new THREE.QuadraticBezierCurve3(a,mid,b),g=new THREE.BufferGeometry().setFromPoints(curve.getPoints(20));root.add(new THREE.Line(g,new THREE.LineBasicMaterial({color:'#5cd0b3',transparent:true,opacity:.18+.72*w})))}
controls.target.z=zs[3]/2;}
function drawHistory(){const c=$('#history'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#41464f';ctx.beginPath();ctx.moveTo(35,10);ctx.lineTo(35,h-25);ctx.lineTo(w-5,h-25);ctx.stroke();const max=Math.max(1,...history)*1.1;ctx.font='11px monospace';ctx.fillStyle='#aaaaaa';ctx.fillText('Loss',0,12);ctx.fillText('0',19,h-22);ctx.fillText(max.toFixed(1),4,28);ctx.strokeStyle='#ffff62';ctx.beginPath();history.forEach((l,i)=>{const x=36+i/Math.max(1,history.length-1)*(w-45),y=h-25-l/max*(h-45);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();history.forEach((l,i)=>{ctx.beginPath();ctx.arc(36+i/Math.max(1,history.length-1)*(w-45),h-25-l/max*(h-45),2,0,Math.PI*2);ctx.fillStyle='#ffff62';ctx.fill()});$('#history-label').textContent='Same example · '+Math.max(0,history.length-1)+' updates';}
function syncWeight(){const p=model.params[Number($('#parameter').value)];$('#weight').min=Math.min(-2,Math.floor(p.value)-1);$('#weight').max=Math.max(2,Math.ceil(p.value)+1);$('#weight-minus').textContent=$('#weight').min;$('#weight-plus').textContent=$('#weight').max;$('#weight').value=p.value;$('#weight-value').textContent=p.value.toFixed(4);$('#gradient-value').textContent=gradientValid?'∂Loss / ∂weight = '+p.grad.toFixed(5):'Gradient: calculate in step 3';}
function draw(){trace=model.forward(ex.tokens,ex.target);selected=Math.min(selected,ex.tokens.length-1);$('#sentence').textContent=ex.text+' …';$('#target').textContent=mode==='predict'?'Hidden until step 2':ex.target;$('#selected-token').textContent=ex.tokens[selected]+' · position '+(selected+1);$('#embedding').textContent='['+trace.x[selected].map(v=>v.toFixed(4)).join(', ')+']';$('#tokens').replaceChildren(...ex.tokens.map((t,i)=>{const b=document.createElement('button');b.textContent=t;b.className=i===selected?'active':'';b.onclick=()=>{selected=i;draw()};return b}));$('#probabilities').replaceChildren(...vocab.map((word,i)=>({word,p:trace.probs[i]})).sort((a,b)=>b.p-a.p).map(({word,p})=>{const d=document.createElement('div');d.className='bar-row'+(mode!=='predict'&&word===ex.target?' target-row':'');const a=document.createElement('span');a.textContent=word;const track=document.createElement('div');track.className='bar-track';const fill=document.createElement('div');fill.className='bar-fill';fill.style.width=(p*100)+'%';track.append(fill);const num=document.createElement('span');num.textContent=(p*100).toFixed(1)+'%';d.append(a,track,num);return d}));const p=trace.probs[vocab.indexOf(ex.target)];$('#loss-equation').textContent=mode==='predict'?'Reveal the training target in step 2':'−ln(P('+ex.target+')) = −ln('+p.toFixed(4)+')';$('#loss').textContent=mode==='predict'?'—':trace.loss.toFixed(4);$('#loss-explain').textContent='Giving the observed next token more probability makes this loss smaller.';if(inspected){const arr=[trace.x,trace.attn,trace.hidden],v=inspected.layer===3?trace.logits[inspected.dim]:arr[inspected.layer][inspected.token][inspected.dim];$('#inspect').textContent=inspected.layer===3?'Logit for '+vocab[inspected.dim]+': '+v.toFixed(6):['Input','Attention output','MLP output'][inspected.layer]+' · '+ex.tokens[inspected.token]+'['+inspected.dim+'] = '+v.toFixed(6)+'\nActivation, not a trainable weight.'}syncWeight();drawHistory();build();if(terrainVisible)terrain?.refresh();}
const cues={predict:'Follow the sentence through the layers. The last token vector predicts what comes next.',loss:'The observed next token is the target. More probability on that token means a smaller loss.',gradient:'Backpropagation computes how each weight affects the loss. Inspect one derivative below.',update:'Update: weight ← weight − learning rate × gradient. Watch the layers and probabilities change.'};
function setMode(m){mode=m;$('#cue').textContent=cues[m];document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));if(m==='gradient'){model.backward(ex.tokens,ex.target);gradientValid=true}draw()}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#example').onchange=()=>{running=false;ex=examples[Number($('#example').value)];selected=ex.tokens.length-1;previous=null;inspected=null;gradientValid=false;history=[model.forward(ex.tokens,ex.target).loss];$('#status').textContent='New training example; model weights retained.';draw()};$('#parameter').onchange=syncWeight;$('#weight').oninput=()=>{previous=trace;model.params[Number($('#parameter').value)].value=Number($('#weight').value);gradientValid=false;history=[model.forward(ex.tokens,ex.target).loss];$('#status').textContent='Manual weight edit → activations and probabilities recomputed. History restarted.';$('#delta').textContent='';draw()};$('#expand').oninput=()=>{$('#expand-value').textContent=Math.round(Number($('#expand').value)*100)+'%';build()};
function step(){const lr=Number($('#lr').value);if(!Number.isFinite(lr)||lr<=0||lr>2){$('#status').textContent='Choose a learning rate between 0 and 2.';return false}const selectedBefore=model.params[Number($('#parameter').value)].value;const {before,after}=model.step(ex.tokens,ex.target,lr);previous=before;model.backward(ex.tokens,ex.target);gradientValid=true;history.push(after.loss);$('#delta').textContent=selectedBefore.toFixed(4)+' → '+model.params[Number($('#parameter').value)].value.toFixed(4);mode='update';setMode(mode);$('#status').textContent='Loss '+before.loss.toFixed(4)+' → '+after.loss.toFixed(4)+' · '+model.steps+' total updates';return true}
$('#train').onclick=step;$('#run').onclick=async()=>{if(running){running=false;return}running=true;$('#run').textContent='Stop';for(let i=0;i<20&&running;i++){if(!step())break;await new Promise(r=>setTimeout(r,220))}running=false;$('#run').textContent='Watch 20 Steps'};$('#reset').onclick=()=>{running=false;model.reset();previous=null;gradientValid=false;parameters();history=[model.forward(ex.tokens,ex.target).loss];$('#delta').textContent='';$('#status').textContent='Model reset to its initial weights.';setMode('predict')};$('#front').onclick=()=>{camera.position.set(0,.6,22);controls.target.set(0,.4,3)};$('#oblique').onclick=()=>{camera.position.set(9,5.5,14);controls.target.set(0,.4,3)};
function frame(){requestAnimationFrame(frame);controls.update();renderer.render(scene,camera);for(const {el,p}of labels){const v=p.clone().project(camera);el.style.left=(v.x*.5+.5)*host.clientWidth+'px';el.style.top=(-v.y*.5+.5)*host.clientHeight+'px';el.style.display=v.z>1?'none':''}}history=[model.forward(ex.tokens,ex.target).loss];draw();resize();frame();
window.demo={model,get trace(){return trace},getExample:()=>ex,refresh:()=>{gradientValid=false;history.push(model.forward(ex.tokens,ex.target).loss);draw()}};

$('#terrain-view').onclick=()=>{terrainVisible=true;$('#terrain').hidden=false;$('#stage').style.display='none';$('.expand').style.display='none';$('.axis-note').style.display='none';$('#terrain-view').classList.add('active');$('#architecture-view').classList.remove('active');if(!terrain)terrain=mountTerrain($('#terrain'),{model,getExample:()=>ex,onUpdate:()=>{gradientValid=false;mode='update';history.push(model.forward(ex.tokens,ex.target).loss);draw()}});else terrain.refresh();};
$('#architecture-view').onclick=()=>{terrainVisible=false;$('#terrain').hidden=true;$('#stage').style.display='block';$('.expand').style.display='flex';$('.axis-note').style.display='block';$('#architecture-view').classList.add('active');$('#terrain-view').classList.remove('active');resize();};
