import * as THREE from '../18-attention-3d/vendor/three.module.js';
import {OrbitControls} from '../18-attention-3d/vendor/OrbitControls.js';
import {vocab} from './model.js';
import {sampleLandscape,coordinateStep} from './landscape.js';
export function mountTerrain(host,{model,getExample,onUpdate}){
 host.innerHTML=`<div style="display:flex;gap:8px;flex-wrap:wrap;padding:8px"><label>Weight X <select data-a></select></label><label>Weight Z <select data-b></select></label><button data-step>One downhill step</button><button data-run>20 steps</button><label>Learning rate <select data-lr><option>.05</option><option>.2</option><option>1</option><option>5</option></select></label><button data-recenter>Recenter</button></div><div data-scene style="height:440px;position:relative;background:#000;touch-action:none"></div><div data-readout style="padding:10px;font:14px monospace"></div><p style="padding:0 10px;color:#aaa">X and Z: two selected weights · height: actual loss. All other weights are frozen during these steps. Drag to orbit; scroll to zoom. The arrow shows the downhill direction; yellow is the actual update path.</p>`;
 const el=s=>host.querySelector(s),panel=el('[data-scene]'),scene=new THREE.Scene(),renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(2,devicePixelRatio));renderer.setClearColor('#000');panel.append(renderer.domElement);const camera=new THREE.PerspectiveCamera(42,1,.1,100);camera.position.set(7,6,7);const orbit=new OrbitControls(camera,renderer.domElement);orbit.target.set(0,1,0);orbit.enableDamping=true;scene.add(new THREE.AmbientLight(0xffffff,2));let root=new THREE.Group();scene.add(root);let frame,signature='',surface,path=[],ball,arrow,line,center=[0,0],min=0,max=1,yScale=2,ia=0,ib=1;
 const opts=model.params.map((p,i)=>`<option value="${i}">${p.name}</option>`).join('');el('[data-a]').innerHTML=opts;el('[data-b]').innerHTML=opts;
 const targetId=vocab.indexOf(getExample().target);ia=model.params.findIndex(p=>p.name===`Unembedding[0,${targetId}]`);ib=model.params.findIndex(p=>p.name===`Unembedding[1,${targetId}]`);el('[data-a]').value=ia;el('[data-b]').value=ib;
 function clear(){root.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose()}});scene.remove(root);root=new THREE.Group();scene.add(root)}
 const pos=(x,z,loss)=>new THREE.Vector3(x-center[0],(loss-min)*yScale,z-center[1]);
 function rebuild(){const e=getExample();surface=sampleLandscape(model,e.tokens,e.target,ia,ib,{size:23,radius:2.5});center=surface.center;path=[];clear();min=Math.min(...surface.points.flat().map(p=>p.loss));max=Math.max(...surface.points.flat().map(p=>p.loss));yScale=Math.min(2,4/Math.max(.01,max-min));const positions=[],colors=[],color=new THREE.Color();const vertex=p=>{positions.push(...pos(p.x,p.z,p.loss).toArray());color.setHSL(.6-.55*(p.loss-min)/Math.max(.001,max-min),.65,.4);colors.push(color.r,color.g,color.b)};for(let i=0;i<22;i++)for(let j=0;j<22;j++){const a=surface.points[i][j],b=surface.points[i+1][j],c=surface.points[i][j+1],d=surface.points[i+1][j+1];[a,b,c,b,d,c].forEach(vertex)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.computeVertexNormals();root.add(new THREE.Mesh(geo,new THREE.MeshBasicMaterial({vertexColors:true,side:THREE.DoubleSide,transparent:true,opacity:.8})));root.add(new THREE.LineSegments(new THREE.WireframeGeometry(geo),new THREE.LineBasicMaterial({color:'#ffffff',transparent:true,opacity:.13})));function label(text,x,y,z){const c=document.createElement('canvas');c.width=512;c.height=64;const ctx=c.getContext('2d');ctx.fillStyle='#ffffff';ctx.font='26px Arial';ctx.textAlign='center';ctx.fillText(text,256,42);const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),depthTest:false}));sp.position.set(x,y,z);sp.scale.set(3.2,.4,1);root.add(sp)}label('X: '+surface.axes[0],0,-.3,3.0);label('Z: '+surface.axes[1],3.0,-.3,0);label('Loss '+max.toFixed(2),-2.8,(max-min)*yScale,0);label('Loss '+min.toFixed(2),-2.8,0,0);
const grid=new THREE.GridHelper(6,12,0x777777,0x333333);grid.position.y=-.03;root.add(grid);ball=new THREE.Mesh(new THREE.SphereGeometry(.11,18,12),new THREE.MeshBasicMaterial({color:'#ffff62'}));root.add(ball);orbit.target.set(0,Math.max(.4,(max-min)*yScale/2),0);camera.position.set(7,6,7);}
 function paintPoint(){const e=getExample(),t=model.backward(e.tokens,e.target),p=pos(model.params[ia].value,model.params[ib].value,t.loss);p.y+=.06;ball.position.copy(p);if(!path.length||path.at(-1).distanceTo(p)>1e-8)path.push(p.clone());if(line){root.remove(line);line.geometry.dispose();line.material.dispose()}line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(path),new THREE.LineBasicMaterial({color:'#ffff62'}));root.add(line);if(arrow){root.remove(arrow);arrow.dispose()}const ga=model.params[ia].grad,gb=model.params[ib].grad,dir=new THREE.Vector3(-ga,-yScale*(ga*ga+gb*gb),-gb);arrow=new THREE.ArrowHelper(dir.length()?dir.normalize():new THREE.Vector3(0,0,1),p,.65,0xffffff,.15,.09);root.add(arrow);
 el('[data-readout]').textContent=`${model.params[ia].name} = ${model.params[ia].value.toFixed(4)} · ${model.params[ib].name} = ${model.params[ib].value.toFixed(4)} · Loss = ${t.loss.toFixed(4)} · P(target) = ${(100*Math.exp(-t.loss)).toFixed(1)}%`;
 }
 function refresh(){const e=getExample(),s=JSON.stringify([e.tokens,e.target,ia,ib,model.params.filter((_,i)=>i!==ia&&i!==ib).map(p=>p.value)]);if(s!==signature){signature=s;rebuild()}paintPoint()}
 function step(){const e=getExample();coordinateStep(model,e.tokens,e.target,ia,ib,+el('[data-lr]').value);refresh();onUpdate?.()}
 el('[data-step]').onclick=step;el('[data-run]').onclick=()=>{for(let i=0;i<20;i++)step()};el('[data-recenter]').onclick=()=>{signature='';refresh()};for(const tag of ['a','b'])el(`[data-${tag}]`).onchange=()=>{ia=+el('[data-a]').value;ib=+el('[data-b]').value;if(ia===ib){ib=(ia+1)%model.params.length;el('[data-b]').value=ib}signature='';refresh()};
 const resize=new ResizeObserver(()=>{const w=panel.clientWidth,h=panel.clientHeight;if(w&&h){renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}});resize.observe(panel);function animate(){frame=requestAnimationFrame(animate);orbit.update();renderer.render(scene,camera)}refresh();animate();return{refresh,destroy(){cancelAnimationFrame(frame);resize.disconnect();orbit.dispose();clear();renderer.dispose()}};
}
