'use strict';
const M=window.MODEL,E=window.TransformerEngine,$=s=>document.querySelector(s),C={q:'#61e0dc',k:'#f4c772',v:'#c99bff',muted:'#73869f'};
const S={chapter:0,context:'river',query:2,source:1,layer:0,head:0,checkpoint:5,masked:true,gain:1,qOverride:null,vOverride:null,compare:false,teacher:false,temperature:1,future:false,answer:false,readout:false,word:'erodes'};
const chapters=['Context','Embeddings → QKV','Match','Carry','Update → predict','Mask','Learn'];
const titles=['The same word. A different prediction.','Three maps, not three mysterious objects.','A match is a dot product.','The value is the information that travels.','Put the message back into the stream.','Do not let the future write the past.','Where did these numbers come from?'];
const subtitles=['One tiny trained model. Keep this sentence in view through every step.','The same normalized input is multiplied by three different learned matrices.','These really are 2-D query and key vectors. Drag Q and recompute the model.','Hold Q and K fixed. Change a value and watch what changes downstream.','Two heads send messages. Projection, residuals and an MLP update all token positions.','The mask is applied before softmax. Explore an actual attention matrix.','Replay saved training checkpoints. Loss on unseen data can get worse while training loss falls.'];
const qs=['Which earlier token changes the meaning of bank?','Are Q, K and V three copies of the embedding?','Is “similar meaning” the same as a large Q · K?','Does changing V change these attention weights?','Does the attention table itself predict the next word?','Can bank use a later token to predict that token?','Does lower training loss guarantee better generalization?'];
const explains=[
'Compare river with savings. The initial embedding of bank is identical. Its final representation and next-token distribution are computed from the whole prefix.',
'No. Each map has its own learned weights. Q and K determine compatibility; V carries a message. The maps are shared across positions.',
'No. The model learned different maps for queries and keys. Compatibility is measured after those maps; it is not just similarity of the original word embeddings.',
'Not in this head and block: Q/K have stayed fixed. The message and later computations can change. Attention is a routing distribution, not a complete explanation.',
'No. Weighted values are concatenated, projected and added to the residual stream. The MLP and the next block also matter. The final bank vector is read out into vocabulary logits.',
'No in causal training. Set scores for later positions to −∞, then softmax makes their weights zero. Positions can still be trained in parallel.',
'No. The held-out determiner–context combinations become unlikely while bank’s river/finance prediction improves. Different metrics answer different questions. Temperature is not training.'
];
const teaching=[
'最初は「riverをsavingsに変えたら、次はどんな語になりそう？」と聞く。Compare contextsで、bankの最初の8個の数字は同じなのに、最後の表現は違うことを確認する。ここに表示する確率は実際に学習した小型モデルの出力。一般的な英語能力があるとは言わない。',
'Qは照合を求める側、Kは照合される側、Vは受け渡す内容。3つとも同じ入力に、それぞれ異なる学習済み行列を掛けて作る。本モデルはpre-normなので、埋め込み＋位置→LayerNorm→射影という順。数字をすべて読まず、同じ8個が別々の2個になる点を指す。',
'最初に「Qをどちらへ動かすとriverを強く見る？」と予想してもらう。点ではなく、原点からの矢印として読む。内積は向きだけでなく長さにも依存する。Qの黄色ではなく水色のハンドルを動かす。これは学習後の介入であり、重みの学習ではない。右の予測も実際に再計算される。',
'ここが一番大事。「重みを変えずに、届く情報だけを変えられる？」と聞く。紫のVを動かし、同じ層・同じヘッドのAttentionは同じなのに予測が変わることを見せる。Vを加重して頭から尻尾へ足した白い矢印がメッセージ。後続ブロックのAttentionは変わることがある。',
'各ヘッドの2次元メッセージを結合して4次元、W_Oで8次元に戻し、元のベクトルに足す。さらにMLPを加えて次のブロックへ。ヘッドの強さを0にするのは実験的な除去であり、通常のモデル動作ではない。どのヘッドも人間が役割を指定したのではなく学習されたもの。',
'Append a future tokenを押し、bankの行の未来列が0のままなことを見る。Mask OFFで予測が変わるか確認し、必ずONに戻す。未来を追加しても過去のlogitsが変わらないことがcausal modelの重要な性質。並列の学習と逐次の生成は両立する。',
'最初のチェックポイントでは意味のある予測ができない。30、100、1200と進める。training lossは下がるが、validation lossは途中から上がる。本例で悪化するのは、訓練から意図的に外した冠詞と文脈語の組合せの予測。bankの次にくる動詞の予測は改善する。異なる指標を混同しない。学習とはデータの次トークンに対するlossから逆伝播で行列を更新すること。温度は学習ではない。'
];
let current,baseline,tokens,ids,drag=null,graphScale=3;
function options(){return{checkpoint:S.checkpoint,layer:S.layer,head:S.head,query:S.query,source:S.source,masked:S.masked,gain:S.gain,qOverride:S.qOverride,vOverride:S.vOverride,temperature:S.temperature}}
function compute(){tokens=['the',S.context,'bank'];if(S.future)tokens.push('erodes');ids=tokens.map(t=>M.vocabulary.indexOf(t));S.query=Math.min(S.query,tokens.length-1);S.source=Math.min(S.source,tokens.length-1);current=E.forward(M,ids,options());baseline=E.forward(M,ids,{checkpoint:S.checkpoint,temperature:S.temperature})}
function resetInterventions(){S.qOverride=null;S.vOverride=null;S.gain=1;S.masked=true}
function go(n){if(n===0)resetInterventions();S.chapter=n;S.readout=false;S.future=n===5?S.future:false;if(n!==5)S.masked=true;S.answer=false;render()}
function clearAll(){Object.assign(S,{chapter:0,context:'river',query:2,source:1,layer:0,head:0,checkpoint:5,masked:true,gain:1,qOverride:null,vOverride:null,compare:false,temperature:1,future:false,readout:false});render()}
function nums(a,kind='',scale=3){return `<div class="mathgrid" style="grid-template-columns:repeat(${a.length},minmax(0,1fr))">${a.map(x=>`<span class="number ${kind}" style="background:${x<0?'rgba(204,151,255,':'rgba(97,224,220,'}${Math.min(.45,.07+Math.abs(x)/scale*.25)})">${x.toFixed(2)}</span>`).join('')}</div>`}
const f=x=>Number.isFinite(x)?x.toFixed(2):'−∞';
function defs(){return `<defs>${Object.entries(C).map(([n,c])=>`<marker id="arr-${n}" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="${c}"/></marker>`).join('')}<marker id="arr-white" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0 0L6 3L0 6" fill="#eef3fc"/></marker></defs>`}
function vector(x,y,v,color,label,scale,from=[0,0],handle=''){const a=[x+from[0]*scale,y-from[1]*scale],b=[x+(from[0]+v[0])*scale,y-(from[1]+v[1])*scale];return `<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="${C[color]||'#eef3fc'}" stroke-width="${handle?3:2}" marker-end="url(#arr-${color})"/><circle cx="${b[0]}" cy="${b[1]}" r="${handle?9:4}" fill="${C[color]||'#eef3fc'}" ${handle?`class="drag" data-drag="${handle}"`:''}/><text x="${b[0]+9}" y="${b[1]-9}" class="${color[0]}l">${label}</text>`}
function svgPlane(head,mode){let q=head.q[S.query],ks=head.k,vs=head.v,all=mode==='q'?[q,...ks]:[...vs,head.messages[S.query]],bound=Math.max(2,Math.ceil(Math.max(...all.flat().map(Math.abs)))+1);if(!drag)graphScale=bound;bound=graphScale;let scale=125/bound,x=230,y=170;
let g=`<svg viewBox="0 0 490 350" id="plane" role="img" aria-label="Exact two-dimensional ${mode==='q'?'query and key':'value and message'} vectors">${defs()}<path d="M65 170H395M230 15V320" stroke="#405069"/>`;
for(let t=-2;t<=2;t++){let val=t*bound/2;g+=`<path d="M${x+val*scale} 40V300M100 ${y-val*scale}H370" stroke="#1c293a"/><text x="${x+val*scale+3}" y="185">${val.toFixed(1)}</text>`}
g+='<text x="365" y="205">dimension 1</text><text x="242" y="18">dimension 2</text>';
if(mode==='q'){ks.forEach((v,i)=>g+=`<g opacity="${i===S.source?1:.3}">`+vector(x,y,v,'k',i===S.source?`K:${tokens[i]}`:'',scale)+'</g>');g+=vector(x,y,q,'q',`Q:${tokens[S.query]}`,scale,[0,0],'q')}
else{vs.forEach((v,i)=>g+=`<g opacity="${i===S.source?1:.25}">`+vector(x,y,v,'v',i===S.source?`V:${tokens[i]}`:'',scale,[0,0],i===S.source?'v':'')+'</g>');let from=[0,0];head.attention[S.query].forEach((w,i)=>{let v=vs[i].map(x=>x*w);g+=vector(x,y,v,'muted','',scale,from);from=E.add(from,v)});g+=vector(x,y,head.messages[S.query],'white','Σ weighted V',scale)}
g+='</svg>';return g}
function arcDiagram(h){let width=680,step=width/(tokens.length+1),targetX=(S.query+1)*step;return `<svg class="arc" viewBox="0 0 680 145" role="img" aria-label="Information flows from source values into selected query">${defs()}${tokens.map((t,i)=>{let w=h.attention[S.query][i],x=(i+1)*step;return `<path d="M${x} 38 Q${(x+targetX)/2} 118 ${targetX} 127" stroke="${C.v}" stroke-width="${1+w*10}" fill="none" opacity="${.1+w*.8}" marker-end="url(#arr-v)"/><text x="${x}" y="20" text-anchor="middle" class="${i===S.source?'vl':'bright'}">${t} · ${(w*100).toFixed(1)}%</text>`}).join('')}<text x="${targetX+14}" y="139" class="ql">→ ${tokens[S.query]}</text></svg>`}
function prediction(){let p=current.probabilities[2],bp=baseline.probabilities[2],order=p.map((x,i)=>i).sort((a,b)=>p[b]-p[a]).slice(0,5);$('#prediction').innerHTML=order.map(i=>`<div class="prob"><span>${M.vocabulary[i]}</span><div class="track"><div class="fill" style="width:${p[i]*100}%"></div></div><span>${(100*p[i]).toFixed(1)}%</span></div>`).join('');$('#outContext').textContent=S.context;
let changed=S.qOverride||S.vOverride||S.gain!==1||!S.masked;$('#intervention').className='status'+(changed?' changed':'');let delta=p.reduce((s,x,i)=>s+Math.abs(x-bp[i]),0)/2;$('#intervention').textContent=changed?`Intervention active · next-token distribution changed by ${(delta*100).toFixed(1)} percentage points (total variation).`:`Unmodified learned model · training step ${M.checkpoints[S.checkpoint].step}. Probabilities after “bank”.`;}
function initialScene(){const otherContext=S.context==='river'?'savings':'river',oi=['the',otherContext,'bank'].map(x=>M.vocabulary.indexOf(x)),other=E.forward(M,oi,{checkpoint:S.checkpoint});return `<div class="minihead"><span>TRACE ONE TOKEN: <b class="k">bank</b></span><span>8 dimensions, no semantic axis labels</span></div><div class="notice">Predict first: what would you expect after “the ${S.context} bank …”?</div><div class="vectorrow"><span>bank embedding</span>${nums(current.tokenEmb[2])}</div><div class="flow"><span>+ position</span>→<span>Block 1</span>→<span>Block 2</span>→<span class="on">next token</span></div><div class="vectorrow"><span>final bank<br>${S.context} context</span>${nums(current.final[2])}</div>${S.compare?`<div class="separator"></div><div class="vectorrow"><span>bank embedding<br>${otherContext} context</span>${nums(other.tokenEmb[2])}</div><div class="vectorrow"><span>final bank<br>${otherContext} context</span>${nums(other.final[2])}</div><p class="tiny muted">Identical token embeddings. Different contextual vectors. These are real activations of this learned model, not named “river” or “money” axes.</p>`:`<button class="primary" data-action="compare">Reveal the comparison →</button><p class="muted">The initial token vector does not know the surrounding sentence. The following blocks let information cross positions.</p>`}<div class="formula">token ID → embedding + position → 2 decoder blocks<br>→ final LayerNorm → vocabulary logits → softmax</div>`}
function embeddingScene(){let b=current.blocks[S.layer],w=M.checkpoints[S.checkpoint].weights,pre='blocks.'+S.layer+'.',i=S.query;return `<div class="minihead"><span>Selected token: <b>${tokens[i]}</b> · block ${S.layer+1}</span><span>All rows use the same learned maps</span></div><div class="vectorrow"><span>${S.layer===0?'token embedding':'block input'}</span>${nums(S.layer===0?current.tokenEmb[i]:b.input[i])}</div>${S.layer===0?`<div class="vectorrow"><span>+ learned position</span>${nums(current.positions[i])}</div><div class="vectorrow"><span>= block input x</span>${nums(b.input[i])}</div>`:''}<div class="vectorrow"><span>after LayerNorm</span>${nums(b.normalized[i])}</div><div class="mapcards">${['q','k','v'].map(t=>`<div class="card"><h3 class="${t}">W${t.toUpperCase()} → ${t.toUpperCase()}</h3><div class="tiny muted">2 × 8 learned weights</div>${w[pre+t+'.weight'].slice(S.head*2,S.head*2+2).map(r=>nums(r,t)).join('')}<div class="tiny">${t.toUpperCase()} for ${tokens[i]}</div>${nums(b.heads[S.head][t][i],t)}</div>`).join('')}</div><div class="formula">q = W_Q · LayerNorm(x)<br>k = W_K · LayerNorm(x) &nbsp; v = W_V · LayerNorm(x)</div><p class="tiny muted">Matrices shown in [output × input] convention. No projection biases in this model. Position is added once, before the first block.</p>`}
function scoreScene(){let h=current.blocks[S.layer].heads[S.head],q=h.q[S.query],limit=Math.max(6,graphScale);return `<div class="minihead"><span>Block ${S.layer+1} · head ${S.head+1} · query: ${tokens[S.query]}</span><button data-action="clear">Restore learned Q/K/V</button></div><div class="split"><div>${svgPlane(h,'q')}<p class="graphhint">Drag the cyan Q handle. Axes are exact coordinates, not a projection.</p></div><div><table class="scoretable"><thead><tr><th>Key</th><th>q · k / √2</th><th>weight</th></tr></thead><tbody>${tokens.map((t,i)=>`<tr class="${i===S.source?'selected':''}" data-source="${i}"><td>${t}</td><td>${f(h.scores[S.query][i])}</td><td>${(h.attention[S.query][i]*100).toFixed(1)}%</td></tr>`).join('')}</tbody></table><div class="formula">q = [${q.map(f)}]<br>k = [${h.k[S.source].map(f)}]<br>q · k = ${f(q[0]*h.k[S.source][0])}<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;+ ${f(q[1]*h.k[S.source][1])}<br>softmax → Σ weights = 1</div></div></div><div class="controlrow">${q.map((v,i)=>`<label>Q dimension ${i+1}<input aria-label="Q dimension ${i+1}" data-range="q${i}" type="range" min="${-limit}" max="${limit}" step=".05" value="${v}"></label>`).join('')}</div>${arcDiagram(h)}`}
function carryScene(){let h=current.blocks[S.layer].heads[S.head],v=h.v[S.source],limit=Math.max(6,graphScale);return `<div class="minihead"><span>Block ${S.layer+1} · head ${S.head+1} · receiver: ${tokens[S.query]}</span><button data-action="clear">Restore learned Q/K/V</button></div><div class="controlrow"><label>Change the value sent by <select id="source">${tokens.map((t,i)=>`<option value="${i}" ${i===S.source?'selected':''}>${t}</option>`).join('')}</select></label><span class="tiny muted">This head’s Q/K stay fixed. The source V changes for every receiver in this head.</span></div><div class="split"><div>${svgPlane(h,'v')}<p class="graphhint">Drag the filled purple value handle. Gray arrows add head-to-tail.</p></div><div><table class="scoretable"><thead><tr><th>Source</th><th>weight</th><th>weighted V</th></tr></thead><tbody>${tokens.map((t,i)=>`<tr class="${i===S.source?'selected':''}"><td>${t}</td><td>${(h.attention[S.query][i]*100).toFixed(1)}%</td><td>[${h.v[i].map(x=>f(x*h.attention[S.query][i])).join(', ')}]</td></tr>`).join('')}</tbody></table><div class="formula">message = Σ aᵢ vᵢ<br>= [${h.messages[S.query].map(f).join(', ')}]</div><p class="notice">The weights route information. The values determine what is carried.</p></div></div><div class="controlrow">${v.map((x,i)=>`<label>V dimension ${i+1}<input aria-label="V dimension ${i+1}" class="vrange" data-range="v${i}" type="range" min="${-limit}" max="${limit}" step=".05" value="${x}"></label>`).join('')}</div>`}
function updateScene(){let b=current.blocks[S.layer],i=S.query;return `<div class="minihead"><span>Block ${S.layer+1} · selected token ${tokens[i]}</span><span>8-D residual stream</span></div><div class="mapcards">${b.heads.map((h,j)=>`<div class="card"><h3 class="v">Head ${j+1}</h3>${nums(h.messages[i],'v')}<small class="muted">gain ${h.gain.toFixed(2)}</small></div>`).join('')}<div class="card"><h3>Concatenate</h3>${nums(b.message[i])}<small class="muted">4 dimensions → W_O → 8</small></div></div>${[['input','residual input x'],['delta','+ projected message'],['residual','= x + attention'],['mlp','+ MLP update'],['output','= block output']].map(([k,label])=>`<div class="vectorrow"><span>${label}</span>${nums(b[k][i])}</div>`).join('')}<div class="controlrow"><label>Ablate head ${S.head+1}: message gain<input data-range="gain" aria-label="Message gain" type="range" min="0" max="1" step=".02" value="${S.gain}"></label><button data-action="layer">Inspect block ${S.layer===0?'2':'1'} →</button></div><div class="flow"><span>token + position</span>→<span class="${S.layer===0?'on':''}">block 1</span>→<span class="${S.layer===1?'on':''}">block 2</span>→<span>LN + readout</span></div><button class="primary" data-action="readout">Follow bank to the vocabulary →</button><p class="tiny muted">The gain slider is a causal intervention, not normal architecture. Every position is updated in parallel from the preceding layer’s states.</p>`}
function maskScene(){let h=current.blocks[S.layer].heads[S.head],n=tokens.length;return `<div class="controlrow"><button data-action="future">${S.future?'Remove future token':'Append a future token: erodes'}</button><button data-action="mask" class="${S.masked?'active':''}">Causal mask ${S.masked?'ON':'OFF — intervention'}</button></div><div class="minihead"><span>Rows: receiving query · Columns: source key/value</span><span>Block ${S.layer+1} / head ${S.head+1}</span></div><div class="heatmap" style="grid-template-columns:100px repeat(${n},minmax(0,1fr))"><span></span>${tokens.map(t=>`<span class="tiny">${t}</span>`).join('')}${tokens.map((t,i)=>`<span class="tiny">${t} →</span>${h.attention[i].map((a,j)=>`<button data-cell="${i},${j}" style="background:rgba(97,224,220,${.03+a*.6});border-color:${i===S.query?C.k:'#25334a'}">${S.masked&&j>i?'—':(a*100).toFixed(1)+'%'}</button>`).join('')}`).join('')}</div><div class="formula" style="margin-top:20px">score[${tokens[S.query]}, ${tokens[S.source]}] = ${f(h.scores[S.query][S.source])}<br>attention = ${(100*h.attention[S.query][S.source]).toFixed(2)}%</div><p class="notice">${S.masked?'Appending a future token cannot change any earlier logits. The live sidebar still predicts after bank, not after the appended token.':'With the mask removed, later positions can influence earlier ones. This intervention is outside the model’s causal training distribution.'}</p><p class="muted">Training: many next-token targets, computed in parallel.<br>Generation: ordinarily append a token, then run the next step.</p>`}
function readoutScene(){let word=M.vocabulary.indexOf(S.word),x=current.final[2],w=M.checkpoints[S.checkpoint].weights['readout.weight'][word],terms=x.map((v,i)=>v*w[i]),logit=current.logits[2][word],logits=current.logits[2],max=Math.max(...logits),denom=logits.reduce((s,v)=>s+Math.exp((v-max)/S.temperature),0);return `<div class="minihead"><span>Readout after the final block and final LayerNorm</span><button data-action="readout">← Back to block update</button></div><div class="controlrow"><label>Candidate next token<select id="word">${M.vocabulary.filter(w=>w!=='<pad>').map(w=>`<option ${w===S.word?'selected':''}>${w}</option>`).join('')}</select></label><span class="big">${(current.probabilities[2][word]*100).toFixed(2)}%</span></div><div class="vectorrow"><span>final bank x</span>${nums(x)}</div><div class="vectorrow"><span>output row for<br>${S.word}</span>${nums(w)}</div><div class="vectorrow"><span>multiply pairs</span>${nums(terms)}</div><div class="formula">logit[${S.word}] = Σ xᵢ × W[${S.word},i] = ${logit.toFixed(4)}<br><br>stable softmax: exp((logit − max) / T) / Σ exp((logits − max) / T)<br>= ${Math.exp((logit-max)/S.temperature).toFixed(4)} / ${denom.toFixed(4)}<br>= ${(current.probabilities[2][word]*100).toFixed(2)}%</div><p class="notice">All 21 vocabulary logits contribute to the denominator. The corpus gives each context three equally frequent valid verbs. For the trained, unmodified model at T = 1, roughly one-third on each appropriate verb is expected.</p><div class="flow"><span>all contextual token vectors</span>→<span class="on">last prefix vector: bank</span>→<span>21 logits</span>→<span>next-token probabilities</span></div>`}
function learnScene(){let cp=M.checkpoints[S.checkpoint],xs=M.checkpoints.map(c=>65+c.step/1200*560),ys=M.checkpoints.map(c=>335-c.metrics.trainLoss*75),vys=M.checkpoints.map(c=>335-c.metrics.validationLoss*75);return `<div class="minihead"><span>Saved checkpoints of one real training run</span><span>Next-token cross-entropy · x-axis: actual training steps</span></div><svg viewBox="0 0 700 360" role="img" aria-label="Training and validation loss curves"><path d="M60 40V335H660" stroke="#4a5b71" fill="none"/>${[0,1,2,3].map(t=>`<path d="M60 ${335-t*75}H660" stroke="#223246"/><text x="35" y="${340-t*75}">${t}</text>`).join('')}<polyline points="${xs.map((x,i)=>x+','+ys[i]).join(' ')}" fill="none" stroke="${C.q}" stroke-width="3"/><polyline points="${xs.map((x,i)=>x+','+vys[i]).join(' ')}" fill="none" stroke="${C.k}" stroke-width="3"/>${xs.map((x,i)=>`<circle cx="${x}" cy="${ys[i]}" r="${i===S.checkpoint?8:4}" fill="${C.q}"/><circle cx="${x}" cy="${vys[i]}" r="${i===S.checkpoint?8:4}" fill="${C.k}"/>${i===1?'':`<text x="${x}" y="353" text-anchor="middle">${M.checkpoints[i].step}</text>`}`).join('')}<text x="70" y="24" class="ql">training loss</text><text x="230" y="24" class="kl">held-out loss</text></svg><div class="controlrow"><label>Training checkpoint<input aria-label="Training checkpoint" data-range="checkpoint" type="range" min="0" max="5" step="1" value="${S.checkpoint}"></label><span class="big">step ${cp.step}</span><button data-action="step">Next checkpoint →</button></div><div class="formula">train loss: ${cp.metrics.trainLoss.toFixed(3)}<br>held-out loss (all positions): ${cp.metrics.validationLoss.toFixed(3)}<br>held-out bank → verb loss: ${cp.metrics.validationBankVerbLoss.toFixed(3)}<br>river/finance next-word category: ${(cp.metrics.heldoutCategoryAccuracy*100).toFixed(0)}% on just ${cp.metrics.heldoutPrefixes} held-out prefixes</div><p class="notice">The held-out loss rises because held-out determiner–context pairs become unlikely. The bank → verb loss still improves toward ln(3) ≈ 1.099: three equally plausible verbs. Different metrics answer different questions.</p><details><summary>Sampling temperature is different from training</summary><div class="controlrow"><label>Temperature<input data-range="temperature" aria-label="Temperature" type="range" min=".2" max="2" step=".1" value="${S.temperature}"></label></div><p>Changes only the final softmax. No learned matrix is updated.</p></details><div class="quiz"><p>Exit question: If I change only V, what stays fixed in that head and block?</p><button data-action="quiz">Reveal answer</button>${S.answer?'<p class="answer">The Q/K scores and attention weights stay fixed. The message, residual update and downstream prediction may change.</p>':''}</div>`}
function render(){compute();$('#chapters').innerHTML=chapters.map((t,i)=>`<button data-chapter="${i}" class="${i===S.chapter?'active':''}">${i+1}. ${t}</button>`).join('');$('#tokens').innerHTML=tokens.map((t,i)=>`<button data-token="${i}" class="${i===S.query?'active':''}">${t}<small>position ${i}</small></button>`).join('');$('#chapterLabel').textContent=`CHAPTER ${S.chapter+1} / 7`;$('#title').textContent=titles[S.chapter];$('#subtitle').textContent=subtitles[S.chapter];$('#question').textContent=qs[S.chapter];$('#explain').textContent=explains[S.chapter];$('#teacherNotes').textContent=teaching[S.chapter];$('#teacherNotes').classList.toggle('hidden',!S.teacher);$('#context').value=S.context;$('#layer').value=S.layer;$('#head').value=S.head;$('#checkpoint').value=S.checkpoint;$('#scene').innerHTML=(S.chapter===4&&S.readout)?readoutScene():[initialScene,embeddingScene,scoreScene,carryScene,updateScene,maskScene,learnScene][S.chapter]();if(S.chapter===4&&S.readout){$('#title').textContent='From one vector to a vocabulary.';$('#subtitle').textContent='The final bank vector is scored against every output row. Softmax turns all 21 logits into a distribution.'}$('#position').textContent=`${S.chapter+1} / 7 · Use ← / → to move through the lesson`;$('#back').disabled=S.chapter===0;$('#next').disabled=S.chapter===6;prediction()}
$('#checkpoint').innerHTML=M.checkpoints.map((c,i)=>`<option value="${i}">step ${c.step}</option>`).join('');$('#context').onchange=e=>{S.context=e.target.value;resetInterventions();render()};$('#compare').onclick=()=>{S.compare=!S.compare;S.chapter=0;resetInterventions();render()};$('#reset').onclick=clearAll;$('#clear').onclick=()=>{resetInterventions();render()};$('#teacher').onclick=()=>{S.teacher=!S.teacher;render()};$('#next').onclick=()=>go(Math.min(6,S.chapter+1));$('#back').onclick=()=>go(Math.max(0,S.chapter-1));for(const key of ['layer','head','checkpoint'])$('#'+key).onchange=e=>{S[key]=+e.target.value;resetInterventions();render()};
document.addEventListener('click',e=>{let row=e.target.closest('[data-source]');if(row){S.source=+row.dataset.source;render();return}let b=e.target.closest('button');if(!b)return;if(b.dataset.chapter!==undefined)go(+b.dataset.chapter);if(b.dataset.token!==undefined){S.query=+b.dataset.token;S.qOverride=null;render()}if(b.dataset.cell){[S.query,S.source]=b.dataset.cell.split(',').map(Number);render()}switch(b.dataset.action){case'compare':S.compare=!S.compare;resetInterventions();render();break;case'clear':resetInterventions();render();break;case'layer':S.layer=1-S.layer;resetInterventions();render();break;case'future':S.future=!S.future;render();break;case'mask':S.masked=!S.masked;render();break;case'step':S.checkpoint=(S.checkpoint+1)%6;resetInterventions();render();break;case'readout':S.readout=!S.readout;render();break;case'quiz':S.answer=!S.answer;render();break}});
document.addEventListener('change',e=>{if(e.target.id==='word'){S.word=e.target.value;render()}if(e.target.id==='source'){S.source=+e.target.value;S.vOverride=null;render()}});
function rangeUpdate(kind,val){if(kind[0]==='q'&&kind.length===2){let h=current.blocks[S.layer].heads[S.head];S.qOverride=(S.qOverride||h.q[S.query]).slice();S.qOverride[+kind[1]]=val}else if(kind[0]==='v'&&kind.length===2){let h=current.blocks[S.layer].heads[S.head];S.vOverride=(S.vOverride||h.v[S.source]).slice();S.vOverride[+kind[1]]=val}else{S[kind]=val;if(kind==='checkpoint')resetInterventions()}}
document.addEventListener('input',e=>{let k=e.target.dataset.range;if(!k)return;let pos=e.target.selectionStart;rangeUpdate(k,+e.target.value);render();let el=document.querySelector(`[data-range="${k}"]`);el?.focus({preventScroll:true})});
document.addEventListener('pointerdown',e=>{let range=e.target.closest('[data-range]');if(range){e.preventDefault();drag={kind:'range',key:range.dataset.range,rect:range.getBoundingClientRect(),min:+range.min,max:+range.max,step:+range.step,pointer:e.pointerId};const pct=Math.max(0,Math.min(1,(e.clientX-drag.rect.left)/drag.rect.width));rangeUpdate(drag.key,Math.round((drag.min+pct*(drag.max-drag.min))/drag.step)*drag.step);render();return}let t=e.target.closest('[data-drag]');if(!t)return;e.preventDefault();let svg=t.closest('svg'),r=svg.getBoundingClientRect();let inverse=svg.getScreenCTM().inverse();drag={kind:t.dataset.drag,rect:r,inverse:{a:inverse.a,b:inverse.b,c:inverse.c,d:inverse.d,e:inverse.e,f:inverse.f},scale:graphScale,pointer:e.pointerId};});
window.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointer)return;e.preventDefault();if(drag.kind==='range'){const pct=Math.max(0,Math.min(1,(e.clientX-drag.rect.left)/drag.rect.width));rangeUpdate(drag.key,Math.round((drag.min+pct*(drag.max-drag.min))/drag.step)*drag.step);render();return}let m=drag.inverse,x=m.a*e.clientX+m.c*e.clientY+m.e,y=m.b*e.clientX+m.d*e.clientY+m.f,v=[(x-230)*drag.scale/125,(170-y)*drag.scale/125].map(x=>Math.max(-12,Math.min(12,x)));if(drag.kind==='q')S.qOverride=v;else S.vOverride=v;render()});window.addEventListener('pointerup',()=>{drag=null});
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.key==='ArrowRight')go(Math.min(6,S.chapter+1));if(e.key==='ArrowLeft')go(Math.max(0,S.chapter-1));if(e.key.toLowerCase()==='f')document.body.classList.toggle('presentation')});
window.STUDIO={state:S,go,render,compute,reset:clearAll,get output(){return current},caption(text){let e=$('#caption');e.textContent=text;e.style.display=text?'block':'none'}};render();
