import {scenes,videos,groups} from './scenes.js';
import {words,sourceScores,sourceLogits,dot,add,scale,softmax,trace,parameterCounts,outputEquivalence,maskingTrace} from './math.js';
import {showSpace,hideSpace,tickSpace,resetCamera,spaceState} from './space.js';
const $=s=>document.querySelector(s),canvas=$('#stage'),ctx=canvas.getContext('2d');
const emb=await (await fetch('embeddings.json')).json();await document.fonts.load('20px ComputerModern');
const C={white:'#eeeeee',gray:'#aaa',dark:'#555',blue:'#58c4dd',teal:'#5cd0b3',yellow:'#ffff00',red:'#fc6255',pink:'#d147bd',green:'#83c167',brown:'#b5a493'};
let index=0,p=0,playing=false,lastTime=0,compare=false,dirty=true,lastSpaceKey='';
const defaults=()=>({bias:0,value:1,T:1,angle:45,selection:3,source:2,mode:0,head:0,mask:true,scaled:false,count:8,slope:.7,intercept:1,word:0,logit:3.5});let state=defaults();
let clipped=[];let renderedScene=null;let hitboxes=[];const register=(x,y,w,h,fn)=>hitboxes.push({x,y,w,h,fn});
function text(t,x,y,size=26,color=C.white,align='center',alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.font=`${size}px ComputerModern, Georgia, serif`;ctx.textAlign=align;ctx.textBaseline='middle';ctx.fillStyle=color;const metrics=ctx.measureText(String(t));const left=align==='center'?x-metrics.width/2:align==='right'?x-metrics.width:x;const transform=ctx.getTransform();if(alpha>.05&&transform.a===1&&transform.b===0&&(left<0||left+metrics.width>1280||y-size/2<0||y+size/2>720))clipped.push({text:String(t),x,y,width:metrics.width});ctx.fillText(String(t),x,y);ctx.restore()}
function box(x,y,w,h,color=C.gray,fill=null,lw=1){ctx.save();if(fill){ctx.fillStyle=fill;ctx.fillRect(x,y,w,h)}ctx.strokeStyle=color;ctx.lineWidth=lw;ctx.strokeRect(x,y,w,h);ctx.restore()}
function line(x,y,x2,y2,color=C.gray,width=1,alpha=1){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=width;ctx.globalAlpha=alpha;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();ctx.restore()}
function arrow(x,y,x2,y2,color=C.white,width=2,progress=1){const xx=x+(x2-x)*progress,yy=y+(y2-y)*progress;if(Math.hypot(xx-x,yy-y)<1)return;line(x,y,xx,yy,color,width);const a=Math.atan2(yy-y,xx-x);ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(xx,yy);ctx.lineTo(xx-12*Math.cos(a-.4),yy-12*Math.sin(a-.4));ctx.lineTo(xx-12*Math.cos(a+.4),yy-12*Math.sin(a+.4));ctx.fill()}
function arc(x,y,x2,y2,height,color=C.teal,progress=1){ctx.save();ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y);ctx.bezierCurveTo(x,y-height,x2,y2-height,x2,y2);ctx.stroke();ctx.restore();arrow(x2-2,y2-15,x2,y2,color,2);const t=progress;const px=(1-t)**3*x+3*(1-t)**2*t*x+3*(1-t)*t*t*x2+t**3*x2,py=(1-t)**3*y+3*(1-t)**2*t*(y-height)+3*(1-t)*t*t*(y2-height)+t**3*y2;circle(px,py,4,color)}
function circle(x,y,r,color,alpha=1){ctx.save();ctx.globalAlpha=alpha;ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,Math.max(.01,r),0,2*Math.PI);ctx.fill();ctx.restore()}
function ease(t){t=Math.max(0,Math.min(1,t));return t*t*(3-2*t)}
const part=(a,b)=>ease((p-a)/(b-a));const sub=n=>'₀₁₂₃₄₅₆₇₈₉'[n];
function vector(v,x,y,{w=70,h=230,color=C.white,label='',weight=false,selected=-1}={}){line(x-w/2+9,y,x-w/2,y,color);line(x-w/2,y,x-w/2,y+h,color);line(x-w/2,y+h,x-w/2+9,y+h,color);line(x+w/2-9,y,x+w/2,y,color);line(x+w/2,y,x+w/2,y+h,color);line(x+w/2,y+h,x+w/2-9,y+h,color);v.forEach((n,i)=>{const cy=y+(i+.5)*h/v.length;if(i===selected)box(x-w/2,cy-h/v.length/2,w,h/v.length,C.yellow);text(typeof n==='number'?n.toFixed(1):n,x,cy,Math.min(23,h/v.length*.65),weight?(n>=0?C.blue:C.red):color)});if(label)text(label,x,y-25,25,color)}
function matrix(a,x,y,w,h,{label='',highlight=-1,weight=true}={}){const rows=a.length,cols=a[0].length;box(x,y,w,h,C.gray);for(let i=0;i<rows;i++)for(let j=0;j<cols;j++){const n=a[i][j];text(typeof n==='number'?(n>=0?'+':'')+n.toFixed(1):n,x+(j+.5)*w/cols,y+(i+.5)*h/rows,Math.min(21,w/cols*.34),typeof n==='number'&&weight?(n>=0?C.blue:C.red):C.gray)}if(highlight>=0)box(x+highlight*w/cols,y,w/cols,h,C.yellow,null,2);if(label)text(label,x+w/2,y-30,30,C.blue)}
const demoMatrix=(r,c,seed=1)=>Array.from({length:r},(_,i)=>Array.from({length:c},(_,j)=>Math.round(Math.sin((i+1)*13+(j+1)*17+seed)*40)/10));
function tokenRow(list,y=110,x0=90,width=1100,selected=-1){const cell=width/list.length;list.forEach((w,i)=>{const x=x0+(i+.5)*cell;const col=w==='fluffy'||w==='blue'?C.blue:w==='verdant'?C.green:(i===selected?C.yellow:C.gray);const tw=Math.min(cell-8,w.length*14+10);box(x-tw/2,y-17,tw,34,col,i===selected?'#333300':'#111');text(w,x,y,Math.min(26,cell/(w.length+.6)*1.5),col);register(x-cell/2,y-22,cell,45,()=>{state.selection=i;dirty=true;updateControlsValues()})});return cell}
function footer(t){text(t,640,685,19,C.gray)}
function title(t){ctx.font='35px ComputerModern';const size=Math.min(35,35*1180/ctx.measureText(t).width);text(t,640,48,size);line(380,78,900,78,'#777')}
function bars(names,probs,x,y,w=300,h=36,selected=-1){probs.forEach((pr,i)=>{text(names[i],x-14,y+i*h,21,i===selected?C.yellow:C.white,'right');ctx.fillStyle=i===selected?C.yellow:C.teal;ctx.fillRect(x,y+i*h-8,Math.max(0,pr*w),16);text((100*pr).toFixed(1)+'%',x+w+18,y+i*h,18,C.gray,'left')})}
function network(x,y,w,h,phase=0){const sizes=[5,7,7,4];sizes.forEach((n,c)=>{if(c<sizes.length-1)for(let a=0;a<n;a++)for(let b=0;b<sizes[c+1];b++)line(x+c*w/3,y+(a+.5)*h/n,x+(c+1)*w/3,y+(b+.5)*h/sizes[c+1],(a+b)%2?C.blue:C.red,.7,.35);for(let i=0;i<n;i++)circle(x+c*w/3,y+(i+.5)*h/n,6,(phase>.5&&c<phase*4)?C.yellow:C.gray)})}
function block(x,y,w,h,label){for(let i=5;i>0;i--)box(x+i*4,y-i*4,w,h,'#4c4c4c','#2b2b2b');box(x,y,w,h,'#777','#333');text(label,x+w/2,y+h/2,28)}
function drawIntro(s){if(s.id==='gpt'){['Generative','Pretrained','Transformer'].forEach((w,i)=>{const on=Math.floor(p*2.99)===i;text(w,240+i*400,170,40,on?C.yellow:C.white);if(i===0){bars(['next','word','…'],[.6,.3,.1],180,350,150);arrow(300,465,300,525,C.blue)}if(i===1){for(let a=0;a<6;a++)for(let b=0;b<7;b++){circle(510+b*28,320+a*30,9,C.teal,.5);line(510+b*28,320+a*30,516+b*28,313+a*30,C.white)}text('learned weights',600,560,25,C.blue)}if(i===2)network(870,300,230,220,p)});footer('Generate text · learn from data · transform vectors')}else{const modes=[['Audio','Transformer','Text'],['Text','Transformer','Speech'],['Text','Transformer','Image'],['Language A','Transformer','Language B']];modes.forEach((r,i)=>{const y=165+i*120;text(r[0],260,y,30,C.blue);arrow(370,y,490,y);box(510,y-35,260,70,C.gray,'#242424');text(r[1],640,y,29);arrow(790,y,910,y);text(r[2],1020,y,30,C.teal)});footer('This walkthrough follows next-token prediction, not every Transformer variant.')}}
function drawGeneration(s){const chat=s.id==='chat';const seed=chat?'User: What should I do in Santiago?':'Behold, a wild pi creature, foraging in its native';text(chat?'A helpful AI assistant continues the conversation':seed,640,125,29,C.blue);const phases=['Predict','Sample','Append','Repeat'];phases.forEach((x,i)=>text(x,310+i*220,210,26,Math.floor(p*3.99)===i?C.yellow:C.gray));block(320,350,280,155,'Transformer');arrow(640,430,750,430,C.white,3,part(0,.25));const probs=softmax([2.3,1.7,.8,.4,.1],state.T),names=chat?['Sure', 'There', 'Absolutely','Santiago','Here']:['habitat','land','forest','country','environment'];bars(names,probs,910,320,160,45,p>.35?0:-1);if(p>.5){text(names[0],640,575,33,C.yellow);arc(640,548,285,145,230,C.teal,part(.5,1));}footer('Distribution shown here is illustrative, not a live GPT-3 API response.')}
function drawTokens(){const list=['To','date',',','the','cle','ve','rest','thinker','of','all','time','was'];const step=1100/list.length;tokenRow(list,145,90,1100);for(let i=0;i<list.length;i++){const x=90+(i+.5)*step;arrow(x,170,x,255,C.white,2,part(.05,.3));ctx.globalAlpha=part(.2,.55);vector(demoMatrix(8,1,i).flat(),x,280,{w:59,h:245});ctx.globalAlpha=1;}footer('Tokens may be words, word pieces, punctuation or other character combinations.');}
function drawArchitecture(s){const n=8;tokenRow(words,125,170,980);const a=part(0,.35);for(let layer=4;layer>=0;layer--){const y=280+layer*62;const offset=layer*20;box(170+offset,y,900,130,'#777',layer%2?'#242424':'#151515');text(layer%2?'Multilayer perceptron':'Attention',180+offset,y+25,23,layer%2?C.blue:C.gray,'left');for(let i=0;i<n;i++){const xx=200+offset+i*108;for(let j=0;j<5;j++)text(((i+j+layer)%7-3+.1).toFixed(1),xx,y+53+j*13,10,C.gray);if(layer%2===0&&a>.1)for(let k=0;k<=i;k++)line(205+k*108+offset,y+43,xx,y+105,C.teal,.7,a*.35)}}if(p>.4){for(let i=0;i<n;i++)arrow(225+i*115,160,225+i*115,235,C.white,1.5)}if(p>.7){box(1000,585,60,60,C.yellow);arrow(1065,615,1160,615,C.yellow,3);text('P(next)',1190,652,22,C.yellow)}footer(s.id==='deeper'?'Attention + MLP repeated across layers; normalization omitted in this high-level source view.':'Attention mixes information across positions. MLP applies the same function to each position.');}
function drawRoadmap(){const r=[['Word embeddings','Words → vectors'],['Dot products','Alignment → a score'],['Softmax','Scores → normalized weights'],['Learned matrices','Parameters determine the maps']];r.forEach((x,i)=>{const y=170+i*115;text('✓',200,y,40,p>=i/4?C.green:C.dark);text(x[0],270,y,31,C.white,'left');text(x[1],750,y,28,C.blue,'left')});footer('Next: put these ingredients together inside the attention block.')}
function drawLearning(){text('Input',230,150,30);text('Tunable parameters',645,150,30,C.blue);text('Output',1060,150,30);box(100,230,250,220,C.gray,'#191919');text('data examples',225,310,30);text('text / image / audio',225,365,22,C.gray);arrow(365,340,465,340);for(let i=0;i<7;i++)for(let j=0;j<8;j++){circle(505+j*39,245+i*30,11,C.teal,.5);const an=p*3+j;line(505+j*39,245+i*30,505+j*39+8*Math.cos(an),245+i*30+8*Math.sin(an),C.white)}arrow(840,340,935,340);text('desired behavior',1060,340,27,C.yellow);text('Learning changes the parameters.',640,565,34);footer('This introduction is conceptual. Backpropagation is not implemented in this scene.')}
function drawRegression(){const x=140,y=580,w=930,h=370;line(x,y,x+w,y);line(x,y,x,y-h);text('Square footage',1020,625,27);ctx.save();ctx.translate(85,380);ctx.rotate(-Math.PI/2);text('Price',0,0,28);ctx.restore();let loss=0;for(let i=0;i<24;i++){const xx=i/23*8+.3,yy=.8*xx+1+Math.sin(i*12)*.8;const pred=state.slope*xx+state.intercept;circle(x+xx*100,y-yy*44,4,C.yellow);if(p>.35)line(x+xx*100,y-yy*44,x+xx*100,y-pred*44,C.red,1,.5);loss+=(pred-yy)**2;}line(x,y-state.intercept*44,x+w,y-(state.slope*9.3+state.intercept)*44,C.blue,3);text(`y = ${state.slope.toFixed(2)} x + ${state.intercept.toFixed(2)}`,650,140,33,C.blue);text(`Mean squared error = ${(loss/24).toFixed(3)}`,650,190,26,C.gray);footer('The dots are fixed data. The slope and intercept are adjustable model parameters.')}
function drawTensors(){text('Input data',180,150,30,C.gray);matrix(demoMatrix(7,5),70,205,230,290,{weight:false});text('array of numbers',185,540,25,C.gray);arrow(330,350,430,350);for(let l=5;l>=0;l--)box(470+l*18,220-l*9,190,275,'#777','#151515');text('layers',625,545,27,C.white);arrow(780,350,870,350);bars(['next₁','next₂','next₃','next₄'],[.55,.28,.12,.05],1010,270,110,58);text('probabilities',1090,545,26,C.gray);footer('A tensor is a multidimensional array. Model parameters are distinct from these activations.')}
function drawWeights(){const a=demoMatrix(5,6),v=[.8,-1.2,.5,2,.2,-.3];const row=Math.min(4,Math.floor(p*4.99));matrix(a,120,215,570,260,{label:'W — learned weights'});box(120,215+row*52,570,52,C.yellow,null,2);vector(v,780,215,{h:260,w:65,label:'x — data'});text('=',855,345,35);vector(a.map(r=>dot(r,v)),970,215,{h:260,w:120,label:'Wx',selected:row});text(a[row].map((n,i)=>`${n.toFixed(1)} × ${v[i]}`).join(' + '),640,550,23,C.white);text(`= ${dot(a[row],v).toFixed(3)}`,640,605,34,C.yellow);footer('Same matrix, different inputs. Changing an activation is not training the weights.')}
function drawLookup(){const names=['a','blue','creature','forest','model','tower','king','mole'];const sel=state.word%names.length;const mat=Array.from({length:8},(_,i)=>names.map(w=>emb.vectors[w][i]));names.forEach((w,i)=>{text(w,205+(i+.5)*100,150,22,i===sel?C.yellow:C.gray);register(205+i*100,123,100,45,()=>{state.word=i;dirty=true;updateControlsValues()})});matrix(mat,205,185,800,320,{label:'',highlight:sel});text('Wᴱ',120,345,42,C.blue);const toX=205+(sel+.5)*100;arrow(toX,525,toX,568,C.yellow,2,part(.1,.6));vector(mat.map(r=>r[sel]).slice(0,3),toX,583,{w:78,h:65,color:C.yellow});text(`E(${names[sel]}) = column ${sel+1}`,640,95,27,C.yellow);footer('Shown: 8 coordinates from actual GloVe 50D. GPT-3: 50,257 columns × 12,288 rows.')}
function drawSpace(s){const kind=s.kind;let items=[],target=[0,0,0],fit=5;let key=`${s.id}:${p.toFixed(3)}:${state.mode}`;
const xyz=w=>(emb.xyz[w]||[0,0,0]).map((v,i)=>i<2?-v:v);const region=s.kind==='neighbors'?'35%':'2%';$('#three').style.right=region;$('#three-labels').style.right=region;
if(kind==='space'){items=['tower','building','roof','cat','dog','model','king','queen'].map((w,i)=>({to:xyz(w),label:w,color:i<3?C.blue:C.gray}));text('50D word vectors → 3D projection',640,112,27,C.blue);footer('Drag to rotate · these three coordinates are a projection, not all of meaning.');}
else if(kind==='neighbors'){const near=emb.neighbors.tower;items=near.slice(0,8).map(([w],i)=>({to:xyz(w),label:i===0?w:'',color:i===0?C.yellow:C.gray}));near.slice(1,10).forEach(([w,c],i)=>text(`${w}  ${c.toFixed(3)}`,990,205+i*43,24,C.gray));fit=4;text('Embeddings closest to E(tower)',640,112,29);footer('Actual GloVe 50D cosine neighbors; camera and projection are reconstructed.');}
else if(kind==='analogy'){const k=s.id==='countries'?'countries':s.id==='food'?'food':state.mode===1?'family':'analogy';const data=emb.analogies[k];const [a,b,c,d]=data.words;const transform=(w,shift)=>add(xyz(w).map((v,i)=>i===1?v*2:v),shift);const paired=['analogy','family'].includes(k);const va=paired?transform(a,[-4,-1,-1]):xyz(a),vb=paired?transform(b,[0,-1,0]):xyz(b),vc=paired?transform(c,[0,-1,0]):xyz(c),vd=paired?transform(d,[-4,-1,-1]):xyz(d),delta=add(vb,scale(vc,-1)),end=add(va,scale(delta,part(.1,.75)));items=[{to:va,label:`E(${a})`,color:C.blue},{to:vb,label:`E(${b})`,color:C.red},{to:vc,label:`E(${c})`,color:C.gray},{from:vc,to:vb,color:C.yellow},{from:va,to:end,color:C.yellow,label:p>.3?'translated difference':''}];if(p>.65)items.push({to:vd,color:C.pink,label:`E(${d}) — actual`},{from:end,to:vd,color:'#888'});text(`E(${a}) + E(${b}) − E(${c}) ≈ E(${d})`,640,115,27);footer(`Actual 50D residual norm: ${data.errorNorm.toFixed(3)} — an analogy, not an exact equality.`);target=scale(add(add(va,vd),add(vb,vc)),.18);fit=paired?7:6;}
else {let base=[-1,.4,.3],updates=[],labels0=[],label0='';if(s.id==='model'){label0='model';updates=[[2,1,1],[-1,1,-2]];labels0=['machine learning model','fashion model'];text('A machine learning model …        A fashion model …',640,115,30);}
if(s.id==='mole'){label0='mole';updates=[[2,1,0],[-1,2,1],[.5,-.2,-2]];labels0=['American shrew mole','One mole of carbon dioxide','Take a biopsy of the mole'];labels0.forEach((t,i)=>text(t,220+i*425,120,22,i===state.mode?C.yellow:C.gray));}
if(s.id==='eiffel'){label0='tower';updates=[[2,1,0],[-2,.3,1]];labels0=['Eiffel Tower','Miniature Eiffel Tower'];text('Tower → Eiffel Tower → Miniature Eiffel Tower',640,115,30);}
if(s.id==='king-context'){label0='king';updates=[[1.5,.2,0],[.2,1.6,0],[0,.2,1.8]];labels0=['lived in Scotland','murdered predecessor','Shakespearean language'];text('The King doth wake tonight and takes his rouse …',640,115,28);}
if(s.id==='harry'){label0=state.mode===2?'car':'Harry';updates=state.mode===2?[[1.5,.4,-1]]:[[2,1,0],[-1,1,-2]];labels0=state.mode===2?['crashed the car']:['wizard · Hogwarts · Hermione','Queen · Sussex · William'];text(state.mode===2?'… they crashed the car …':'… wizard … Harry       /       … Queen … Sussex … Harry',640,115,27);}
items=[{to:base,label:`E(${label0})`,color:C.yellow}];let end=base;const sequential=['eiffel','king-context'].includes(s.id);updates.forEach((u,i)=>{if(!sequential&&i!==state.mode%updates.length)return;const amt=sequential?ease(p*updates.length-i):part(.1,.8);const start=sequential?end:base;end=add(start,scale(u,amt));items.push({from:start,to:end,label:amt>.5?labels0[i]:'',color:[C.blue,C.teal,C.pink][i]});});items.push({to:end,color:C.white});footer('Contextual shifts are explanatory geometry, not extracted Transformer activations.');fit=4;}
if(key!==lastSpaceKey){showSpace(items,{azimuth:lastSpaceKey.split(':')[0]===s.id&&lastSpaceKey.split(':').at(-1)===String(state.mode)?null:.8,target,fit});lastSpaceKey=key;}}
function drawDot(){const ox=360,oy=400,unit=70;for(let i=-3;i<=3;i++){line(ox-230,oy+i*unit,ox+230,oy+i*unit,'#2e4049');line(ox+i*unit,oy-230,ox+i*unit,oy+230,'#2e4049')}line(ox-245,oy,ox+245,oy);line(ox,oy-245,ox,oy+245);const a=state.angle*Math.PI/180;const v=[2,0],w=[2*Math.cos(a),2*Math.sin(a)];arrow(ox,oy,ox+v[0]*unit,oy-v[1]*unit,C.yellow,4);arrow(ox,oy,ox+w[0]*unit,oy-w[1]*unit,C.pink,4);text('w',ox+v[0]*unit+20,oy,28,C.yellow);text('v',ox+w[0]*unit,oy-w[1]*unit-25,28,C.pink);vector(v,755,230,{h:160,w:90,color:C.yellow,label:'w'});vector(w,900,230,{h:160,w:90,color:C.pink,label:'v'});text(`${v[0].toFixed(1)} × ${w[0].toFixed(2)} + ${v[1].toFixed(1)} × ${w[1].toFixed(2)}`,880,465,27);text(`w · v = ${dot(v,w).toFixed(3)}`,880,535,39,dot(v,w)>=0?C.yellow:C.red);text(`${state.angle}°`,360,135,31,C.gray);footer('Lengths matter too: q · k = ‖q‖ ‖k‖ cos θ. Alignment is not cosine similarity alone.')}
function drawPlural(){const direction=add(emb.vectors.cats,scale(emb.vectors.cat,-1));const pairs=[['cat','cats'],['dog','dogs'],['student','students'],['one','two','three','four']];const ws=pairs[state.mode%4];text('plural = E(cats) − E(cat)',760,155,33,C.yellow);line(290,195,290,635,C.gray);for(let n=-4;n<=5;n++){const y=450-n*45;line(281,y,299,y,C.gray);text(n,256,y,21,C.gray)}ws.forEach((w,i)=>{const v=dot(direction,emb.vectors[w]);const y=450-v*45,ty=285+i*86;circle(290,y,6,i%2?C.red:C.blue);line(304,y,495,ty,i%2?C.red:C.blue,1.5);text(`plural · E(${w}) = ${v.toFixed(3)}`,530,ty,30,i%2?C.red:C.blue,'left')});footer('All 50 GloVe coordinates are used. The direction is learned structure, not a rule guaranteed for every word.')}
function drawWindow(s){const count=s.kind==='quadratic'?state.count:Math.min(32,state.count);if(s.kind==='quadratic'){const n=Math.min(64,count),size=430/n,x=430,y=170;for(let i=0;i<=n;i++){line(x+i*size,y,x+i*size,y+430,'#888',.5);line(x,y+i*size,x+430,y+i*size,'#888',.5)}text(`n = ${count}`,220,275,37,C.blue);text(`n² = ${(count*count).toLocaleString()}`,220,345,33,C.yellow);text('key–query pairs',220,400,25);footer('Dense attention-score storage grows quadratically with context length.');}else{for(let i=0;i<count;i++){const x=170+(i+.5)*950/count;vector(['⋮','0.4','−1.2','⋮','3.8'],x,210,{w:Math.min(45,850/count),h:325,color:i===count-1?C.yellow:C.gray});}text('Context size: 2,048 token positions in GPT-3',640,145,30);text('12,288 coordinates per position',640,590,29,C.blue);footer(`${count} schematic columns visible here; the real dimension and context are not reduced to this display.`)}}
function drawUnembedding(){const n=8;tokenRow(['Harry','Potter','was','…','least','favourite','teacher,','Professor'],145,80,1100,7);for(let i=0;i<n;i++)vector(demoMatrix(5,1,i).flat(),120+i*110,380,{w:57,h:180,color:i===7?C.yellow:C.gray});const pp=part(.1,.45);arrow(890,370,890,290,C.yellow,2,pp);matrix(demoMatrix(6,6),350,190,390,145,{label:'Wᵁ'});vector(['⋮','4.2','1.9','⋮'],820,195,{w:65,h:140,color:C.yellow});if(p>.3){arrow(875,260,970,260);bars(['Snape','Trelawney','Quirrell','other'],[.78,.16,.04,.02],1060,220,100,57)}footer('The final contextual vector → vocabulary logits → softmax. These probabilities illustrate the source example.')}
function drawSoftmax(){const logits=[...sourceLogits];logits[4]=state.logit;const T=$scene().id==='temperature'?state.T:1;const probs=softmax(logits,T);text('Logits',270,142,29,C.teal);vector(logits,270,200,{w:110,h:355});arrow(355,370,470,370);box(490,175,245,425,C.blue,'#073640');text('softmax',612,218,32);for(let i=0;i<7;i++)text(T===0?'argmax limit':`e^(x${sub(i+1)} / ${T.toFixed(1)}) / Σ e^(x / T)`,612,270+i*43,19,C.white);arrow(752,370,835,370);text('Probabilities',1000,142,29,C.yellow);bars(logits.map((_,i)=>`p${sub(i+1)}`),probs,940,220,175,50);text(`Σp = ${probs.reduce((a,b)=>a+b,0).toFixed(6)}`,1010,615,28,C.yellow);footer(`T = ${T.toFixed(2)} · exponential computed after subtracting max(logit) for numerical stability.`)}
function drawMystery(){const snippets=['A missing key …','The witness changed their story …','The clock had stopped …','A detail from the first chapter …'];snippets.forEach((t,i)=>{text(t,210+i*260,190+(i%2)*80,22,C.gray);arc(210+i*260,220+(i%2)*80,855,445,60,C.teal,part(.1,.9))});text('Therefore the murderer was',560,440,36);box(850,415,155,50,C.yellow);text('???',927,443,30,C.yellow);arrow(850,480,850,530);vector(['⋮','1.8','−0.4','⋮'],850,550,{w:70,h:85});footer('The last vector must carry relevant information from across the available context.')}
function drawAdjectives(){const x0=90,w=1100,cell=w/8,y=240;tokenRow(words,y,x0,w);[[1,3],[2,3],[6,7]].forEach(([i,j],k)=>{if(p>.04)arc(x0+(i+.5)*cell,y-28,x0+(j+.5)*cell,y-28,90+k*14,k===2?C.green:C.blue,part(.05,.5))});for(let i=0;i<8;i++){const x=x0+(i+.5)*cell;const a=part(.35,.75);arrow(x,y+30,x,340,C.white,2,a);ctx.globalAlpha=a;vector(demoMatrix(7,1,i).flat(),x,360,{w:67,h:215,label:'E'+sub(i+1)});ctx.globalAlpha=1;}text('meaning + position',640,615,27,C.teal);footer('The adjective → noun head is an imagined example in the original video, not a claim about all heads.')}
function drawQuery(s){const key=s.kind==='key';const col=key?C.teal:C.yellow;tokenRow(words,138,80,1100,state.selection);for(let i=0;i<8;i++){const x=80+(i+.5)*137.5;arrow(x,170,x,210);text('E'+sub(i+1),x,240,26);arrow(x,268,x,316,col,2,part(.05,.35));text(key?'Wᴷ':'WQ',x+31,285,18,col);text((key?'K':'Q')+sub(i+1),x,345,31,col)}const mat=demoMatrix(4,8,key?6:3);matrix(mat,155,475,560,140,{label:key?'Key matrix Wᴷ':'Query matrix WQ'});vector(demoMatrix(8,1,state.selection).flat(),800,475,{h:140,w:60});text('=',865,540,32);vector(mat.map(r=>dot(r,demoMatrix(8,1,state.selection).flat())),945,475,{h:140,w:115,color:col});text(key?'“I am an adjective; here is my position.”':'“Any adjectives in front of me?”',650,400,28,col);footer('GPT-3 map: 12,288 → 128. The compact matrix here demonstrates multiplication with illustrative numbers.')}
const $scene=()=>scenes[index];
function attentionLayout(s){const selected=state.selection;const isValue=['value','weighted-values','residual'].includes(s.kind);const isSoft=['attention-softmax','mask','equation'].includes(s.kind);const tt=trace({mask:s.kind==='mask'?state.mask:isValue,scaled:s.kind==='equation'&&state.scaled,bias:state.bias,value:state.value,head:state.head});
const x0=430,y0=230,cw=78,ch=49;for(let i=0;i<=8;i++){line(x0+i*cw,110,x0+i*cw,y0+8*ch,'#777',.8);line(145,y0+i*ch,x0+8*cw+20,y0+i*ch,'#777',.8)}
for(let j=0;j<8;j++){const x=x0+(j+.5)*cw;const selectedColor=j===selected?C.yellow:C.gray;box(x-cw/2+5,99,cw-10,26,j===selected?C.yellow:C.gray,j===selected?'#242400':'#111');text(words[j],x,112,words[j].length>6?17:20,words[j]==='blue'?C.blue:words[j]==='verdant'?C.green:selectedColor);arrow(x,135,x,155);text('E'+sub(j+1),x,175,24);if(!isValue){arrow(x,188,x,206,C.yellow,1);text('Q'+sub(j+1),x,218,24,C.yellow)}register(x-cw/2,98,cw,132,()=>{state.selection=j;dirty=true;updateControlsValues()})}
for(let i=0;i<8;i++){const y=y0+(i+.5)*ch;const c=i===1||i===2?C.blue:i===6?C.green:C.gray;text(words[i],256,y,23,c,'right');arrow(267,y,295,y);text('E'+sub(i+1),319,y,25);arrow(343,y,377,y,isValue?C.red:C.teal,2);text(isValue?'WV':'WK',360,y-17,15,isValue?C.red:C.teal);text((isValue?'v':'K')+sub(i+1),402,y,25,isValue?C.red:C.teal);register(160,y-ch/2,260,ch,()=>{state.source=i;dirty=true;updateControlsValues()});}
if(selected>=0)box(x0+selected*cw,y0,cw,8*ch,C.yellow,'#ffff0009',1.5);
for(let i=0;i<8;i++)for(let j=0;j<8;j++){const x=x0+(j+.5)*cw,y=y0+(i+.5)*ch;const a=tt.attention[i][j],sco=tt.logits[i][j];const focus=j===selected?1:.36;const alpha=isSoft?part(.2,.8):0;if(s.kind==='scores'){const reveal=part(.2,.8);if(reveal<.6)circle(x,y,2+Math.max(0,tt.scores[i][j])/5,C.gray,focus);if(reveal>.25)text((tt.scores[i][j]>0?'+':'')+tt.scores[i][j].toFixed(1),x,y,21,tt.scores[i][j]>90?C.white:C.red,'center',reveal*focus)}else if(isValue){if(j===selected){text(a.toFixed(2)+(p>.3?' v'+sub(i+1):''),x,y,21,C.red,'center');}else circle(x,y,2+16*Math.sqrt(a),C.gray,.35)}else if(s.kind==='mask'&&p<.45){text(sco===-Infinity?'−∞':sco.toFixed(1),x,y,20,sco===-Infinity?C.red:C.gray)}else {if(alpha<.65)circle(x,y,2+15*Math.sqrt(a),C.gray,1-alpha*.6);if(alpha>.2)text(a.toFixed(2),x,y,20,a>.3?C.white:C.gray,'center',alpha*focus);}}
if(isValue&&p>.5){const xx=x0+(selected+.5)*cw;arrow(xx,630,xx,654,C.yellow);text('ΔE'+sub(selected+1),xx,672,24,C.yellow);text('E′'+sub(selected+1)+' = E'+sub(selected+1)+' + ΔE'+sub(selected+1),280,670,25,C.teal)}else if(isSoft)text(`Column ${selected+1}: Σ = ${tt.attention.reduce((a,r)=>a+r[selected],0).toFixed(6)}`,700,664,26,C.yellow);else text('Rows: keys / senders       Columns: queries / receivers',650,674,22,C.gray);
return tt;}
function drawMask(){const t=maskingTrace(state.mask&&p>.3,state.mode===2);const y0=225,cw=81,ch=61;for(const [x0,name] of [[45,'Unnormalized'],[747,'Normalized']]){text(name,x0+243,133,34);text('Attention Pattern',x0+243,177,32);for(let i=0;i<6;i++)for(let j=0;j<6;j++){const x=x0+(j+.5)*cw,y=y0+(i+.5)*ch;box(x0+j*cw,y0+i*ch,cw,ch,'#666');if(x0===45){const n=t.logits[i][j];text(n===-Infinity?'−∞':(n>=0?'+':'')+n.toFixed(2),x,y,25,n===-Infinity?C.red:C.white);if(i>j&&p>.15&&p<=.3)box(x0+j*cw,y0+i*ch,cw,ch,C.red,null,2);}else if(p>.6)text(t.attention[i][j].toFixed(2),x,y,24,t.attention[i][j]===0?C.red:C.white);}}text('softmax',638,381,31);arrow(556,423,719,423,C.white,3,part(.4,.65));if(p>.6){t.sums.forEach((v,j)=>text(v.toFixed(2),747+(j+.5)*cw,627,22,Math.abs(v-1)<1e-8?C.yellow:C.red));text('Column sums →',580,627,23,C.gray);}footer(state.mode===2?'Incorrect: zeroing after softmax breaks normalization.':'Correct: −∞ before softmax produces zeros while every column still sums to one.')}
function drawEquation(){text('A = softmax_columns ( KᵀQ / √dₖ + mask )',640,150,36);text('ΔE = V A',640,217,37,C.red);const q=demoMatrix(5,8,2),k=demoMatrix(5,8,3);matrix(q,160,330,390,180,{label:'Q: dₖ × n'});matrix(k,710,330,390,180,{label:'K: dₖ × n'});text('KᵀQ: n × n',640,570,33,C.yellow);text('V: dᵥ × n     →     V A: dᵥ × n',640,625,29,C.red);footer('Column-vector convention: weights normalize down columns. Row-vector notation transposes the layout.')}
function drawValue(s){if(s.kind==='value'){text('fluffy                 creature',380,165,38);vector([9.2,-3.3,5.8,.6,1.3,8.4,'⋮',-8.2],240,225,{h:260,w:80});vector([-7.6,2.8,-7.1,8.8,.4,-1.7,'⋮',-4.7],470,225,{h:260,w:80});matrix(demoMatrix(5,6),80,540,450,105,{label:'WV'});const base=[870,440],old=[780,295],to=[1045,270];arrow(...base,...old,C.brown,4);arrow(...old,...to,C.red,3,part(.1,.7));arrow(...base,old[0]+(to[0]-old[0])*part(.1,.7),old[1]+(to[1]-old[1])*part(.1,.7),C.white,3);text('creature',750,267,25,C.brown);text('fluffy creature',1040,237,25);text('Value',955,315,29,C.red);footer('A value is an update for another embedding, not just the original source-word vector.');return;}
if(state.mode===0){attentionLayout(s);return;}
const tt=trace({mask:true,bias:state.bias,value:state.value});const j=state.selection;const base=tt.base[j],sum=tt.delta[j];const proj=v=>[640+v[0]*105+v[2]*58,520-v[1]*140-v[2]*42];const origin=proj([0,0,0]);for(let i=-3;i<5;i++){line(...proj([i,0,-3]),...proj([i,0,4]),'#344550');line(...proj([-3,0,i]),...proj([4,0,i]),'#344550')}arrow(...origin,...proj(base),C.brown,4);text('E('+words[j]+')',...add(proj(base),[-10,28]),25,C.brown);let pos=base;for(let i=0;i<8;i++){const v=scale(tt.values[i],tt.attention[i][j]*part(.1,.8));const next=add(pos,v);if(Math.hypot(...v)>.02){arrow(...proj(pos),...proj(next),i===2?C.blue:C.red,3);text(`${tt.attention[i][j].toFixed(2)} v_${words[i]}`,...add(proj(next),[20,-20]),21,i===2?C.blue:C.red)}pos=next;}arrow(...origin,...proj(pos),C.teal,3);text('E′',...add(proj(pos),[20,30]),30,C.teal);text('E′ = E + Σᵢ aᵢⱼ vᵢ',640,130,36);text(`ΔE = [${sum.map(x=>x.toFixed(3)).join(', ')}]`,640,615,28,C.yellow);footer('3D illustrative values; attention coefficients use the reconstructed source example.');}
function drawCounts(s){const fmt=x=>x.toLocaleString();let rows=[];if(s.id==='embedding-count')rows=[['Embedding Wᴱ','12,288 × 50,257',parameterCounts.embedding]];else if(s.id==='unembedding-count')rows=[['Embedding Wᴱ','12,288 × 50,257',parameterCounts.embedding],['Unembedding Wᵁ','50,257 × 12,288',parameterCounts.embedding]];else if(s.id==='qkv-count')rows=[['Query','128 × 12,288',parameterCounts.query],['Key','128 × 12,288',parameterCounts.key],['Naive full value map','12,288 × 12,288',parameterCounts.valueFull]];else rows=[['One matrix','128 × 12,288',parameterCounts.query],['One head','4 matrices',parameterCounts.head],['One attention block','96 heads',parameterCounts.block],['All attention blocks','96 layers',parameterCounts.attention]];rows.forEach(([name,expr,count],i)=>{const y=190+i*108;line(110,y+57,1170,y+57,'#555');text(name,140,y,28,C.white,'left');text(expr,650,y,26,C.gray);text(fmt(count),1150,y,29,C.blue,'right');});if(rows.length===1)matrix(demoMatrix(7,16),275,310,780,255,{label:'Wᴱ'});footer('GPT-3 175B architecture, following the original video’s matrix count (not all small biases/normalization weights).')}
function drawLowrank(){const left=demoMatrix(8,3),right=demoMatrix(3,8);text('12,288 → 128 → 12,288',640,140,38,C.yellow);matrix(left,200,260,200,300,{label:'Value up'});matrix(right,455,348,420,125,{label:'Value down'});vector(demoMatrix(8,1).flat(),965,260,{h:300,w:65,label:'E'});text('=',1040,410,35);vector(['⋮','ΔE','⋮'],1140,260,{h:300,w:95,color:C.red});text('rank(W_up W_down) ≤ 128',640,623,32,C.yellow);footer('Two matrices: 2 × 12,288 × 128 = 3,145,728 parameters, versus 150,994,944 for a full square map.')}
function drawCross(){const a=['I','do','not','want','to','pet','it'],b=['Je','ne','veux','pas','le','caresser'];const match=[0,1,3,2,6,5];const x=440,y=245,cw=82,ch=62;a.forEach((w,j)=>{text(w,x+(j+.5)*cw,155,25,C.blue);arrow(x+(j+.5)*cw,180,x+(j+.5)*cw,205,C.yellow);text('Q'+sub(j+1),x+(j+.5)*cw,224,24,C.yellow)});b.forEach((w,i)=>{text(w,260,y+(i+.5)*ch,27,C.green,'right');arrow(285,y+(i+.5)*ch,355,y+(i+.5)*ch,C.teal);text('K'+sub(i+1),390,y+(i+.5)*ch,24,C.teal);for(let j=0;j<a.length;j++){box(x+j*cw,y+i*ch,cw,ch,'#555');circle(x+(j+.5)*cw,y+(i+.5)*ch,match[i]===j?18:3,C.gray,p>.2?1:.2)}});footer('Queries and keys/values come from different sequences; there is no causal triangle between these languages.')}
function drawHeads(){const active=state.head;for(let h=3;h>=0;h--){const x=160+h*210,y=175;const tt=trace({head:h,mask:true});text(`Head ${h+1}`,x+85,y-30,26,h===active?C.yellow:C.gray);for(let i=0;i<8;i++)for(let j=0;j<8;j++){box(x+j*20,y+i*20,20,20,h===active?'#888':'#444');circle(x+(j+.5)*20,y+(i+.5)*20,1+6*Math.sqrt(tt.attention[i][j]),h===active?C.white:C.gray)}register(x,y-60,170,230,()=>{state.head=h;dirty=true;updateControlsValues()});arrow(x+80,y+180,x+80,415,C.gray,2,part(.1,.5));vector(tt.delta[state.selection],x+80,450,{w:100,h:105,color:h===active?C.teal:C.gray,label:'ΔE⁽'+(h+1)+'⁾'});}text('… 96 independent heads',640,615,27,C.gray);footer('E′ⱼ = Eⱼ + ΔEⱼ⁽¹⁾ + ΔEⱼ⁽²⁾ + ⋯ + ΔEⱼ⁽⁹⁶⁾. Small patterns shown here are illustrative.')}
function drawOutput(){const e=outputEquivalence();text('Two equivalent orders of computation',640,125,30);for(let h=0;h<2;h++){const x=160+h*435;matrix(e.up[h],x,245,215,170,{label:'W_up⁽'+(h+1)+'⁾'});vector(e.small[h],x+285,270,{h:110,w:75,color:C.red});text(h===0?'+':'=',x+370,335,32);}text(`[${e.summed.map(x=>x.toFixed(2)).join(', ')}]`,1110,340,28,C.teal);matrix(e.matrix,240,500,410,145,{label:'Wᴼ = [ W_up⁽¹⁾ | W_up⁽²⁾ ]'});vector(e.concat,750,500,{h:145,w:85,color:C.red});text('=',840,567,32);vector(e.fused,990,500,{h:145,w:145,color:C.teal});footer('Numerically identical: Σₕ W_up⁽ʰ⁾ z⁽ʰ⁾ = Wᴼ concat(z⁽¹⁾, z⁽²⁾, …).')}
function drawParallel(){text('All key–query pairs can be computed together.',640,135,31);for(let i=0;i<9;i++){const y=225+i*37;text(`Q${sub(i%8+1)}`,260,y,26,C.yellow);arrow(300,y,520,y,C.gray,1);text('×',620,y,26,C.blue);arrow(700,y,955,y,C.gray,1);text('score',1030,y,24,C.gray);circle(320+ease((p*2+i*.04)%1)*610,y,4,C.teal)}box(550,200,150,360,C.blue);text('GPU',625,610,35,C.blue);footer('Parallelizable computation enables scale. Attention is only one part of the network.')}
function draw(){dirty=false;hitboxes=[];clipped=[];ctx.clearRect(0,0,1280,720);ctx.fillStyle='#000';ctx.fillRect(0,0,1280,720);const s=$scene();title(s.title);const useSpace=['space','neighbors','analogy','context'].includes(s.kind);if(!useSpace){hideSpace();lastSpaceKey=''}const f={intro:drawIntro,generation:drawGeneration,token:drawTokens,architecture:drawArchitecture,roadmap:drawRoadmap,learning:drawLearning,regression:drawRegression,tensors:drawTensors,weights:drawWeights,lookup:drawLookup,space:drawSpace,neighbors:drawSpace,analogy:drawSpace,context:drawSpace,dot:drawDot,plural:drawPlural,counts:drawCounts,window:drawWindow,unembedding:drawUnembedding,softmax:drawSoftmax,mystery:drawMystery,adjectives:drawAdjectives,query:drawQuery,key:drawQuery,scores:attentionLayout,'attention-softmax':attentionLayout,equation:drawEquation,mask:drawMask,quadratic:drawWindow,value:drawValue,'weighted-values':drawValue,residual:drawValue,lowrank:drawLowrank,cross:drawCross,heads:drawHeads,output:drawOutput,parallel:drawParallel}[s.kind];if(!f)throw Error('Missing renderer '+s.kind);f(s);renderedScene=s.id;$('#scrub').value=p;$('#position').textContent=`${index+1} / ${scenes.length} · ${Math.round(p*100)}%`;}
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
function slider(key,label,min,max,step=1){return `<label>${label}<output data-output="${key}">${state[key]}</output></label><input data-state="${key}" aria-label="${label}" type="range" min="${min}" max="${max}" step="${step}" value="${state[key]}">`}
function buttons(key,values){return `<div class="buttons">${values.map(([v,t])=>`<button data-set="${key}" data-value="${v}" class="${state[key]===v?'active':''}">${t}</button>`).join('')}</div>`}
function buildControls(){const s=$scene();let html='';if(['space','neighbors','analogy','context'].includes(s.kind)){html+='<p>Drag to orbit; scroll to zoom. Use Reset view to restore the camera.</p><button id="camera-reset">Reset view</button>';if(s.id==='analogy')html+=buttons('mode',[[0,'king / queen'],[1,'uncle / aunt']]);if(s.id==='mole')html+=buttons('mode',[[0,'Animal'],[1,'Amount of substance'],[2,'Skin']]);if(s.id==='model')html+=buttons('mode',[[0,'machine learning'],[1,'fashion']]);if(s.id==='harry')html+=buttons('mode',[[0,'wizard'],[1,'royalty'],[2,'crashed car']]);}
if(s.kind==='plural')html+=buttons('mode',[[0,'cat / cats'],[1,'dog / dogs'],[2,'student / students'],[3,'one → four']]);if(s.kind==='lookup')html+='<p>Click a word in the matrix to retrieve its column.</p>';
if(s.kind==='dot')html+=slider('angle','Angle θ',0,180,1)+buttons('angle',[[0,'Aligned'],[90,'Perpendicular'],[180,'Opposite']]);
if(s.kind==='regression')html+=slider('slope','Slope',0,1.5,.01)+slider('intercept','Intercept',-2,4,.01)+buttons('mode',[[1,'Least-squares solution']]);
if(s.id==='temperature'||s.kind==='generation')html+=slider('T','Temperature T',0,5,.05);if(s.kind==='softmax')html+=slider('logit','Fifth logit',-5,10,.1);
if(['window','quadratic'].includes(s.kind))html+=slider('count','Displayed context length n',4,s.kind==='window'?32:64,1)+buttons('count',[[8,'8'],[16,'16'],[32,'32']]);
if(['scores','attention-softmax','weighted-values','residual','heads'].includes(s.kind))html+='<p>Click a word above to select the column being updated.</p>'+slider('bias','blue → creature score change',-6,6,.05);if(s.kind==='mask')html+=buttons('mask',[[true,'Mask future'],[false,'No mask']])+buttons('mode',[[0,'−∞ before softmax'],[2,'Zero after softmax (incorrect)']]);if(s.kind==='equation')html+='<p>Column-vector notation keeps matrix shapes consistent instead of importing the source notation variations into executable equations.</p>';
if(['weighted-values','residual'].includes(s.kind))html+=buttons('mode',[[0,'Source column view'],[1,'Add arrows']])+slider('value','blue Value strength',-2,3,.05);
if(s.kind==='heads')html+=buttons('head',[[0,'head 1'],[1,'head 2'],[2,'head 3'],[3,'head 4']]);
if(!html)html='<p>Use ▶ Play or the slider to advance the diagram. ← → changes scenes; Space plays or pauses.</p>';
$('#controls').innerHTML=html;$('#controls').querySelectorAll('[data-state]').forEach(el=>el.oninput=()=>{state[el.dataset.state]=+el.value;dirty=true;updateControlsValues()});$('#controls').querySelectorAll('[data-set]').forEach(el=>el.onclick=()=>{let v=el.dataset.value;v=v==='true'?true:v==='false'?false:+v;state[el.dataset.set]=v;if(s.kind==='regression'&&v===1){const xs=Array.from({length:24},(_,i)=>i/23*8+.3),ys=xs.map((x,i)=>.8*x+1+Math.sin(i*12)*.8);const xm=xs.reduce((a,b)=>a+b)/24,ym=ys.reduce((a,b)=>a+b)/24;state.slope=xs.reduce((a,x,i)=>a+(x-xm)*(ys[i]-ym),0)/xs.reduce((a,x)=>a+(x-xm)**2,0);state.intercept=ym-state.slope*xm;}dirty=true;buildControls()});if($('#camera-reset'))$('#camera-reset').onclick=resetCamera;}
function updateControlsValues(){for(const el of $('#controls').querySelectorAll('[data-state]'))el.value=state[el.dataset.state];for(const el of $('#controls').querySelectorAll('[data-output]'))el.textContent=Number(state[el.dataset.output]).toFixed(2);}
function time(t){return Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0')}
function updateSource(){const s=$scene();$('#source-link').href=`https://www.youtube.com/watch?v=${videos[s.chapter]}&t=${s.start}s`;if(compare)$('#source').src=`https://www.youtube.com/embed/${videos[s.chapter]}?start=${s.start}&end=${s.end}&rel=0`;else $('#source').removeAttribute('src');}
function goto(i,{progress=0,keep=false}={}){index=Math.max(0,Math.min(scenes.length-1,i));p=progress;playing=false;$('#play').textContent='▶ Play';if(!keep)state=defaults();const s=$scene();history.replaceState(null,'','#'+s.id);$('#title').textContent=s.title;$('#cue').textContent=s.cue;$('#stamp').textContent=`CHAPTER ${s.chapter} · SOURCE ${time(s.start)}–${time(s.end)}`;$('#boundary').textContent=['neighbors','analogy','plural','lookup','space'].includes(s.kind)?'Real GloVe 50D data, matching the source—not GPT-3. The 3D projection and layout are reconstructed.':'Source-aligned teaching illustration. Numbers, positions, and motion include reconstructions; these are not internal states of a trained GPT.';buildControls();window.scrollTo({top:0,behavior:'instant'});$('#scenes').querySelectorAll('button').forEach((b,j)=>b.classList.toggle('active',j===index));updateSource();lastSpaceKey='';dirty=true;}
$('#chapters').innerHTML=groups.map(([t,id])=>`<button data-goto="${id}">${t}</button>`).join('');$('#chapters').querySelectorAll('button').forEach(b=>b.onclick=()=>goto(scenes.findIndex(s=>s.id===b.dataset.goto)));
$('#scenes').innerHTML=scenes.map((s,i)=>`<button data-index="${i}">${i+1}. ${esc(s.title)}<small>Ch.${s.chapter} · ${time(s.start)}–${time(s.end)}</small></button>`).join('');$('#scenes').querySelectorAll('button').forEach(b=>b.onclick=()=>goto(+b.dataset.index));
$('#prev').onclick=()=>goto(index-1);$('#next').onclick=()=>goto(index+1);$('#reset').onclick=()=>goto(index);$('#scrub').oninput=e=>{p=+e.target.value;playing=false;$('#play').textContent='▶ Play';dirty=true};$('#play').onclick=()=>{if(p>=1)p=0;playing=!playing;$('#play').textContent=playing?'Ⅱ Pause':'▶ Play';dirty=true};$('#project').onclick=()=>document.body.classList.toggle('project');$('#compare').onclick=()=>{compare=!compare;$('#reference').hidden=!compare;$('#compare').classList.toggle('active',compare);updateSource()};
canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*1280,y=(e.clientY-r.top)/r.height*720;const h=hitboxes.find(h=>x>=h.x&&x<=h.x+h.w&&y>=h.y&&y<=h.y+h.h);h?.fn()});canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*1280,y=(e.clientY-r.top)/r.height*720;canvas.style.cursor=hitboxes.some(h=>x>=h.x&&x<=h.x+h.w&&y>=h.y&&y<=h.y+h.h)?'pointer':'default'});
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(e.target.tagName))return;if(e.key==='ArrowRight')goto(index+1);if(e.key==='ArrowLeft')goto(index-1);if(e.code==='Space'){e.preventDefault();$('#play').click()}});
window.addEventListener('hashchange',()=>{const i=scenes.findIndex(s=>s.id===location.hash.slice(1));if(i>=0&&i!==index)goto(i)});
window.replica={get state(){return {index,scene:$scene().id,renderedScene,clipped,p,playing,controls:{...state},space:spaceState()}},scenes,goto:(id,progress=1)=>goto(typeof id==='number'?id:scenes.findIndex(s=>s.id===id),{progress}),set:o=>{Object.assign(state,o);dirty=true;updateControlsValues()},trace:()=>trace({mask:state.mask,bias:state.bias,value:state.value}),math:{softmax,dot,outputEquivalence,parameterCounts,maskingTrace},embeddings:emb};
goto(Math.max(0,scenes.findIndex(s=>s.id===location.hash.slice(1))));function frame(now){const dt=Math.min(.05,(now-lastTime)/1000||0);lastTime=now;if(playing){p=Math.min(1,p+dt/12);dirty=true;if(p>=1){playing=false;$('#play').textContent='▶ Play'}}if(dirty)draw();tickSpace();requestAnimationFrame(frame)}requestAnimationFrame(frame);
