import {softmax, dot} from './math.js';
const $=s=>document.querySelector(s),words=['a','fluffy','blue','creature','roamed','the','verdant','forest'];
const initial=()=>({q:[[.4,.3],[1.4,.2],[.2,1.4],[1.5,1.5],[-1,.5],[.2,.1],[-.5,1.5],[-1,1.7]],k:[[.1,.1],[2,.1],[.1,2],[.3,.3],[-1,.3],[.1,-.5],[-1.5,1.5],[-1.6,.2]],v:[[0,0],[1.8,.4],[.1,2.2],[0,0],[.2,.1],[0,0],[1.8,1],[.2,.2]],enabled:words.map(()=>true),query:3,key:2,T:1,mask:true});
let s=initial(),pin=null;
function calculate(){const scores=s.q.map(q=>s.k.map(k=>dot(q,k)/Math.sqrt(2)));const A=scores.map((row,j)=>{const z=row.map((v,i)=>!s.enabled[i]||(s.mask&&i>j)?-Infinity:v);return z.every(v=>v===-Infinity)?z.map(()=>0):softmax(z,s.T)});const y=A.map(row=>[0,1].map(d=>row.reduce((sum,a,i)=>sum+a*s.v[i][d],0)));return {scores,A,y};}
const slider=(kind,d,label)=>`<label class="control"><span>${label}</span><input aria-label="${label}" data-kind="${kind}" data-d="${d}" type="range" min="-3" max="3" step="0.01" value="${s[kind][kind==='q'?s.query:s.key][d]}"><output></output></label>`;
function controls(){ $('#vector-controls').innerHTML=slider('q',0,'Q x')+slider('q',1,'Q y')+slider('k',0,'K x')+slider('k',1,'K y');$('#value-controls').innerHTML=slider('v',0,'Value x')+slider('v',1,'Value y');document.querySelectorAll('[data-kind]').forEach(el=>el.oninput=()=>{s[el.dataset.kind][el.dataset.kind==='q'?s.query:s.key][+el.dataset.d]=+el.value;render()});}
const cx=220,cy=168,unit=43;
function vectorSVG(){let h='';for(let n=-3;n<=3;n++){h+=`<path d="M${cx+n*unit} 25V305 M65 ${cy+n*unit}H375" stroke="${n?'#213145':'#607080'}"/>`;if(n)h+=`<text x="${cx+n*unit}" y="325" text-anchor="middle">${n}</text>`;}s.k.forEach((k,i)=>{const x=cx+k[0]*unit,y=cy-k[1]*unit;h+=`<g data-key="${i}" class="handle"><line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="${i===s.key?'#ffcd75':'#567a92'}" stroke-width="${i===s.key?3:1}"/><circle cx="${x}" cy="${y}" r="12" fill="${i===s.key?'#ffcd75':'#567a92'}"/><text x="${x+15}" y="${y+4}">${i===s.key?'K: '+words[i]:''}</text></g>`});const q=s.q[s.query],x=cx+q[0]*unit,y=cy-q[1]*unit;h+=`<g data-query="1" class="handle"><line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="#88f0d4" stroke-width="4"/><circle cx="${x}" cy="${y}" r="11" fill="#88f0d4" stroke="#0b1622" stroke-width="3"/><text x="${x-12}" y="${y-17}" text-anchor="end">Q: ${words[s.query]}</text></g>`;$('#vectors').innerHTML=h;}
function render(){const t=calculate(),a=t.A[s.query],y=t.y[s.query];$('#tokens').innerHTML=words.map((w,i)=>`<button data-token="${i}" aria-pressed="${i===s.query}" class="${i===s.query?'active':''}">${w}</button>`).join('');$('#temp').textContent=s.T.toFixed(2);$('#vector-title').textContent=`Query: ${words[s.query]} · Key: ${words[s.key]}`;$('#value-title').textContent=`Value from “${words[s.key]}”`;vectorSVG();document.querySelectorAll('[data-kind]').forEach(el=>{const val=s[el.dataset.kind][el.dataset.kind==='q'?s.query:s.key][+el.dataset.d];el.value=val;el.nextElementSibling.textContent=val.toFixed(2)});
$('#weights').innerHTML=words.map((w,i)=>`<div class="weight-row ${s.mask&&i>s.query?'muted':''}"><input type="checkbox" data-enabled="${i}" aria-label="Allow ${w}" ${s.enabled[i]?'checked':''}><button data-keyselect="${i}" class="${i===s.key?'active':''}">${w}</button><div class="bar"><i style="width:${a[i]*100}%"></i><span>${!s.enabled[i]?'blocked':s.mask&&i>s.query?'future masked':'score '+t.scores[s.query][i].toFixed(2)}</span></div><span>${(a[i]*100).toFixed(1)}%</span></div>`).join('');$('#sum').textContent=a.some(x=>x)?`Weight sum = ${a.reduce((x,y)=>x+y,0).toFixed(6)}`:'No available sources. Mixture set to zero; softmax is undefined for an all-masked row.';
let x=220,z=140,h='<path d="M20 140H420 M220 15V265" stroke="#405063"/>';a.forEach((v,i)=>{const nx=x+v*s.v[i][0]*32,nz=z-v*s.v[i][1]*32;h+=`<path d="M${x} ${z}L${nx} ${nz}" stroke="${i===s.key?'#ffcd75':'#6ba1ba'}" stroke-width="5"/><circle cx="${nx}" cy="${nz}" r="3" fill="#eee"/>`;x=nx;z=nz});h+=`<path d="M220 140L${x} ${z}" stroke="#88f0d4" stroke-width="2" stroke-dasharray="5 4"/><circle cx="${x}" cy="${z}" r="6" fill="#88f0d4"/><text x="20" y="255">Segments = aᵢ × vᵢ · dotted line = sum (fixed scale)</text>`;$('#mixture').innerHTML=h;$('#result').textContent=`Σ aᵢvᵢ = [${y.map(v=>v.toFixed(4)).join(', ')}]`;$('#baseline').textContent=pin?`Pinned “${words[pin.query]}”: [${pin.y.map(v=>v.toFixed(4)).join(', ')}] · Δ = [${y.map((v,i)=>(v-pin.y[i]).toFixed(4)).join(', ')}]`:'Pin an output above to compare before and after.';
$('#matrix').innerHTML='<span>Q ↓ / K →</span>'+words.map(w=>`<span>${w}</span>`).join('')+words.map((w,j)=>`<span>${w}</span>`+t.A[j].map((v,i)=>`<button data-cell="${j},${i}" aria-label="Query ${w}, key ${words[i]}, weight ${(v*100).toFixed(1)} percent" class="${j===s.query&&i===s.key?'selected':''}" style="background:rgba(86,205,182,${.07+v*.85})">${Math.round(v*100)}</button>`).join('')).join('');$('#cell-info').textContent=`${words[s.key]} → ${words[s.query]}: ${t.scores[s.query][s.key].toFixed(4)} score → ${(a[s.key]*100).toFixed(2)}% weight.`;
}
function select(q,k){s.query=q;s.key=k;controls();render()}
$('#tokens').onclick=e=>{const b=e.target.closest('[data-token]');if(b)select(+b.dataset.token,s.key)};$('#weights').onclick=e=>{const b=e.target.closest('[data-keyselect]');if(b)select(s.query,+b.dataset.keyselect)};$('#weights').onchange=e=>{if(e.target.dataset.enabled!==undefined){s.enabled[+e.target.dataset.enabled]=e.target.checked;render()}};$('#matrix').onclick=e=>{const b=e.target.closest('[data-cell]');if(b)select(...b.dataset.cell.split(',').map(Number))};$('#mask').onchange=e=>{s.mask=e.target.checked;render()};$('#temperature').oninput=e=>{s.T=+e.target.value;render()};$('#snapshot').onclick=()=>{pin={query:s.query,y:[...calculate().y[s.query]]};render()};$('#reset').onclick=()=>{s=initial();pin=null;$('#mask').checked=true;$('#temperature').value=1;$('#challenge').textContent='Predict a change first, then test it with the controls.';controls();render()};
let drag=null;$('#vectors').onpointerdown=e=>{const target=e.target.closest('[data-query],[data-key]');if(!target)return;drag=target.hasAttribute('data-query')?'q':'k';if(drag==='k')s.key=+target.dataset.key;$('#vectors').setPointerCapture(e.pointerId);controls();render();e.preventDefault()};$('#vectors').onpointermove=e=>{if(!drag)return;const pt=new DOMPoint(e.clientX,e.clientY).matrixTransform($('#vectors').getScreenCTM().inverse());s[drag][drag==='q'?s.query:s.key]=[(pt.x-cx)/unit,(cy-pt.y)/unit].map(v=>Math.max(-3,Math.min(3,v)));render()};$('#vectors').onpointerup=$('#vectors').onpointercancel=()=>drag=null;
document.querySelectorAll('[data-challenge]').forEach(b=>b.onclick=()=>{if(b.dataset.challenge==='route'){select(3,2);$('#challenge').textContent='Drag the green Q toward the blue key. Can you raise its weight above 70%? Watch fluffy’s weight fall.'}if(b.dataset.challenge==='value'){select(3,2);pin={query:3,y:[...calculate().y[3]]};$('#challenge').textContent='Move Value y from 2.2 to 3, or reduce it to 0. The weights stay fixed. (Vector controls are bounded at ±3.)';render()}if(b.dataset.challenge==='future'){select(2,7);$('#challenge').textContent='Forest is in the future of blue: its weight is zero. Turn off Causal mask and inspect the same cell.'}});
window.attentionLab={get state(){return structuredClone(s)},calculate};controls();render();
