// Scene boundaries matched against the published videos and creator's timed captions.
// English teaching cues are newly written; source videos remain embedded on YouTube.
const raw=[
[5,0,43,'gpt','Generative · Pretrained · Transformer','Point to the three words in order. Distinguish generation, pretraining on data, and the Transformer architecture inside.','intro'],
[5,43,105,'modalities','One architecture, many kinds of data','The architecture also supports audio, images, and translation. Here we follow a decoder-style next-token predictor.','intro'],
[5,105,183,'generate','Predict → sample → append → repeat','Show the distribution and select a word. Feed it back as input and predict again. The sentence is not produced all at once.','generation'],
[5,183,235,'tokens','Text becomes columns of numbers','Split “To date, the cleverest thinker of all time was” into tokens and transform each into a column vector. Words and tokens need not coincide.','token'],
[5,235,275,'model','Same word, different context','Compare machine learning model and fashion model. Both start from the same model embedding; surrounding information moves them in different directions.','context'],
[5,275,345,'architecture','Attention ↔ Multilayer perceptron','Attention transfers information between columns. The MLP independently applies the same transformation to each column. Repeat these two operations.','architecture'],
[5,345,396,'chat','Autocompletion becomes a conversation','Start a dialogue and repeatedly predict the continuation after AI Assistant. Real dialogue models also undergo additional training.','generation'],
[5,396,440,'roadmap','Beginning, ending, then the middle','This chapter prepares the input and output stages. Attention follows in the next chapter; MLP and training details come later.','roadmap'],
[5,440,499,'learning','Learn the parameters, not a handwritten rule','Adjust trainable parameters using examples of inputs and desired outputs. This is different from directly programming the solution procedure.','learning'],
[5,499,532,'regression','Two parameters: slope and intercept','Move slope and intercept. The points are data; the line has two trainable numbers. Extend that distinction to 175 billion weights.','regression'],
[5,532,626,'tensors','All data is represented as numbers','Inputs, intermediate states, and outputs are arrays of numbers. Higher dimensions keep the same principle, structured for backpropagation.','tensors'],
[5,626,747,'weights','Weights are not the input data','Blue and red entries are trainable weights; gray entries are data from this input. Select a row and demonstrate multiply-and-add.','weights'],
[5,747,807,'lookup','The embedding matrix Wᴱ','Each vocabulary token has one column. Selecting a token retrieves its initial embedding, before context is considered.','lookup'],
[5,807,875,'dimensions','12,288 dimensions → a 3D view','Three numbers can be plotted in 3D; GPT-3 uses 12,288 dimensions. This is a low-dimensional projection, not a claim that meaning has only three axes.','space'],
[5,875,898,'tower-neighbors','Words near “tower”','Words such as building and skyscraper cluster near tower. These are the same GloVe 50D vectors used by the source, not GPT-3 weights.','neighbors'],
[5,898,959,'analogy','king + (woman − man) ≈ queen','Translate the yellow difference vector to the tip of king. As the source emphasizes, it does not land exactly on queen. Compare the family pair too.','analogy'],
[5,959,984,'countries','Directions can encode relationships','Add Italy − Germany to Hitler as a historical word-association example. Proximity reflects language-data relationships, not an exact semantic equation.','analogy'],
[5,984,995,'food','sushi + (Germany − Japan)','Test the same difference-vector idea with foods. Bratwurst is a nearby example, not an exact vector equality.','analogy'],
[5,995,1026,'dot','Dot product measures alignment','Rotate the arrow: aligned is positive, perpendicular is zero, opposite is negative. Component products on the right sum to the same dot product.','dot'],
[5,1026,1072,'plural','A direction for plurality','Compare dot products of singular/plural words with the cats − cat direction. This is a tendency in learned representations, not a universal rule.','plural'],
[5,1072,1105,'embedding-count','50,257 × 12,288 = 617,558,016','The input matrix alone has about 618 million weights: vocabulary size times embedding dimension.','counts'],
[5,1105,1189,'king-context','A vector can absorb a whole context','Add Scotland, murdered predecessor, and Shakespearean language to king in sequence, making the representation more specific than an isolated word.','context'],
[5,1189,1222,'context-window','A finite context window','GPT-3 has a 2,048-token context window, with 12,288 numbers per column. Distinguish column count from dimension per column.','window'],
[5,1222,1305,'unembedding','Only the final vector predicts the next token','Take the last column of “Harry Potter … least favourite teacher, Professor” and map it to vocabulary scores. During training, every position can predict.','unembedding'],
[5,1305,1342,'unembedding-count','The unembedding matrix Wᵁ','The input shape is reversed: 50,257 rows × 12,288 columns. Counting this as a separate matrix, as the source does, adds 617,558,016 weights.','counts'],
[5,1342,1432,'softmax','Logits → exponentials → probabilities','Logits can be negative and are not probabilities. Exponentiate and divide by the sum to obtain nonnegative values totaling 1.','softmax'],
[5,1432,1563,'temperature','Temperature changes the distribution','Higher T flattens the distribution; approaching zero concentrates it at the maximum. T=0 uses the argmax limit, avoiding division by zero.','softmax'],
[5,1563,1634,'chapter5-end','Four ingredients for attention','Embeddings, dot products, softmax, and learned matrices connect in the next chapter. Source announcements and supporter credits remain available in the reference video.','roadmap'],
[6,0,99,'recap','Embeddings can carry contextual meaning','Briefly revisit input and output. Now open the mechanism that turns word vectors into context-aware vectors.','architecture'],
[6,99,173,'mole','One token, three meanings of “mole”','Compare “American shrew mole,” “One mole of carbon dioxide,” and “Take a biopsy of the mole.” Mole starts with the same vector; context changes its update direction.','context'],
[6,173,211,'eiffel','Tower → Eiffel Tower → Miniature Eiffel Tower','Add Eiffel to tower, then miniature. Adding information can weaken the association with height.','context'],
[6,211,269,'mystery','“Therefore the murderer was …”','If only the final was vector predicts next, story clues must reach it. Attention is not limited to nearby adjectives.','mystery'],
[6,269,377,'adjectives','A fluffy blue creature roamed the verdant forest','Draw fluffy and blue → creature, and verdant → forest. This head is a hypothetical teaching example in the source, not a discovered real-model head.','adjectives'],
[6,377,467,'query','Query: “Any adjectives in front of me?”','Multiply the creature embedding by WQ: 12,288 dimensions become a 128-dimensional query, indicating what information to seek.','query'],
[6,467,507,'key','Key: “I am an adjective, and I am here”','Multiply the same embeddings by a different matrix WK. In this example, fluffy and blue keys align with the creature query.','key'],
[6,507,577,'scores','Every key meets every query','Queries receive along the top; keys supply along the left. Select the creature column and inspect large fluffy/blue dot products. Keep arrows consistent with the matrix orientation.','scores'],
[6,577,615,'attention-softmax','Normalize each column','Apply softmax to this column. Each column sums to 1; in the source display, fluffy and blue receive almost all the weight.','attention-softmax'],
[6,615,668,'equation','A compact equation for the same computation','KᵀQ contains all pairwise dot products. Scale by √dₖ and apply column-wise softmax. This lab consistently uses column vectors and writes the update as V A.','equation'],
[6,668,762,'mask','Do not let the future reveal the answer','Each position predicts its next word without seeing future words. Apply −∞ before softmax; zeroing afterward alone breaks normalization.','mask'],
[6,762,790,'quadratic','Twice the context, four times the pairs','Double context length n and watch the n² grid quadruple. This is dense attention-score storage, not an exact formula for total model memory.','quadratic'],
[6,790,862,'value','Value: what information should be added?','The embedding of fluffy differs from the fluffiness direction sent to another word. WV creates a vector to add to the receiver.','value'],
[6,862,926,'weighted-values','0.42 v_fluffy + 0.58 v_blue','After Q/K determine weights, multiply each V by its column coefficient and add tip-to-tail to form ΔE. Changing V does not change attention weights.','weighted-values'],
[6,926,944,'residual','E′ = E + ΔE, for every token','Add the update to the original embedding; do not replace it. Apply the same operation to every column, not only creature.','residual'],
[6,944,1026,'qkv-count','Why not a huge square value matrix?','Q/K are 128 × 12,288. A square 12,288-dimensional V matrix would require about 151 million weights, motivating low-rank factorization.','counts'],
[6,1026,1101,'lowrank','Value down → value up','12,288 → 128 → 12,288. The source calls these value-down and value-up for explanation. The update returns to the original space but can span only a limited number of directions.','lowrank'],
[6,1101,1159,'cross','Cross-attention: two different sequences','Compare “I do not want to pet it” and “Je ne veux pas le caresser.” Q and K/V come from different sequences. The source-aligned correspondence diagram distinguishes cross-attention from self-attention.','cross'],
[6,1159,1231,'harry','Context does more than attach adjectives','Crashed updates car; wizard relates to Harry differently from Queen / Sussex / William. Do not restrict head roles to grammar.','context'],
[6,1231,1336,'heads','96 heads propose 96 updates','Each head has its own Q/K/V, attention pattern, and update. Sum updates into the original columns. Switch heads to compare.','heads'],
[6,1336,1399,'output','Concatenate, then multiply by Wᴼ','The output matrix places each head value-up matrix side by side. Mixing small values, concatenating, then projecting is equivalent to projecting each head and summing.','output'],
[6,1399,1456,'deeper','Contextual meanings meet richer contexts','Repeat attention and MLP. Contextual columns exchange information again, supporting more abstract representations.','architecture'],
[6,1456,1494,'attention-count','96 heads × 96 layers','Q, K, value-down, and value-up total 57,982,058,496 attention weights—not all 175 billion. Many weights belong to the MLPs.','counts'],
[6,1494,1569,'parallel','Parallel computation makes scale possible','Pairwise dot products and column updates can run in parallel. Recap the system, then connect to later chapters on MLPs and learning.','parallel']
];
export const scenes=raw.map(([chapter,start,end,id,title,cue,kind])=>({chapter,start,end,id,title,cue,kind}));
export const videos={5:'wjZofJX0v4M',6:'eMlx5fFNoYc'};
export const groups=[['Chapter 5 / Input and output','gpt'],['Embedding / Semantic space','lookup'],['Chapter 6 / Context updates','mole'],['Q · K · Softmax / Where to read','query'],['V · Multi-head / What to add','value']];
