import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
const host=document.querySelector('#three'),labels=document.querySelector('#three-labels');
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.append(renderer.domElement);
const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(34,1,.1,100);camera.position.set(8,5,11);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=true;controls.target.set(0,.6,0);controls.update();
let group=new THREE.Group();scene.add(group);let marker=[],active=false;
const V=a=>new THREE.Vector3(...a);const C=x=>new THREE.Color(x);
function dispose(){group.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose()});scene.remove(group);group=new THREE.Group();scene.add(group);labels.replaceChildren();marker=[];}
function line(a,b,color='#666',opacity=.5){const g=new THREE.BufferGeometry().setFromPoints([V(a),V(b)]);const o=new THREE.Line(g,new THREE.LineBasicMaterial({color,transparent:true,opacity}));group.add(o);}
function arrow(a,b,color){const d=V(b).sub(V(a));if(d.length()<.0001)return;group.add(new THREE.ArrowHelper(d.clone().normalize(),V(a),d.length(),C(color),.14,.07));}
function label(text,p,color){const el=document.createElement('span');el.className='label3';el.textContent=text;el.style.color=color;labels.append(el);const leader=document.createElement('span');leader.className='leader3';leader.style.background=color;labels.append(leader);marker.push({el,leader,p:V(p)});}
export function showSpace(items,{azimuth=0,target=[0,.5,0],fit=5}={}){active=true;host.style.display='block';labels.style.display='block';dispose();for(let i=-6;i<=6;i++){line([i,0,-6],[i,0,6],'#527987',.3);line([-6,0,i],[6,0,i],'#527987',.3)}for(const b of [[6,0,0],[0,6,0],[0,0,6]]){line(b.map(x=>-x),b,'#ddd',.7)}
for(const it of items){arrow(it.from||[0,0,0],it.to,it.color||'#ddd');if(it.label)label(it.label,it.to,it.color||'#ddd');}
if(azimuth!==null){camera.position.set(target[0]+fit*1.3*Math.cos(azimuth),target[1]+fit*.45,target[2]+fit*1.3*Math.sin(azimuth));controls.target.set(...target);controls.update();}}
export function hideSpace(){active=false;host.style.display='none';labels.style.display='none'}
export function tickSpace(){if(!active)return;const r=host.getBoundingClientRect();if(r.width<1||r.height<1)return;const sz=new THREE.Vector2();renderer.getSize(sz);if(sz.x!==r.width||sz.y!==r.height){renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}controls.update();renderer.render(scene,camera);const used=[];for(const m of marker){const p=m.p.clone().project(camera);const px=(p.x+1)/2*r.width,py=(-p.y+1)/2*r.height;const hidden=p.z>1||px<0||px>r.width||py<0||py>r.height;m.el.style.display=hidden?'none':'';m.leader.style.display=hidden?'none':'';if(hidden)continue;const w=m.el.offsetWidth,h=m.el.offsetHeight;let x=Math.max(5,Math.min(r.width-w-5,px+8)),y=Math.max(5,Math.min(r.height-h-5,py+5));for(let attempt=0;attempt<20;attempt++){if(!used.some(q=>x<q.x+q.w+5&&x+w+5>q.x&&y<q.y+q.h+4&&y+h+4>q.y))break;y=Math.max(5,Math.min(r.height-h-5,py+(attempt%2===0?1:-1)*Math.ceil((attempt+1)/2)*(h+5)));}used.push({x,y,w,h});m.el.style.left=x+'px';m.el.style.top=y+'px';const ex=x,ey=y+h/2,dx=ex-px,dy=ey-py;m.leader.style.left=px+'px';m.leader.style.top=py+'px';m.leader.style.width=Math.hypot(dx,dy)+'px';m.leader.style.transform='rotate('+Math.atan2(dy,dx)+'rad)';}}
export function resetCamera(){camera.position.set(8,5,11);controls.target.set(0,.5,0);controls.update();}
export const spaceState=()=>({active,camera:camera.position.toArray(),labels:marker.length,webgl:renderer.getContext().isContextLost()?'lost':'ok'});
