import {examples,vocab,params,forward,gradients,resetParams,getRef,setRef,gradRef} from '../train/model.js';
const $=s=>document.querySelector(s), exSel=$('#example');examples.forEach((e,i)=>exSel.add(new Option(`${e.context.join(' ')} → ${e.target}`,i)));
let ex=examples[0],history=[],trail=[],surface,refs,range,arrowEnd=null;const fmt=(x,n=4)=>Number(x).toFixed(n);
function chooseRefs(){const y=vocab.indexOf(ex.target);refs={w:{group:'O',idx:[0,y]},b:{group:'c',idx:[y]}};range={w:[getRef(refs.w)-1.4,getRef(refs.w)+1.4],b:[getRef(refs.b)-1.4,getRef(refs.b)+1.4]};history=[];trail=[];arrowEnd=null;record()}
function record(){const f=forward(ex.context,ex.target);history.push(f.loss);trail.push({w:getRef(refs.w),b:getRef(refs.b),loss:f.loss})}
function computeSurface(n=31){const ow=getRef(refs.w),ob=getRef(refs.b),xs=[],ys=[],z=[];for(let i=0;i<n;i++)xs.push(range.w[0]+(range.w[1]-range.w[0])*i/(n-1));for(let j=0;j<n;j++)ys.push(range.b[0]+(range.b[1]-range.b[0])*j/(n-1));for(const b of ys){const row=[];setRef(refs.b,b);for(const w of xs){setRef(refs.w,w);row.push(forward(ex.context,ex.target).loss)}z.push(row)}setRef(refs.w,ow);setRef(refs.b,ob);return{xs,ys,z}}
function renderPlot(){const f=forward(ex.context,ex.target),w=getRef(refs.w),b=getRef(refs.b),g=gradients(ex.context,ex.target).g,lr=+$('#lr').value,nw=w-lr*gradRef(g,refs.w),nb=b-lr*gradRef(g,refs.b);setRef(refs.w,nw);setRef(refs.b,nb);const nl=forward(ex.context,ex.target).loss;setRef(refs.w,w);setRef(refs.b,b);arrowEnd={w:nw,b:nb,loss:nl};const traces=[{type:'surface',x:surface.xs,y:surface.ys,z:surface.z,colorscale:[[0,'#15b8a6'],[.45,'#63a7a5'],[1,'#f07468']],showscale:false,opacity:.9,hovertemplate:'weight %{x:.3f}<br>bias %{y:.3f}<br>loss %{z:.4f}<extra></extra>',contours:{z:{show:true,usecolormap:false,color:'#ffffff55',width:1}}},{type:'scatter3d',mode:'lines+markers',x:trail.map(p=>p.w),y:trail.map(p=>p.b),z:trail.map(p=>p.loss+.012),line:{color:'#19e0c4',width:7},marker:{color:'#19e0c4',size:4},hoverinfo:'skip'},{type:'scatter3d',mode:'markers+text',x:[w],y:[b],z:[f.loss+.035],text:['CURRENT'],textposition:'top center',marker:{size:10,color:'#ffca5c',line:{color:'#624400',width:2}},hovertemplate:`current<br>loss ${f.loss.toFixed(4)}<extra></extra>`},{type:'scatter3d',mode:'lines+markers',x:[w,nw],y:[b,nb],z:[f.loss+.05,nl+.05],line:{color:'#ff554f',width:9},marker:{size:[2,7],color:'#ff554f',symbol:['circle','diamond']},hovertemplate:'projected next step<extra></extra>'}];Plotly.react('plot',traces,{margin:{l:0,r:0,t:5,b:0},paper_bgcolor:'#fff',scene:{bgcolor:'#f8fbfd',xaxis:{title:`output weight O[0, ${f.y}]`},yaxis:{title:`target bias c[${f.y}]`},zaxis:{title:'cross-entropy loss'},camera:{eye:{x:1.45,y:1.45,z:1.08}},aspectratio:{x:1.15,y:1.15,z:.72}},showlegend:false},{responsive:true,displaylogo:false})}
function render(){const f=forward(ex.context,ex.target),g=gradients(ex.context,ex.target).g,w=getRef(refs.w),b=getRef(refs.b);$('#step').textContent=Math.max(0,history.length-1);$('#sentence').innerHTML=ex.sentence.replace('___',`<b>${ex.target}</b>`);$('#context').textContent=`[ ${ex.context.map(x=>'“'+x+'”').join(', ')} ]`;$('#target').textContent=ex.target;$('#prob').textContent=(f.probs[f.y]*100).toFixed(1)+'%';$('#loss').textContent=fmt(f.loss);const order=f.probs.map((p,i)=>({p,i})).sort((a,b)=>b.p-a.p);$('#bars').innerHTML=order.map(o=>`<div class="barrow ${o.i===f.y?'target':''}"><span>${vocab[o.i]}</span><div class="track"><div class="fill" style="width:${Math.max(.5,o.p*100)}%"></div></div><code>${(o.p*100).toFixed(1)}%</code></div>`).join('');$('#wLabel').textContent=`output weight O[0, ${f.y}] → “${ex.target}”`;$('#bLabel').textContent=`output bias c[${f.y}] → “${ex.target}”`;for(const [id,v] of [['#wSlider',w],['#wNumber',w],['#bSlider',b],['#bNumber',b]])$(id).value=v;$('#gradient').textContent=`[ ${fmt(gradRef(g,refs.w),5)}, ${fmt(gradRef(g,refs.b),5)} ]`;$('#updateRule').textContent=`θ ← θ − ${fmt(+$('#lr').value,2)} × ∇L`;drawHistory();renderPlot()}
function drawHistory(){const svg=$('#history'),vals=history,lo=Math.min(...vals),hi=Math.max(...vals),den=hi-lo||1,pts=vals.map((v,i)=>`${10+i*(500/Math.max(1,vals.length-1))},${8+(v-lo)/den*0+54*(hi-v)/den}`).join(' ');svg.innerHTML=`<line x1="10" y1="62" x2="510" y2="62" stroke="#cbd8e2"/><polyline points="${pts}" fill="none" stroke="#12b8a5" stroke-width="4" vector-effect="non-scaling-stroke"/>`}
function manual(ref,v){setRef(ref,+v);history=[];trail=[];record();surface=computeSurface();arrowEnd=null;$('#change').textContent='Manual parameter change: forward pass, softmax, and loss recomputed.';render()}
['w','b'].forEach(k=>{const ref=()=>refs[k];$(`#${k}Slider`).oninput=e=>{ $(`#${k}Number`).value=e.target.value;manual(ref(),e.target.value)};$(`#${k}Number`).onchange=e=>manual(ref(),e.target.value)});
$('#stepBtn').onclick=()=>{const before=forward(ex.context,ex.target),g=gradients(ex.context,ex.target).g,lr=+$('#lr').value;setRef(refs.w,getRef(refs.w)-lr*gradRef(g,refs.w));setRef(refs.b,getRef(refs.b)-lr*gradRef(g,refs.b));record();const after=forward(ex.context,ex.target);$('#change').textContent=`Loss ${fmt(before.loss)} → ${fmt(after.loss)} · target ${(before.probs[before.y]*100).toFixed(1)}% → ${(after.probs[after.y]*100).toFixed(1)}%`;render()};
$('#reset').onclick=()=>{resetParams();chooseRefs();surface=computeSurface();$('#change').textContent='Deterministic initial parameters restored.';render()};$('#lr').onchange=render;exSel.onchange=()=>{ex=examples[+exSel.value];resetParams();chooseRefs();surface=computeSurface();$('#change').textContent='New example, new target parameters, same deterministic model.';render()};
resetParams();chooseRefs();surface=computeSurface();render();window.landscapeLab={snapshot:()=>({example:ex,forward:forward(ex.context,ex.target),gradient:gradients(ex.context,ex.target),refs,history:[...history],trail:[...trail],arrowEnd}),step:()=>$('#stepBtn').click()};
