import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {words,X,WQ,WK,WV,trace,multi} from './math.js';
const $=s=>document.querySelector(s),C={q:'#ffcc72',k:'#6ddbd5',v:'#ba9af7',a:'#ff8d8d',white:'#e7effa',muted:'#7990a8'};
const chapters=[
 {name:'ことば → ベクトル',title:'単語は、数字の束になる。',idea:'ひとつの単語に、ひとつのベクトル。',text:'モデルが扱うのは文字そのものではなく数の並び。位置の情報も加え、同じ単語でも「どこにあるか」を区別します。ここでは4トークン・3成分に縮めます。',formula:'<i>X</i> = Embedding(tokens) + Position',cues:['「青い 猫 が 眠る」。まず、文をトークンに分ける。実際の分割は、単語の区切りと一致するとは限らない。','各トークンを、数字が縦に並んだベクトルへ。この教材の X は位置情報を含めた説明用の値。','まだ、隣の単語の情報は混ざっていない。ここから「文脈」をつくっていく。'],cam:[[8,5,14],[3,3.2,14]],target:[0,0,0]},
 {name:'Q / K / V',title:'読む目的と、渡す情報。',idea:'同じ入力から、3つの役割をつくる。',text:'Query は探す側、Key は照合される側、Value は渡す内容。全トークンに同じ学習パラメータ W を掛けます。ここでは固定した説明用行列です。',formula:'<span class="q">Q</span> = XW<sub>Q</sub>　<span class="k">K</span> = XW<sub>K</sub>　<span class="v">V</span> = XW<sub>V</sub>',cues:['ひとつの入力 X が、3つの線形変換へ分岐する。Q と K は2成分、V は3成分。','黄色の Query と、水色の Key は「どこから読むか」を決めるためのもの。','紫の Value は、実際に運ばれる情報。同じ単語から出発しても、3つの役割は別々。'],cam:[[8,4,17],[1.5,1.6,16]],target:[0,.1,0]},
 {name:'内積で照合',title:'向きが合えば、強く読む。',idea:'Query と Key の内積が、相性になる。',text:'矢印は Q/K の全2成分を同じ倍率で描いています。長さも向きも内積に影響します。単なる角度の比較や、意味の正しさの判定ではありません。',formula:'s<sub>ij</sub> = <span class="q">q<sub>i</sub></span> · <span class="k">k<sub>j</sub></span> / √2',cues:['読む側の Query を1本選ぶ。同じ原点から、すべての Key を比べよう。','内積 q · k は、2つの成分の積を足したもの。向きが揃い、長いほど大きくなる。','√dₖ で割り、スコアの大きさを調整する。この教材では dₖ = 2。まだ確率ではない。'],cam:[[5,7,13],[.2,1.5,13]],target:[0,.4,0]},
 {name:'注意の行列',title:'相性を、読む割合に変える。',idea:'ひとつの行の合計が、1になる。',text:'横が情報源 Key、奥が読む側 Query。柱の高さは注意の重み A。未来を隠すと、先のトークンの重みは0。温度を下げると分布が鋭くなります。',formula:'<i>A</i> = softmax((QKᵀ / √2) / τ + M)',cues:['全 Query と全 Key の内積を、4×4の表に並べる。ひとつの行が、ひとりの読み手。','文章生成では未来を見せない。j > i の場所を −∞ にして、softmax 後の重みを0にする。','softmax は各行を正規化する。右の温度を動かすと、注意の集中と分散が変わる。'],cam:[[9,10,12],[3,11,12]],target:[0,.8,0]},
 {name:'Value を合成',title:'読む割合で、情報を混ぜる。',idea:'重み × 内容。それを全部、足す。',text:'選んだ Query の出力は Σⱼ Aᵢⱼvⱼ。矢印を先端から順につなぎます。「猫」の Value だけを変えると、注意の割合を変えずに出力だけが動きます。',formula:'<span class="a">o<sub>i</sub></span> = Σ<sub>j</sub> A<sub>ij</sub> <span class="v">v<sub>j</sub></span>',cues:['Attention が決めたのは「読む割合」。いま、その割合を Value の各成分に掛ける。','加重した矢印を、先端から順につなぐ。出発点から最後の先端への矢印が出力 o。','「猫」の Value 倍率を変えてみよう。Q/K が同じなら A は不変。それでも出力は変わる。'],cam:[[7,6,12],[2,3,11]],target:[.5,.9,0]},
 {name:'Transformer へ',title:'別々の視点を、ひとつの更新へ。',idea:'Attention は、Transformer の一部。',text:'3つの head は別の W を使います。出力を連結し Wₒ で投影して、残差へ加算。続く MLP は位置ごとに処理します。下段は Post-LN の構造図で、Norm と MLP の計算は省略します。',formula:'X′ = X + Concat(O₁, O₂, O₃) W<sub>O</sub>',cues:['同じ文を見る、異なる head。同じ注意行列のコピーではなく、別々の Q/K/V から計算する。','3つの出力を連結し、Wₒ で3成分に戻す。その更新を元の X に足す。残差は情報の通り道。','この後に Norm・MLP・残差などを重ね、最後の表現から次のトークンを予測する。Attention は「文脈を読む」仕組み。'],cam:[[10,7,17],[8,6,15]],target:[0,-.3,-2]}
];
const state={time:0,playing:!matchMedia('(prefers-reduced-motion: reduce)').matches,query:3,head:0,mask:true,temp:1,gain:1,speed:1,orbit:false};
let model=trace(state),mix=multi(state),chapter=-1,root,labels=[],anim=[],pickables=[],frames=0,last=0,dirty=true,captionIndex=-1;
let renderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=T.SRGBColorSpace;$('#stage').prepend(renderer.domElement);}catch(e){$('#fallback').hidden=false;throw e}
const scene=new T.Scene();scene.fog=new T.FogExp2('#080d15',.014);scene.add(new T.AmbientLight('#b5d9ff',1.5));const light=new T.DirectionalLight('#d7eaff',3);light.position.set(3,8,7);scene.add(light);const rim=new T.PointLight(C.k,45,30);rim.position.set(-5,4,-5);scene.add(rim);
const camera=new T.PerspectiveCamera(39,1,.1,150),orbit=new OrbitControls(camera,renderer.domElement);orbit.enabled=false;orbit.enableDamping=true;orbit.minDistance=7;orbit.maxDistance=32;orbit.enablePan=false;
const V=a=>new T.Vector3(...a),lerp=(a,b,t)=>a.map((v,i)=>v+(b[i]-v)*t),ease=t=>{t=Math.max(0,Math.min(1,t));return t*t*(3-2*t)},range=(p,a,b)=>ease((p-a)/(b-a));
const oldCam=new T.Vector3(),oldTarget=new T.Vector3();let transition=1;
function clear(){if(root){root.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of [o.material].flat()){m.map?.dispose();m.dispose()}});scene.remove(root)}root=new T.Group();scene.add(root);labels=[];anim=[];pickables=[];$('#labels').replaceChildren()}
function label(text,pos,color=C.white,parent=root,major=false){const anchor=new T.Object3D();anchor.position.copy(V(pos));parent.add(anchor);const el=document.createElement('span');el.className='label'+(major?' major':'');el.style.color=color;el.textContent=text;$('#labels').append(el);labels.push({anchor,el});return anchor}
function matrixLabel(text,pos,color,parent){label(text,pos,color,parent);labels[labels.length-1].el.classList.add('matrix-entry')}
function line(a,b,color=C.muted,opacity=.5,parent=root){const m=new T.Line(new T.BufferGeometry().setFromPoints([V(a),V(b)]),new T.LineBasicMaterial({color,transparent:true,opacity}));parent.add(m);return m}
function box(pos,size,color,opacity=.7,parent=root){const m=new T.Mesh(new T.BoxGeometry(...size),new T.MeshStandardMaterial({color,transparent:true,opacity,roughness:.45,metalness:.25}));m.position.copy(V(pos));parent.add(m);return m}
function arrow(a,b,color,parent=root,width=.035){const g=new T.Group();g.position.copy(V(a));parent.add(g);const d=V(b).sub(V(a)),len=d.length();if(len<1e-6)return g;const m=new T.MeshBasicMaterial({color});const shaft=new T.Mesh(new T.CylinderGeometry(width,width,Math.max(.001,len-.17),10),m);shaft.position.y=Math.max(.001,len-.17)/2;const tip=new T.Mesh(new T.ConeGeometry(width*3,.19,14),m);tip.position.y=len-.095;g.add(shaft,tip);g.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d.normalize());return g}
function panel(pos,size,color,parent=root,opacity=.08){const m=box(pos,[...size,.035],color,opacity,parent);const edge=new T.LineSegments(new T.EdgesGeometry(m.geometry),new T.LineBasicMaterial({color,transparent:true,opacity:.4}));m.add(edge);return m}
function path(a,b,color,parent=root,bend=1){const mid=V(a).lerp(V(b),.5);mid.y+=bend;const curve=new T.QuadraticBezierCurve3(V(a),mid,V(b));const l=new T.Line(new T.BufferGeometry().setFromPoints(curve.getPoints(40)),new T.LineBasicMaterial({color,transparent:true,opacity:.4}));parent.add(l);const bead=new T.Mesh(new T.SphereGeometry(.055,10,8),new T.MeshBasicMaterial({color}));parent.add(bead);anim.push((p)=>bead.position.copy(curve.getPoint((p*2)%1)));return l}
function grid(y=-2.15,size=14){const g=new T.GridHelper(size,28,'#29414f','#1b2b38');g.position.y=y;g.material.transparent=true;g.material.opacity=.33;root.add(g)}
function vector(values,pos,color,parent=root,scale=1){const g=new T.Group();g.position.copy(V(pos));g.scale.setScalar(scale);parent.add(g);const h=values.length*.5;panel([0,0,0],[.95,h+.25],color,g,.09);values.forEach((v,i)=>{const y=(values.length-1)*.25-i*.5;box([0,y,.05],[.66,.35,.08],v<0?C.a:color,.18+Math.min(Math.abs(v)*.35,.6),g);label(v.toFixed(2),[0,y,.13],color,g)});return g}
function heatmap(a,parent,pos,size=3,color=C.k){const g=new T.Group();g.position.copy(V(pos));parent.add(g);const cell=size/4;for(let i=0;i<4;i++)for(let j=0;j<4;j++){const w=a[i][j];box([(j-1.5)*cell,(1.5-i)*cell,0],[cell*.87,cell*.87,.055],w?color:'#354052',w?.15+.85*w:.09,g)}return g}
function inputScene(){grid();words.forEach((w,i)=>{const x=(i-1.5)*2.1,g=new T.Group();root.add(g);label(w,[x,1.6,.1],i===state.query?C.q:C.white,g,true);const token=panel([x,1.6,0],[1.4,.6],i===state.query?C.q:C.k,g,.12);token.userData.query=i;pickables.push(token);const v=vector(X[i],[x,-.1,0],i===state.query?C.q:C.k,g);arrow([x,1.15,0],[x,.85,0],C.muted,g,.018);anim.push(p=>{v.scale.y=.05+.95*range(p,.05,.45);v.position.z=-range(p,.45,1)*i*.12});if(i<3)line([x+.75,1.6,0],[x+1.35,1.6,0],C.muted,.5);});label('X  ∈  ℝ⁴ˣ³',[0,-1.5,.2],C.muted);}
function projectionScene(){grid(-2.5);vector(X[state.query],[-4,0,0],C.white);label('x : '+words[state.query],[-4,1.2,0],C.white,root,true);const specs=[['Q',C.q,WQ[state.head],model.Q[state.query],2],['K',C.k,WK[state.head],model.K[state.query],0],['V',C.v,WV[state.head],model.V[state.query],-2]];specs.forEach(([name,color,W,out,y],n)=>{const group=new T.Group();root.add(group);group.position.y=y;path([-3.4,-y,0],[-.9,0,0],color,group,.3);const cols=W[0].length;panel([0,0,0],[2,1.4],color,group);W.forEach((r,i)=>r.forEach((val,j)=>matrixLabel(val.toFixed(1),[(j-(cols-1)/2)*.72,(1-i)*.36,.06],color,group)));label('W'+name,[0,.96,.04],color,group);arrow([1.15,0,0],[2.4,0,0],color,group,.022);const v=vector(out,[3.15,0,0],color,group,.8);label(name,[3.15,1,0],color,group,true);anim.push(p=>{const a=range(p,n*.16,.35+n*.2);group.scale.setScalar(.7+.3*a);v.scale.setScalar(.4+.4*a)})});}
function dotScene(){grid(-2);for(let i=-3;i<=3;i++){line([i,-2,0],[i,3,0],C.muted,.17);line([-3,i,0],[3,i,0],C.muted,.17)}arrow([-3,0,0],[3,0,0],C.muted,root,.013);arrow([0,-2,0],[0,3,0],C.muted,root,.013);label('成分 1',[3.1,-.25,0],C.muted);label('成分 2',[-.4,3,0],C.muted);model.K.forEach((k,j)=>{const end=[k[0]*2,k[1]*2,0];const a=arrow([0,0,0],end,C.k,root,.022);label('k '+words[j],[end[0]+(j%2?.35:-.3),end[1]+.22,.04],C.k);anim.push(p=>a.scale.setScalar(.05+.95*range(p,.05+j*.07,.3+j*.09)))});const q=model.Q[state.query],end=[q[0]*2,q[1]*2,.03];const a=arrow([0,0,.03],end,C.q,root,.046);label('q '+words[state.query],[end[0]+.18,end[1]+.5,.1],C.q,root,true);anim.push(p=>a.scale.setScalar(.4+.6*range(p,0,.35)));const j=1,k=model.K[j],proj=k.map(v=>v*(q[0]*k[0]+q[1]*k[1])/(k[0]*k[0]+k[1]*k[1]));line(end,[proj[0]*2,proj[1]*2,0],C.q,.5);label('q · k猫 = '+(q[0]*k[0]+q[1]*k[1]).toFixed(3),[0,-1.7,.1],C.white);}
function matrixScene(){grid(-.06,12);const step=1.35;for(let i=0;i<4;i++){label(words[i],[-3.55,.05,(i-1.5)*step],i===state.query?C.q:C.muted);label(words[i],[(i-1.5)*step,.05,3.05],C.k);for(let j=0;j<4;j++){const w=model.A[i][j],x=(j-1.5)*step,z=(i-1.5)*step;box([x,-.02,z],[1.22,.04,1.22],i===state.query?C.q:C.k,.1);const h=Math.max(.015,w*2.7),b=box([x,h/2,z],[.75,h,.75],i===state.query?C.q:C.k,w?.85:.1);b.userData.query=i;pickables.push(b);label(w?Math.round(w*100)+'%':'×',[x,h+.28,z],i===state.query?C.q:C.muted);anim.push(p=>{const f=range(p,.04+(i+j)*.035,.5+(i+j)*.035);b.scale.y=.01+.99*f;b.position.y=h*b.scale.y/2})}}label('KEY → 情報源',[0,0,4],C.k,root,true);label('QUERY',[-3.8,.1,-3.1],C.q);label('高さ = Aᵢⱼ',[3.6,1.5,0],C.white);}
function valueScene(){grid(-1.7,12);const a=model.A[state.query],colors=[C.k,C.v,C.q,C.a],factor=4;let cur=[-1.3,-.7,-.3];const origin=[...cur];a.forEach((w,j)=>{const part=model.V[j].map(v=>v*w*factor),start=[...cur],end=start.map((v,k)=>v+part[k]);const g=arrow([0,0,0],part,colors[j],root,.04);const separate=[(j-1.5)*1.6,-.7,-1];g.position.copy(V(separate));const lp=[j<2?-2.8:3.1,j%2===0?1.9:.8,.5];const lab=label(w.toFixed(2)+' × v'+words[j],lp,colors[j]);const leader=line(lp,start.map((v,k)=>v+part[k]*.5),colors[j],.45);anim.push(p=>{const f=range(p,.18+j*.08,.48+j*.09),at=lerp(separate,start,f);g.position.copy(V(at));g.visible=w>0;lab.visible=w>0;leader.visible=w>0;const points=[...lp,...at.map((v,k)=>v+part[k]*.5)];leader.geometry.attributes.position.array.set(points);leader.geometry.attributes.position.needsUpdate=true;leader.geometry.computeBoundingSphere()});cur=end});const result=arrow(origin,cur,C.white,root,.027);const l=label('o = ['+model.O[state.query].map(x=>x.toFixed(2)).join(', ')+']',[.3,3.4,.1],C.white,root,true);anim.push(p=>{result.visible=p>.66;l.visible=p>.66});label('同じ倍率で描いた3成分 / 白 = 合計',[0,-1.6,.1],C.muted);}
function finalScene(){grid(-3.8,18);const colors=[C.k,C.v,C.a];mix.heads.forEach((h,i)=>{const g=new T.Group();g.position.set((i-1)*3,1.6,0);root.add(g);heatmap(h.A,g,[0,0,0],2,colors[i]);label('HEAD 0'+(i+1),[0,1.35,0],colors[i],g,true);path([0,-1.2,0],[-g.position.x,-2.1,-2.3],colors[i],g,-.4);anim.push(p=>{g.position.z=-range(p,.02,.5)*Math.abs(i-1)*.5})});panel([0,-.55,-2.5],[5.8,.65],C.white);label('Concat → Wₒ → + X',[0,-.55,-2.42],C.white,root,true);path([-4,1.6,0],[-1.5,-.55,-2.4],C.q,root,-2);label('残差 X',[-4,-.1,-.6],C.q);const layers=[['Norm',C.muted],['MLP',C.v],['+ 残差',C.q],['Norm →',C.k]];layers.forEach(([name,c],i)=>{const x=(i-1.5)*2.1,z=-4,y=-1.8;const layer=new T.Group();root.add(layer);panel([x,y,z],[1.8,.75],c,layer,.1);label(name,[x,y,z+.06],c,layer);if(i<3)arrow([x+1,y,z],[x+1.2,y,z],c,layer,.018);anim.push(p=>{layer.visible=p>.25+i*.12})});line([-2.4,-.9,-2.5],[-3.15,-1.4,-4],C.white,.6);}

const builders=[inputScene,projectionScene,dotScene,matrixScene,valueScene,finalScene];
function updateModel(){model=trace(state);mix=multi(state);dirty=true;updateReadout()}
function updateReadout(){const row=model.A[state.query];$('#readout').innerHTML='<div style="color:#93a3b8">'+words[state.query]+' が読む割合 / Head '+(state.head+1)+'</div>'+row.map((v,i)=>'<div class="barrow"><span>'+words[i]+'</span><div class="bar"><i style="width:'+v*100+'%"></i></div><span>'+ (v*100).toFixed(1)+'%</span></div>').join('')+'<div style="margin-top:5px">Σ = '+row.reduce((a,b)=>a+b,0).toFixed(6)+'<br>o = ['+model.O[state.query].map(x=>x.toFixed(3)).join(', ')+']</div>';updateMatrixData();$('#temp-out').value=state.temp.toFixed(2);$('#gain-out').value=state.gain.toFixed(2);$('#tokens').querySelectorAll('button').forEach((b,i)=>{b.classList.toggle('active',i===state.query);b.setAttribute('aria-pressed',String(i===state.query))})}
function updateMatrixData(){const table=(name,m)=>'<h4>'+name+'</h4><table>'+m.map(r=>'<tr>'+r.map(v=>'<td>'+(Number.isFinite(v)?v.toFixed(3):'−∞')+'</td>').join('')+'</tr>').join('')+'</table>';$('#matrix-data').innerHTML=table('X (4×3)',X)+table('WQ (3×2)',WQ[state.head])+table('WK (3×2)',WK[state.head])+table('WV (3×3)',WV[state.head])+table('Q = XWQ',model.Q)+table('K = XWK',model.K)+table('V（倍率介入後）',model.V)+table('S = QKᵀ / √2',model.scores)+table('L = S / τ + M',model.logits)+table('A = softmax(L)',model.A)+table('O = AV',model.O)+table('Concat(O1,O2,O3)',mix.concat)+table('WO (9×3)',mix.WO)+table('X + Concat(O) WO',mix.residual)}
function setChapter(i){oldCam.copy(camera.position);oldTarget.copy(orbit.target);transition=chapter<0?1:0;chapter=i;captionIndex=-1;const c=chapters[i];$('#scene-no').textContent='CHAPTER 0'+(i+1)+' / 06';$('#scene-title').textContent=c.title;$('#idea').textContent=c.idea;$('#explain').textContent=c.text;$('#formula').innerHTML=c.formula;$('#chapters').querySelectorAll('button').forEach((b,j)=>{b.classList.toggle('active',i===j);b.setAttribute('aria-current',i===j?'step':'false')});dirty=true}
function playSync(){$('#play').innerHTML=state.playing?'Ⅱ <span>一時停止</span>':'▶ <span>再生</span>';$('#play').setAttribute('aria-label',state.playing?'一時停止':'再生')}
function seek(t){state.time=Math.max(0,Math.min(150,t));state.playing=false;state.orbit=false;orbit.enabled=false;$('#orbit').setAttribute('aria-pressed','false');playSync();if(chapter!==Math.min(5,Math.floor(state.time/25)))setChapter(Math.min(5,Math.floor(state.time/25)));renderFrame(0)}
$('#chapters').innerHTML=chapters.map((c,i)=>'<button><small>0'+(i+1)+'</small>'+c.name+'</button>').join('');$('#chapters').querySelectorAll('button').forEach((b,i)=>b.onclick=()=>seek(i*25));$('#tokens').innerHTML=words.map(w=>'<button>'+w+'</button>').join('');$('#tokens').querySelectorAll('button').forEach((b,i)=>b.onclick=()=>{state.query=i;updateModel()});
$('#temperature').oninput=e=>{state.temp=+e.target.value;updateModel()};$('#gain').oninput=e=>{state.gain=+e.target.value;updateModel()};$('#mask').onchange=e=>{state.mask=e.target.checked;updateModel()};$('#head').onchange=e=>{state.head=+e.target.value;updateModel()};$('#speed').onchange=e=>state.speed=+e.target.value;
$('#play').onclick=()=>{if(state.time>=150)state.time=0;state.playing=!state.playing;playSync()};$('#timeline').oninput=e=>seek(+e.target.value);$('#next').onclick=()=>seek(Math.min(149.9,(chapter+1)*25));$('#back').onclick=()=>seek(Math.max(0,(chapter-1)*25));$('#reset').onclick=()=>{Object.assign(state,{query:3,head:0,mask:true,temp:1,gain:1});$('#temperature').value=1;$('#gain').value=1;$('#mask').checked=true;$('#head').value=0;updateModel()};$('#orbit').onclick=()=>{state.orbit=!state.orbit;orbit.enabled=state.orbit;if(state.orbit){state.playing=false;playSync()}$('#orbit').setAttribute('aria-pressed',String(state.orbit));renderer.domElement.style.touchAction=state.orbit?'none':'pan-y'};$('#home').onclick=()=>{state.orbit=false;orbit.enabled=false;transition=1;$('#orbit').setAttribute('aria-pressed','false');renderFrame(0)};
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON','A'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();$('#play').click()}if(e.code==='ArrowRight'){e.preventDefault();seek(state.time+5)}if(e.code==='ArrowLeft'){e.preventDefault();seek(state.time-5)}});
let pointer;renderer.domElement.addEventListener('pointerdown',e=>pointer=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!pointer||Math.hypot(e.clientX-pointer[0],e.clientY-pointer[1])>5)return;const r=renderer.domElement.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2),camera);const hit=ray.intersectObjects(pickables,false)[0];if(hit){state.query=hit.object.userData.query;updateModel()}});
function layoutLabels(){const r=$('#stage').getBoundingClientRect();root.updateMatrixWorld(true);for(const {anchor,el} of labels){let visible=true,o=anchor;while(o){if(!o.visible)visible=false;o=o.parent}const p=anchor.getWorldPosition(new T.Vector3()).project(camera),x=(p.x+1)*r.width/2,y=(1-p.y)*r.height/2;el.style.display=visible&&p.z<1&&x>8&&x<r.width-8&&y>100&&y<r.height-110?'block':'none';el.style.left=x+'px';el.style.top=y+'px'}}
function renderFrame(dt){const idx=Math.min(5,Math.floor(state.time/25));if(idx!==chapter)setChapter(idx);if(dirty){clear();builders[chapter]();dirty=false}const p=Math.min(1,(state.time-chapter*25)/25),r=$('#stage').getBoundingClientRect();if(renderer.domElement.width!==Math.floor(r.width*renderer.getPixelRatio())||renderer.domElement.height!==Math.floor(r.height*renderer.getPixelRatio()))renderer.setSize(r.width,r.height,false);camera.zoom=r.width<600?1:[1.25,1.14,1.12,1,1.04,1.1][chapter];camera.aspect=r.width/r.height;camera.updateProjectionMatrix();const c=chapters[chapter];if(!state.orbit){const target=V(c.target),pos=V(lerp(c.cam[0],c.cam[1],ease(p)));if(r.width<600){const f=chapter===1?1.44:chapter===5?1.35:1.32;pos.sub(target).multiplyScalar(f).add(target)}transition=Math.min(1,transition+dt*1.4);camera.position.copy(oldCam).lerp(pos,ease(transition));orbit.target.copy(oldTarget).lerp(target,ease(transition));camera.lookAt(orbit.target)}else orbit.update();anim.forEach(f=>f(p));renderer.render(scene,camera);layoutLabels();const ci=Math.min(2,Math.floor(p*3));if(ci!==captionIndex){captionIndex=ci;$('#caption').textContent=c.cues[ci];$('#caption-num').textContent='0'+(chapter+1)+' / 0'+(ci+1)}$('#timeline').value=state.time;$('#clock').textContent=Math.floor(state.time/60)+':'+String(Math.floor(state.time%60)).padStart(2,'0')+' / 2:30';frames++}
function tick(now){const dt=Math.min(.1,(now-last)/1000||0);last=now;if(state.playing&&!document.hidden){state.time=Math.min(150,state.time+dt*state.speed);if(state.time===150){state.playing=false;playSync()}}renderFrame(dt);requestAnimationFrame(tick)}
window.cinema={get state(){return {...state,chapter,frames,camera:camera.position.toArray(),drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,webgl:!renderer.getContext().isContextLost()}},trace:()=>trace(state),multi:()=>multi(state),seek,chapters:chapters.map(c=>c.name),get labels(){return labels.map(l=>({text:l.el.textContent,visible:l.el.style.display!=='none',rect:l.el.getBoundingClientRect().toJSON()}))}};
setChapter(0);updateReadout();playSync();requestAnimationFrame(tick);
