import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {words,X,WQ,WK,WV,trace,multi} from './math.js';
const $=s=>document.querySelector(s),C={q:'#ffcc72',k:'#6ddbd5',v:'#ba9af7',a:'#ff8d8d',white:'#e7effa',muted:'#7990a8'};
const chapters=[{"name": "文脈とは移動", "title": "creature に、性質が加わる。", "idea": "数字の更新を、空間の移動として見る。", "text": "fluffy＝ふわふわ、blue＝青い。3B1Bの修飾語→名詞の例を4語に縮約。ここでは3軸に意味を割り当てた手設計の模型です。実際の埋め込みの軸を測ったものではなく、位置埋め込みも省略しています。", "formula": "e′ = e + Δe", "cues": ["a fluffy blue creature。「生き物」という一般的な表現を、「ふわふわで青い生き物」へ動かしたい。", "3成分は、ふわふわ・青さ・生き物の模型上の座標。Attentionは色の名前を付けるだけでなく、数値を加えて表現を変える。", "灰色の元ベクトルから赤い更新後へ。次の章から、この移動 Δe がどの計算で決まるかを分解する。"], "cam": [[8, 5, 14], [3, 3.2, 14]], "target": [0, 0.4, 0]}, {"name": "質問と手がかり", "title": "名詞の質問に、形容詞が応える。", "idea": "同じ入力を、違う行列で写す。", "text": "Head 1では creature のQueryが[2,2]。fluffyのKeyは[2,0]、blueは[0,2]になり、両方と内積4で一致します。これは期待する挙動を説明するための設定で、学習済みheadの解釈ではありません。", "formula": "qᵢ = eᵢWQ　kᵢ = eᵢWK　vᵢ = eᵢWV", "cues": ["読む側を creature にすると、入力[0,0,1]が行列を通り、Query[2,2]へ変換される。", "行列の各列と入力の内積が、出力の1成分になる。画面下の式は選択したトークンとHeadで再計算する。", "Valueは3成分から2成分へ圧縮。あとで Wup を掛け、元の3次元空間へ戻す。QとKは運ぶ内容ではない。"], "cam": [[8, 4, 17], [1.5, 1.6, 16]], "target": [0, 0.1, 0]}, {"name": "内積を分解", "title": "2つの積を足すと、相性になる。", "idea": "fluffy と blue は、違う方向から一致する。", "text": "黄色が選択Query。水色のKeyを同じ原点で比較します。Head 1のcreatureは両形容詞と一致します。Head 2/3は片方を重く読む別の手設計例。矢印の長さも内積に影響します。", "formula": "sᵢⱼ = (qᵢ₁kⱼ₁ + qᵢ₂kⱼ₂) / √2", "cues": ["内積は「向き」だけでは決まらない。各成分を掛けて足すので、長さも効く。", "creatureとfluffyなら 2×2 + 2×0 = 4。blueなら 2×0 + 2×2 = 4。同じスコアでも寄与する成分は違う。", "√2で割った値はまだ確率ではない。次に未来を隠し、指数化と正規化で読む割合をつくる。"], "cam": [[5, 7, 17], [0.2, 1.5, 17]], "target": [1, 1, 0]}, {"name": "スコア → 割合", "title": "負のスコアも、読む割合へ。", "idea": "スコア → マスク → exp → 行の合計で割る。", "text": "3B1Bは読む側を列に配置しますが、本教材は行に配置します。同じ計算の転置表示です。温度はAttention分布を実験する追加操作で、生成時の温度とは別です。未来マスクはsoftmaxより前に適用します。", "formula": "Aᵢⱼ = exp(Lᵢⱼ) / Σₖ exp(Lᵢₖ)　L = S/τ + M", "cues": ["最初は符号付きスコア。黄色の行は選択したQueryで、どのKeyから読むかを並べたもの。", "未来の場所を −∞ に置き換える。指数にすると0になるので、分母からも除外される。", "最後は重み。各行の合計は1。Head 1のcreatureでは fluffy と blue が大きな割合を受け取る。"], "cam": [[9, 10, 12], [3, 11, 12]], "target": [0, 0.8, 0]}, {"name": "文脈を足す", "title": "生き物 → ふわふわで青い生き物。", "idea": "重み付きValueを、元の表現に足す。", "text": "ValueをWupで3成分へ戻し、重みを掛けて先端からつなぎます。白が元のe、色付きが各寄与、赤がe′。fluffy倍率0なら「ふわふわ」の寄与だけ消えます。Aは不変。ここでは選択した単一headの更新です。", "formula": "Δeᵢ = (Σⱼ Aᵢⱼvⱼ) Wup　e′ᵢ = eᵢ + Δeᵢ", "cues": ["まず白い元ベクトル。creatureなら[0,0,1]で、模型上は青さもふわふわもまだ0。", "色付きの矢印は A×Value×Wup。順につなぐと、元の表現の先端から文脈の方向へ移動する。", "赤い矢印が更新後。fluffy倍率を0・1・負の値で比較しよう。読む割合が同じでも、運ぶ情報が違えば到着点が変わる。"], "cam": [[7, 6, 13], [3, 3, 12]], "target": [0.4, 0.5, 0]}, {"name": "圧縮と複数Head", "title": "小さく計算し、元の空間へ戻す。", "idea": "3→2→3。各Headの更新を足し合わせる。", "text": "各Headは3×2のWVで圧縮し、2×3のWupで復元。この合成の階数は高々2。3本のWupを縦に積んだ6×3行列がWOです。Concat(O)WOと、各HeadのOWupの和は一致します。Norm・MLP・次トークン予測は本版では計算しません。", "formula": "Σₕ OₕWup,ₕ = Concat(O₁,O₂,O₃) WO", "cues": ["上段で3成分のeを2成分のvへ写し、Wupで3成分へ戻す。これは完全復元ではなく、渡したい更新をつくる写像。", "各Headは異なるQとValueを使う。3つの注意行列から、別々の更新案が計算される。", "それらの和を元のeへ足す。実際のTransformerは、この先のMLPやNormも繰り返す。この6章はAttentionの内部に焦点を当てたもの。"], "cam": [[10, 7, 18], [5, 4, 17]], "target": [0, 0, -1]}];
const state={time:0,playing:!matchMedia('(prefers-reduced-motion: reduce)').matches,query:3,head:0,mask:true,temp:1,gain:1,speed:1,orbit:false};
let model=trace(state),mix=multi(state),chapter=-1,root,labels=[],anim=[],pickables=[],frames=0,last=0,dirty=true,captionIndex=-1;
let renderer;try{renderer=new T.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=T.SRGBColorSpace;$('#stage').prepend(renderer.domElement);}catch(e){$('#fallback').hidden=false;throw e}
const scene=new T.Scene();scene.fog=new T.FogExp2('#080d15',.014);scene.add(new T.AmbientLight('#b5d9ff',1.5));const light=new T.DirectionalLight('#d7eaff',3);light.position.set(3,8,7);scene.add(light);const rim=new T.PointLight(C.k,45,30);rim.position.set(-5,4,-5);scene.add(rim);
const camera=new T.PerspectiveCamera(39,1,.1,150),orbit=new OrbitControls(camera,renderer.domElement);orbit.enabled=false;orbit.enableDamping=true;orbit.minDistance=7;orbit.maxDistance=32;orbit.enablePan=false;
const V=a=>new T.Vector3(...a),lerp=(a,b,t)=>a.map((v,i)=>v+(b[i]-v)*t),ease=t=>{t=Math.max(0,Math.min(1,t));return t*t*(3-2*t)},range=(p,a,b)=>ease((p-a)/(b-a));
const oldCam=new T.Vector3(),oldTarget=new T.Vector3();let transition=1;
function clear(){if(root){root.traverse(o=>{o.geometry?.dispose();if(o.material)for(const m of [o.material].flat()){m.map?.dispose();m.dispose()}});scene.remove(root)}root=new T.Group();scene.add(root);labels=[];anim=[];pickables=[];$('#labels').replaceChildren()}
function label(text,pos,color=C.white,parent=root,major=false){const anchor=new T.Object3D();anchor.position.copy(V(pos));parent.add(anchor);const el=document.createElement('span');el.className='label'+(major?' major':'');el.style.color=color;el.textContent=text;$('#labels').append(el);labels.push({anchor,el});return anchor}
function matrixLabel(text,pos,color,parent){label(text,pos,color,parent);labels[labels.length-1].el.classList.add('matrix-entry')}
function line(a,b,color=C.muted,opacity=.5,parent=root){const m=new T.Line(new T.BufferGeometry().setFromPoints([V(a),V(b)]),new T.LineBasicMaterial({color,transparent:true,opacity}));parent.add(m);return m}
function box(pos,size,color,opacity=.7,parent=root){const m=new T.Mesh(new T.BoxGeometry(...size),new T.MeshStandardMaterial({color,transparent:true,opacity,roughness:.45,metalness:.25}));m.position.copy(V(pos));parent.add(m);return m}
function arrow(a,b,color,parent=root,width=.035){const g=new T.Group();g.position.copy(V(a));parent.add(g);const d=V(b).sub(V(a)),len=d.length();if(len<1e-6)return g;const m=new T.MeshBasicMaterial({color});const shaft=new T.Mesh(new T.CylinderGeometry(width,width,Math.max(.001,len-.17),10),m);shaft.position.y=Math.max(.001,len-.17)/2;const tip=new T.Mesh(new T.ConeGeometry(width*3,.19,14),m);tip.position.y=len-.095;g.add(shaft,tip);g.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d.normalize());return g}
function panel(pos,size,color,parent=root,opacity=.08){const m=box(pos,[...size,.035],color,opacity,parent);const edge=new T.LineSegments(new T.EdgesGeometry(m.geometry),new T.LineBasicMaterial({color,transparent:true,opacity:.4}));m.add(edge);return m}
function path(a,b,color,parent=root,bend=1){const mid=V(a).lerp(V(b),.5);mid.y+=bend;const curve=new T.QuadraticBezierCurve3(V(a),mid,V(b));const l=new T.Line(new T.BufferGeometry().setFromPoints(curve.getPoints(40)),new T.LineBasicMaterial({color,transparent:true,opacity:.4}));parent.add(l);const bead=new T.Mesh(new T.SphereGeometry(.055,10,8),new T.MeshBasicMaterial({color}));parent.add(bead);anim.push((p)=>bead.position.copy(curve.getPoint((p*2)%1)));return l}
function grid(y=-2.15,size=14){const g=new T.GridHelper(size,28,'#29414f','#1b2b38');g.position.y=y;g.material.transparent=true;g.material.opacity=.33;root.add(g)}
function vector(values,pos,color,parent=root,scale=1){const g=new T.Group();g.position.copy(V(pos));g.scale.setScalar(scale);parent.add(g);const h=values.length*.5;panel([0,0,0],[.95,h+.25],color,g,.09);values.forEach((v,i)=>{const y=(values.length-1)*.25-i*.5;box([0,y,.05],[.66,.35,.08],v<0?C.a:color,.18+Math.min(Math.abs(v)*.35,.6),g);label(v.toFixed(2),[0,y,.13],color,g)});return g}
function heatmap(a,parent,pos,size=3,color=C.k){const g=new T.Group();g.position.copy(V(pos));parent.add(g);const cell=size/4;for(let i=0;i<4;i++)for(let j=0;j<4;j++){const w=a[i][j];box([(j-1.5)*cell,(1.5-i)*cell,0],[cell*.87,cell*.87,.055],w?color:'#354052',w?.15+.85*w:.09,g)}return g}
function inputScene(){grid(-1.5);const base=X[3],end=model.residual[3],origin=[-1,-.6,-1],scale=2.6;const point=v=>v.map((x,i)=>origin[i]+x*scale);const axes=[['fluffy',[1,0,0],C.v],['blue',[0,1,0],C.k],['creature',[0,0,1],C.white]];axes.forEach(([name,d,col])=>{arrow(origin,point(d.map(x=>x*1.05)),col,root,.014);if(name!=='creature')label(name,point(d.map(x=>x*1.14)),col)});arrow(origin,point(base),C.white);label('e : creature',point(base).map((v,i)=>v+(i===0?-.7:0)),C.white);const mover=new T.Mesh(new T.SphereGeometry(.13,18,12),new T.MeshBasicMaterial({color:C.a}));root.add(mover);const trail=line(point(base),point(end),C.a,.8);const updated=arrow(origin,point(end),C.a,root,.025);label('e′ : ['+end.map(v=>v.toFixed(2)).join(', ')+']',[.3,2.0,2],C.a,root,true);anim.push(p=>{const t=range(p,.2,.9);mover.position.copy(V(point(lerp(base,end,t))));updated.visible=p>.8;trail.visible=p>.2});label('a   fluffy   blue   creature',[0,-2.3,0],C.white,root,true);}
function projectionScene(){grid(-2.5);vector(X[state.query],[-4,0,0],C.white);label('x : '+words[state.query],[-3,1.2,0],C.white,root,true);const specs=[['Q',C.q,WQ[state.head],model.Q[state.query],2],['K',C.k,WK[state.head],model.K[state.query],0],['V',C.v,WV[state.head],model.V[state.query],-2]];specs.forEach(([name,color,W,out,y],n)=>{const group=new T.Group();root.add(group);group.position.y=y;path([-3.4,-y,0],[-.9,0,0],color,group,.3);const cols=W[0].length;panel([0,0,0],[2,1.4],color,group);W.forEach((r,i)=>r.forEach((val,j)=>matrixLabel(val.toFixed(1),[(j-(cols-1)/2)*.72,(1-i)*.36,.06],color,group)));label('W'+name,[0,.96,.04],color,group);arrow([1.15,0,0],[2.4,0,0],color,group,.022);const v=vector(out,[3.15,0,0],color,group,.8);label(name,[3.15,1,0],color,group,true);anim.push(p=>{const a=range(p,n*.16,.35+n*.2);group.scale.setScalar(.7+.3*a);v.scale.setScalar(.4+.4*a)})});}
function dotScene(){grid(-2);for(let i=-3;i<=3;i++){line([i,-2,0],[i,3,0],C.muted,.17);line([-3,i,0],[3,i,0],C.muted,.17)}arrow([-3,0,0],[3,0,0],C.muted,root,.013);arrow([0,-2,0],[0,3,0],C.muted,root,.013);label('成分 1',[3.1,-.25,0],C.muted);label('成分 2',[-.4,3,0],C.muted);model.K.forEach((k,j)=>{const end=[k[0]*1.3,k[1]*1.3,0];const a=arrow([0,0,0],end,C.k,root,.022);label('k '+words[j],[end[0]+(j%2?.35:-.3),end[1]+.22,.04],C.k);anim.push(p=>a.scale.setScalar(.05+.95*range(p,.05+j*.07,.3+j*.09)))});const q=model.Q[state.query],end=[q[0]*1.3,q[1]*1.3,.03];const a=arrow([0,0,.03],end,C.q,root,.046);label('q '+words[state.query],[end[0]+.18,end[1]+.5,.1],C.q,root,true);anim.push(p=>a.scale.setScalar(.4+.6*range(p,0,.35)));const j=1,k=model.K[j],proj=k.map(v=>v*(q[0]*k[0]+q[1]*k[1])/(k[0]*k[0]+k[1]*k[1]));line(end,[proj[0]*1.3,proj[1]*1.3,0],C.q,.5);label('q · k_fluffy = '+(q[0]*k[0]+q[1]*k[1]).toFixed(3),[0,-1.7,.1],C.white);}
function matrixScene(){grid(-.06,12);const step=1.35;for(let i=0;i<4;i++){label(words[i],[-3.65,.05,(i-1.5)*step],i===state.query?C.q:C.muted);label(words[i],[(i-1.5)*step,.05,3.05],C.k);for(let j=0;j<4;j++){const w=model.A[i][j],score=model.scores[i][j],logit=model.logits[i][j],x=(j-1.5)*step,z=(i-1.5)*step;box([x,-.02,z],[1.22,.04,1.22],i===state.query?C.q:C.k,.1);const b=box([x,.1,z],[.75,1,.75],i===state.query?C.q:C.k,.8);b.userData.query=i;pickables.push(b);const anchor=label('',[x,.7,z],i===state.query?C.q:C.muted),el=labels.at(-1).el;anim.push(p=>{const phase=Math.min(3,Math.floor(p*4));let val=phase===0?score:phase===1?logit:phase===2?(Number.isFinite(logit)?Math.exp(logit):0):w;let h=phase<2?Math.max(-1.4,Math.min(2,val*.6)):phase===2?Math.log1p(val)*.55:w*2.7;if(!Number.isFinite(h))h=0;b.scale.y=Math.max(.015,Math.abs(h));b.position.y=h/2;b.material.opacity=Number.isFinite(val)&&val!==0?.85:.12;anchor.position.y=Math.max(.2,h)+.3;el.textContent=phase===3?w.toFixed(2):Number.isFinite(val)?val.toFixed(1):'−∞';})}}const lab=label('',[0,2.8,-2.6],C.white,root,true),el=labels.at(-1).el;anim.push(p=>el.textContent=['1 / 符号付きスコア S','2 / 温度 + 未来マスク L','3 / exp(L) — 高さはlog表示','4 / 正規化 A — 高さは重み'][Math.min(3,Math.floor(p*4))]);label('KEY → 情報源',[0,0,4],C.k);label('QUERY',[-3.8,.1,-3.1],C.q);}
function valueScene(){grid(-1.6,12);const colors=[C.muted,C.v,C.k,C.q],factor=3.4,origin=[-1.5,-.7,-1.4],base=X[state.query].map((v,i)=>origin[i]+v*factor);arrow(origin,base,C.white,root,.038);label('e : '+words[state.query],[-2.7,.2,1.5],C.white);let cur=[...base];model.A[state.query].forEach((w,j)=>{const part=model.lifted[j].map(v=>v*w*factor),start=[...cur],end=start.map((v,k)=>v+part[k]),g=arrow([0,0,0],part,colors[j],root,.04);const separate=[(j-1.5)*1.5,-.8,-1];g.position.copy(V(separate));label(w.toFixed(2)+' × '+words[j],[(j%2===0?-1.5:1.5),j<2?2.55:1.85,0],colors[j]);anim.push(p=>{g.position.copy(V(lerp(separate,start,range(p,.12+j*.09,.38+j*.1))));g.visible=w>0;g.scale.setScalar(range(p,.03,.2))});cur=end});const result=arrow(origin,cur,C.a,root,.03);const endDot=new T.Mesh(new T.SphereGeometry(.11,16,12),new T.MeshBasicMaterial({color:C.a}));root.add(endDot);const caption=label('e′ = ['+model.residual[state.query].map(v=>v.toFixed(2)).join(', ')+']',[0,3.5,0],C.a,root,true);anim.push(p=>{result.visible=p>.72;caption.visible=p>.72;endDot.position.copy(V(lerp(base,cur,range(p,.2,.85))))});label('白 e  +  色付き Δe  =  赤 e′',[0,-1.8,.3],C.white);}
function finalScene(){grid(-3.5,18);const i=state.query,h=state.head;vector(X[1],[-4,2,0],C.white,root,.7);vector(model.V[1],[0,2,0],C.v,root,.7);vector(model.lifted[1],[4,2,0],C.a,root,.7);arrow([-3.3,2,0],[-.8,2,0],C.v);arrow([.8,2,0],[3.3,2,0],C.a);label('WV : 3 → 2',[-2,3,0],C.v);label('Wup : 2 → 3',[2,3,0],C.a);label('e_fluffy',[-4,3.2,0],C.white);label('v',[0,3.2,0],C.v);label('v Wup',[4,3.2,0],C.a);const colors=[C.k,C.v,C.a];mix.heads.forEach((head,j)=>{const g=new T.Group();g.position.set((j-1)*3,-.4,0);root.add(g);heatmap(head.A,g,[0,0,0],1.6,colors[j]);label('HEAD '+(j+1),[0,1,0],colors[j],g);path([0,-1,0],[-g.position.x,-2,-2],colors[j],g,-.2);anim.push(p=>g.visible=p>.2+j*.1)});label('Σ head Δe = ['+mix.delta[i].map(v=>v.toFixed(2)).join(', ')+']',[0,-2,-1],C.white);label('e′ = ['+mix.residual[i].map(v=>v.toFixed(2)).join(', ')+']',[0,-2.8,-1],C.a,root,true);}

const builders=[inputScene,projectionScene,dotScene,matrixScene,valueScene,finalScene];
function updateModel(){model=trace(state);mix=multi(state);dirty=true;updateReadout()}
function updateReadout(){const row=model.A[state.query];$('#readout').innerHTML='<div style="color:#93a3b8">'+words[state.query]+' が読む割合 / Head '+(state.head+1)+'</div>'+row.map((v,i)=>'<div class="barrow"><span>'+words[i]+'</span><div class="bar"><i style="width:'+v*100+'%"></i></div><span>'+ (v*100).toFixed(1)+'%</span></div>').join('')+'<div style="margin-top:5px">Σ = '+row.reduce((a,b)=>a+b,0).toFixed(6)+'<br>o = ['+model.O[state.query].map(x=>x.toFixed(3)).join(', ')+']</div>';updateMatrixData();$('#temp-out').value=state.temp.toFixed(2);$('#gain-out').value=state.gain.toFixed(2);$('#tokens').querySelectorAll('button').forEach((b,i)=>{b.classList.toggle('active',i===state.query);b.setAttribute('aria-pressed',String(i===state.query))})}
function updateMatrixData(){const table=(name,m)=>'<h4>'+name+'</h4><table>'+m.map(r=>'<tr>'+r.map(v=>'<td>'+(Number.isFinite(v)?v.toFixed(3):'−∞')+'</td>').join('')+'</tr>').join('')+'</table>';$('#matrix-data').innerHTML=table('X (4×3)',X)+table('WQ (3×2)',WQ[state.head])+table('WK (3×2)',WK[state.head])+table('WV down (3×2)',WV[state.head])+table('Wup (2×3)',model.UP)+table('Q = XWQ',model.Q)+table('K = XWK',model.K)+table('V（倍率介入後）',model.V)+table('S = QKᵀ / √2',model.scores)+table('L = S / τ + M',model.logits)+table('A = softmax(L)',model.A)+table('O = AV (4×2)',model.O)+table('Value × Wup (4×3)',model.lifted)+table('選択Head Δe',model.delta)+table('選択Head e + Δe',model.residual)+table('Concat(O1,O2,O3)',mix.concat)+table('WO (6×3)',mix.WO)+table('X + Concat(O) WO',mix.residual)}
function setChapter(i){oldCam.copy(camera.position);oldTarget.copy(orbit.target);transition=chapter<0?1:0;chapter=i;captionIndex=-1;const c=chapters[i];$('#scene-no').textContent='CHAPTER 0'+(i+1)+' / 06';$('#scene-title').textContent=c.title;$('#idea').textContent=c.idea;$('#explain').textContent=c.text;$('#formula').innerHTML=c.formula;$('#chapters').querySelectorAll('button').forEach((b,j)=>{b.classList.toggle('active',i===j);b.setAttribute('aria-current',i===j?'step':'false')});dirty=true}
function playSync(){$('#play').innerHTML=state.playing?'Ⅱ <span>一時停止</span>':'▶ <span>再生</span>';$('#play').setAttribute('aria-label',state.playing?'一時停止':'再生')}
function seek(t){state.time=Math.max(0,Math.min(150,t));state.playing=false;state.orbit=false;orbit.enabled=false;$('#orbit').setAttribute('aria-pressed','false');playSync();if(chapter!==Math.min(5,Math.floor(state.time/25)))setChapter(Math.min(5,Math.floor(state.time/25)));renderFrame(0)}
$('#chapters').innerHTML=chapters.map((c,i)=>'<button><small>0'+(i+1)+'</small>'+c.name+'</button>').join('');$('#chapters').querySelectorAll('button').forEach((b,i)=>b.onclick=()=>seek(i*25));$('#tokens').innerHTML=words.map(w=>'<button>'+w+'</button>').join('');$('#tokens').querySelectorAll('button').forEach((b,i)=>b.onclick=()=>{state.query=i;updateModel()});
$('#temperature').oninput=e=>{state.temp=+e.target.value;updateModel()};$('#gain').oninput=e=>{state.gain=+e.target.value;updateModel()};$('#mask').onchange=e=>{state.mask=e.target.checked;updateModel()};$('#head').onchange=e=>{state.head=+e.target.value;updateModel()};$('#speed').onchange=e=>state.speed=+e.target.value;
$('#play').onclick=()=>{if(state.time>=150)state.time=0;state.playing=!state.playing;playSync()};$('#timeline').oninput=e=>seek(+e.target.value);$('#next').onclick=()=>seek(Math.min(149.9,(chapter+1)*25));$('#back').onclick=()=>seek(Math.max(0,(chapter-1)*25));$('#reset').onclick=()=>{Object.assign(state,{query:3,head:0,mask:true,temp:1,gain:1});$('#temperature').value=1;$('#gain').value=1;$('#mask').checked=true;$('#head').value=0;updateModel()};$('#orbit').onclick=()=>{state.orbit=!state.orbit;orbit.enabled=state.orbit;if(state.orbit){state.playing=false;playSync()}$('#orbit').setAttribute('aria-pressed',String(state.orbit));renderer.domElement.style.touchAction=state.orbit?'none':'pan-y'};$('#home').onclick=()=>{state.orbit=false;orbit.enabled=false;transition=1;$('#orbit').setAttribute('aria-pressed','false');renderFrame(0)};
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON','A'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();$('#play').click()}if(e.code==='ArrowRight'){e.preventDefault();seek(state.time+5)}if(e.code==='ArrowLeft'){e.preventDefault();seek(state.time-5)}});
let pointer;renderer.domElement.addEventListener('pointerdown',e=>pointer=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!pointer||Math.hypot(e.clientX-pointer[0],e.clientY-pointer[1])>5)return;const r=renderer.domElement.getBoundingClientRect(),ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2),camera);const hit=ray.intersectObjects(pickables,false)[0];if(hit){state.query=hit.object.userData.query;updateModel()}});
function layoutLabels(){const r=$('#stage').getBoundingClientRect();root.updateMatrixWorld(true);for(const {anchor,el} of labels){let visible=true,o=anchor;while(o){if(!o.visible)visible=false;o=o.parent}const p=anchor.getWorldPosition(new T.Vector3()).project(camera),x=(p.x+1)*r.width/2,y=(1-p.y)*r.height/2;el.style.display=visible&&p.z<1&&x>8&&x<r.width-8&&y>100&&y<r.height-110?'block':'none';el.style.left=x+'px';el.style.top=y+'px'}}
function renderFrame(dt){const idx=Math.min(5,Math.floor(state.time/25));if(idx!==chapter)setChapter(idx);if(dirty){clear();builders[chapter]();dirty=false}const p=Math.min(1,(state.time-chapter*25)/25),r=$('#stage').getBoundingClientRect();if(renderer.domElement.width!==Math.floor(r.width*renderer.getPixelRatio())||renderer.domElement.height!==Math.floor(r.height*renderer.getPixelRatio()))renderer.setSize(r.width,r.height,false);camera.zoom=r.width<600?1:[1.25,1.14,1.12,1,1.04,1.1][chapter];camera.aspect=r.width/r.height;camera.updateProjectionMatrix();const c=chapters[chapter];if(!state.orbit){const target=V(c.target),pos=V(lerp(c.cam[0],c.cam[1],ease(p)));if(r.width<600){const f=chapter===1?1.44:chapter===5?1.35:1.32;pos.sub(target).multiplyScalar(f).add(target)}transition=Math.min(1,transition+dt*1.4);camera.position.copy(oldCam).lerp(pos,ease(transition));orbit.target.copy(oldTarget).lerp(target,ease(transition));camera.lookAt(orbit.target)}else orbit.update();anim.forEach(f=>f(p));renderer.render(scene,camera);layoutLabels();if(chapter===1){const e=X[state.query],w=WQ[state.head];$('#formula').textContent='q₁ = '+e.map((v,i)=>v.toFixed(1)+'×'+w[i][0].toFixed(1)).join(' + ')+' = '+model.Q[state.query][0].toFixed(2)}const ci=Math.min(2,Math.floor(p*3));if(ci!==captionIndex){captionIndex=ci;$('#caption').textContent=c.cues[ci];$('#caption-num').textContent='0'+(chapter+1)+' / 0'+(ci+1)}$('#timeline').value=state.time;$('#clock').textContent=Math.floor(state.time/60)+':'+String(Math.floor(state.time%60)).padStart(2,'0')+' / 2:30';frames++}
function tick(now){const dt=Math.min(.1,(now-last)/1000||0);last=now;if(state.playing&&!document.hidden){state.time=Math.min(150,state.time+dt*state.speed);if(state.time===150){state.playing=false;playSync()}}renderFrame(dt);requestAnimationFrame(tick)}
window.cinema={get state(){return {...state,chapter,frames,camera:camera.position.toArray(),drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,webgl:!renderer.getContext().isContextLost()}},trace:()=>trace(state),multi:()=>multi(state),seek,chapters:chapters.map(c=>c.name),get labels(){return labels.map(l=>({text:l.el.textContent,visible:l.el.style.display!=='none',rect:l.el.getBoundingClientRect().toJSON()}))}};
setChapter(0);updateReadout();playSync();requestAnimationFrame(tick);

function focusMode(on){document.body.classList.toggle('cinema-focus',on);$('#focus').setAttribute('aria-pressed',String(on));$('#focus').textContent=on?'操作パネルに戻る':'映像に集中';window.dispatchEvent(new Event('resize'))}
$('#focus').onclick=()=>focusMode(!document.body.classList.contains('cinema-focus'));
window.addEventListener('keydown',e=>{if(e.key==='Escape')focusMode(false)});
