import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {examples,vocab,params,forward,gradients,trainPair,trainCorpus,resetParams,setParams,getRef,setRef,gradRef,lossSlice,surfaceRefs,state,shape} from './model.js';
const $=s=>document.querySelector(s); let ex=examples[0],stage='predict',selected=null,checkpoint=null,lastGrad=null,history=[];
const select=$('#pairSelect');examples.forEach((e,i)=>select.add(new Option(`${e.context.join(" ")} → ${e.target}`,i)));
function fmt(x,n=3){return Number(x).toFixed(n)}
function vec(el,a){el.innerHTML=a.map((x,i)=>`<span title="dimension ${i}">${x>=0?'+':''}${fmt(x)}</span>`).join('')}
function render(){const f=forward(ex.context,ex.target);$('#stepCount').textContent=params.step;$('#sentence').innerHTML=ex.sentence.replace('___','<span class="blank">?</span>');$('#targetToken').textContent=ex.target;$('#contextToken').textContent=`mean(${ex.context.join(", ")})`;vec($('#embeddingVector'),f.e);vec($('#hiddenVector'),f.h);$('#targetProb').textContent=stage==='predict'?'hidden':`${(100*f.probs[f.y]).toFixed(1)}%`;$('#lossValue').textContent=['loss','gradient','update','again'].includes(stage)?fmt(f.loss):'hidden';const order=f.probs.map((p,i)=>({p,i})).sort((a,b)=>b.p-a.p);$('#probBars').innerHTML=order.map(({p,i})=>`<div class="bar-row ${i===f.y&&stage!=='predict'?'target':''}"><span class="token">${vocab[i]}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(1,p*100)}%"></div></div><code>${(p*100).toFixed(1)}%</code></div>`).join('');const top=order[0];$('#prediction').textContent=vocab[top.i];$('#predictionProb').textContent=`${(100*top.p).toFixed(1)}%`;$('#targetCard').classList.toggle('hidden',stage==='predict');const showGrad=['gradient','update'].includes(stage)&&selected&&lastGrad;$('#gradientCard').classList.toggle('hidden',!showGrad);if(showGrad){$('#gradientLabel').textContent=stage==='update'?'Gradient used for last update (before update)':'Current selected gradient';$('#gradientName').textContent=nameRef(selected);$('#gradientValue').textContent=fmt(gradRef(lastGrad,selected),5)}if(selected){const v=getRef(selected);$('#weightSlider').disabled=false;$('#weightNumber').disabled=false;$('#weightSlider').value=v;$('#weightNumber').value=fmt(v,5);$('#weightImpact').textContent=`Current value ${fmt(v,5)}. Drag it and watch the right-side distribution change.`}document.querySelectorAll('.flow button').forEach(b=>b.classList.toggle('active',b.dataset.stage===stage));render3d(f);if(!$('#surfacePanel').classList.contains('hidden'))drawSurface();}
select.onchange=()=>{ex=examples[+select.value];stage='predict';lastGrad=null;render();status('New example. The same weights make a new prediction.');};
const stageCopy={predict:'Forward pass: weights are fixed; the model predicts a distribution.',target:'The target comes from the training corpus, not from the model.',loss:'Cross-entropy is −log P(target). Higher target probability means lower loss.',gradient:'Backpropagation computes ∂loss/∂weight for every parameter.',update:'Gradient descent changes every weight by − learning rate × gradient.',again:'Run the same input again: changed weights produce changed probabilities.'};
document.querySelectorAll('.flow button').forEach(b=>b.onclick=()=>{stage=b.dataset.stage;if(stage==='gradient')lastGrad=gradients(ex.context,ex.target).g;if(stage==='update'){const r=trainPair(ex.context,ex.target,+$('#learningRate').value);lastGrad=r.g;history.push({step:params.step,loss:r.after.loss});}render();status(stageCopy[stage]);});
function status(s){$('#status').textContent=s}
$('#trainOne').onclick=()=>{const r=trainPair(ex.context,ex.target,+$('#learningRate').value);lastGrad=r.g;history.push({step:params.step,loss:r.after.loss});stage='again';render();status(`One real SGD step: loss ${fmt(r.before.loss)} → ${fmt(r.after.loss)}.`);};
$('#trainHundred').onclick=()=>{trainCorpus(100,+$('#learningRate').value);lastGrad=selected?gradients(ex.context,ex.target).g:null;stage='again';render();status('100 real corpus SGD steps completed. Try each sentence again.');};
$('#reset').onclick=()=>{resetParams();checkpoint=null;history=[];selected=null;lastGrad=null;stage='predict';$('#weightName').textContent='Click a connection';$('#weightSlider').disabled=true;$('#weightNumber').disabled=true;$('#weightSlider').value=0;$('#weightNumber').value='';render();status('Deterministic initial weights restored.');};
$('#checkpoint').onclick=()=>{checkpoint=state();status(`Checkpoint saved at step ${params.step}.`)};$('#restore').onclick=()=>{if(checkpoint){setParams(checkpoint);lastGrad=selected?gradients(ex.context,ex.target).g:null;render();status('Checkpoint restored.')}else status('Save a checkpoint first.')};
function nameRef(r){return `${r.group}[${r.idx.join(', ')}]`}
function selectWeight(r){selected=r;$('#weightName').textContent=nameRef(r);const v=getRef(r);for(const id of ['#weightSlider','#weightNumber']){$(id).disabled=false;$(id).value=v}$('#weightImpact').textContent=`Current value ${fmt(v,5)}. Drag it and watch the right-side distribution change.`;lastGrad=gradients(ex.context,ex.target).g;render();}
function changeWeight(v){if(!selected)return;setRef(selected,+v);lastGrad=gradients(ex.context,ex.target).g;$('#weightSlider').value=v;$('#weightNumber').value=v;render();}
$('#weightSlider').oninput=e=>changeWeight(e.target.value);$('#weightNumber').oninput=e=>changeWeight(e.target.value);

let scene,camera,renderer,controls,raycaster,mouse,edges=[],nodes=[];
function init3d(){const root=$('#model3d');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(42,root.clientWidth/root.clientHeight,.1,100);camera.position.set(0,2.3,10);renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(2,devicePixelRatio));renderer.setSize(root.clientWidth,root.clientHeight);root.appendChild(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=6;controls.maxDistance=15;raycaster=new THREE.Raycaster();raycaster.params.Line.threshold=.12;mouse=new THREE.Vector2();renderer.domElement.onclick=e=>{const r=renderer.domElement.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-(e.clientY-r.top)/r.height*2+1;raycaster.setFromCamera(mouse,camera);const hit=raycaster.intersectObjects([...nodes,...edges],false)[0];if(hit){if(hit.object.userData.kind==='edge')selectWeight(hit.object.userData.ref);else inspectNode(hit.object)}};addModel();function loop(){requestAnimationFrame(loop);controls.update();renderer.render(scene,camera)}loop();addEventListener('resize',()=>{camera.aspect=root.clientWidth/root.clientHeight;camera.updateProjectionMatrix();renderer.setSize(root.clientWidth,root.clientHeight)});}
const ypos=(n,i)=>(i-(n-1)/2)*1.15;
function node(x,y,color,label,layer,index){const g=new THREE.SphereGeometry(.22,24,18),m=new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.22,roughness:.4});const o=new THREE.Mesh(g,m);o.position.set(x,y,0);o.userData={label,kind:'node',layer,index};scene.add(o);nodes.push(o);return o}
function edge(a,b,ref){const pts=[a.position,b.position],g=new THREE.BufferGeometry().setFromPoints(pts),m=new THREE.LineBasicMaterial({color:0x55718a,transparent:true,opacity:.38});const l=new THREE.Line(g,m);l.userData={ref,kind:'edge'};scene.add(l);edges.push(l)}
function addModel(){scene.add(new THREE.AmbientLight(0xffffff,2));const dl=new THREE.DirectionalLight(0xffffff,3);dl.position.set(3,4,6);scene.add(dl);const E=Array.from({length:shape.D},(_,i)=>node(-3,ypos(shape.D,i),0x2dd4bf,`embedding ${i}`,'embedding',i));const H=Array.from({length:shape.H},(_,i)=>node(0,ypos(shape.H,i),0xffd166,`hidden ${i}`,'hidden',i));const V=Array.from({length:shape.V},(_,i)=>node(3,ypos(shape.V,i)*.38,0xff6b6b,vocab[i],'vocab',i));for(let i=0;i<shape.D;i++)for(let j=0;j<shape.H;j++)edge(E[i],H[j],{group:'W',idx:[i,j]});for(let j=0;j<shape.H;j++)for(let k=0;k<shape.V;k++)edge(H[j],V[k],{group:'O',idx:[j,k]});}
function inspectNode(o){const f=forward(ex.context,ex.target);let value,label;if(o.userData.layer==='embedding'){value=f.e[o.userData.index];label=`Embedding[${o.userData.index}]`}else if(o.userData.layer==='hidden'){value=f.h[o.userData.index];label=`Hidden activation[${o.userData.index}]`}else{value=f.probs[o.userData.index];label=`P(${vocab[o.userData.index]})`}selected=null;$('#weightName').textContent=label;$('#weightSlider').disabled=true;$('#weightNumber').disabled=true;$('#weightNumber').value=fmt(value,5);$('#weightImpact').textContent=`Current forward-pass value: ${fmt(value,6)}. Select a connection to edit a trainable weight.`;render();}
function render3d(f){if(!scene)return;nodes.forEach(n=>{let v=0;if(n.position.x< -1)v=f.e[+n.userData.label.split(' ').at(-1)];else if(n.position.x<1)v=f.h[+n.userData.label.split(' ').at(-1)];else v=f.probs[vocab.indexOf(n.userData.label)];n.scale.setScalar(.85+Math.min(1.5,Math.abs(v))*0.45)});edges.forEach(e=>{const v=getRef(e.userData.ref);e.material.color.set(v>=0?0x2dd4bf:0xff6b6b);e.material.opacity=.18+Math.min(.72,Math.abs(v)/2.5);if(selected&&nameRef(selected)===nameRef(e.userData.ref)){e.material.color.set(0xffd166);e.material.opacity=1}})}

let surfaceRenderer,surfaceScene,surfaceCamera,surfaceControls,surfaceMesh,point,surfaceRevision=0;
$('#toggleSurface').onclick=()=>{$('#surfacePanel').classList.toggle('hidden');if(!$('#surfacePanel').classList.contains('hidden')){initSurface();drawSurface()}};
function initSurface(){if(surfaceRenderer)return;const root=$('#lossSurface');surfaceScene=new THREE.Scene();surfaceCamera=new THREE.PerspectiveCamera(45,root.clientWidth/root.clientHeight,.1,100);surfaceCamera.position.set(5,4.5,6);surfaceRenderer=new THREE.WebGLRenderer({antialias:true});surfaceRenderer.setSize(root.clientWidth,root.clientHeight);surfaceRenderer.setPixelRatio(Math.min(2,devicePixelRatio));root.appendChild(surfaceRenderer.domElement);surfaceControls=new OrbitControls(surfaceCamera,surfaceRenderer.domElement);surfaceControls.enableDamping=true;surfaceScene.add(new THREE.AmbientLight(0xffffff,2));function loop(){requestAnimationFrame(loop);surfaceControls.update();surfaceRenderer.render(surfaceScene,surfaceCamera)}loop()}
function drawSurface(){if(!surfaceScene)return;$('#lossSurface').dataset.revision=String(++surfaceRevision);for(const o of [surfaceMesh,point])if(o)surfaceScene.remove(o);const {a,b}=surfaceRefs(selected);const data=lossSlice(ex.context,ex.target,a,b,1,27),n=data.length,pos=[],col=[],ind=[],zs=data.flat().map(p=>p.z),zmin=Math.min(...zs),zmax=Math.max(...zs);for(let i=0;i<n;i++)for(let j=0;j<n;j++){const p=data[i][j],z=(p.z-zmin)/(zmax-zmin+.0001);pos.push((i/(n-1)-.5)*6,z*2.6,(j/(n-1)-.5)*6);col.push(.1+z*.9,.75-z*.45,.8-z*.65)}for(let i=0;i<n-1;i++)for(let j=0;j<n-1;j++){const q=i*n+j;ind.push(q,q+n,q+1,q+1,q+n,q+n+1)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('color',new THREE.Float32BufferAttribute(col,3));g.setIndex(ind);g.computeVertexNormals();surfaceMesh=new THREE.Mesh(g,new THREE.MeshStandardMaterial({vertexColors:true,side:THREE.DoubleSide,roughness:.75}));surfaceScene.add(surfaceMesh);point=new THREE.Mesh(new THREE.SphereGeometry(.12,18,12),new THREE.MeshBasicMaterial({color:0xffd166}));point.position.set(0,(forward(ex.context,ex.target).loss-zmin)/(zmax-zmin+.0001)*2.6,0);surfaceScene.add(point);surfaceScene.add(new THREE.AmbientLight(0xffffff,2));$('#surfaceAxes').innerHTML=`<code>x: ${nameRef(a)}</code><code>z: ${nameRef(b)}</code><code>height: actual cross-entropy</code>`;}
init3d();render();
