const D=document, q=s=>D.querySelector(s);let mode=D.body.dataset.demo,state={};
const meta={
'observe-act':['Observe → Act','A delivery robot must reach the green charger. Predict: will feedback matter if a new obstacle appears?'],
'replanning':['Plan, Fail, Replan','A campus agent has four errands. Add a disruption, then compare a fixed plan with replanning.'],
'memory':['Memory Mixer','Which past facts should an assistant retrieve for today’s request? Tune the retrieval policy.'],
'context':['Context Packing','A limited context window forces choices. Decide what deserves space before asking for an answer.'],
'verification':['Trust, but Verify','A research agent drafts claims. Choose how much of its output to verify before publishing.'],
'coordination':['Coordination Cost','Assign agents to a launch task. Specialization helps, but every handoff consumes time.']};
function shell(controls){let [title,desc]=meta[mode];D.title=title+' · Agent Systems Lab';D.body.innerHTML=`<div class="top"><div class="brand">ATLS 4519 · Agent Systems Lab</div><a class="back" href="../">← All experiments</a></div><main><div class="kicker">Interactive concept demo</div><h1>${title}</h1><p class="lede">${desc}</p><div class="shell"><aside class="panel"><div class="controls">${controls}</div><p class="note">Transparent deterministic teaching simulation. The displayed state is an instructional system trace, not a model’s private chain of thought.</p></aside><section class="stage"><div id="viz" class="viz"></div></section></div></main>`}
const ctl=(label,id,min,max,val,step=1)=>`<div class="control"><label>${label}<b id="${id}v">${val}</b></label><input id="${id}" type="range" min="${min}" max="${max}" value="${val}" step="${step}"></div>`;
const buttons=(primary='Run simulation')=>`<div class="buttons"><button class="primary" id="run">${primary}</button><button id="reset">Reset</button></div>`;
function wire(ids,render){ids.forEach(id=>q('#'+id).oninput=e=>{q('#'+id+'v').textContent=e.target.value;render()});q('#reset').onclick=()=>init();}
function metrics(a){return `<div class="metrics">${a.map(x=>`<div class="metric"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('')}</div>`}
function grid(pos,block){let out='<div class="grid">';for(let i=0;i<24;i++){let c='cell',t='';if([8,14].includes(i)||i===block)c+=' wall';if(i===pos){c+=' agent';t='🤖'}if(i===23){c+=' goal';t='⚡'}out+=`<div class="${c}">${t}</div>`}return out+'</div>'}
function observe(){shell(`${ctl('Feedback frequency','feedback',0,3,1)}${ctl('World changes','changes',0,3,1)}${buttons()}`);state={step:0,pos:0,block:10};let render=()=>{let f=+q('#feedback').value,c=+q('#changes').value,success=f>0||c===0,pos=state.step?success?23:9:0;q('#viz').innerHTML=metrics([['observations',state.step?1+f*2:0],['actions',state.step?success?9:5:0],['goal',state.step?(success?'reached':'blocked'):'—']])+grid(pos,c?10:-1)+`<div class="track"><div class="node ${state.step?'done':'active'}">Observe<br><small>world state</small></div><div class="arrow"></div><div class="node ${state.step?'done':''}">Choose<br><small>next action</small></div><div class="arrow"></div><div class="node ${state.step?'done':''}">Act<br><small>update world</small></div></div><div class="prompt">${state.step?(success?'Feedback exposes the new obstacle, so the route changes.':'Without another observation, the agent keeps following stale state.'):'Change the controls, predict the outcome, then run.'}</div>`};q('#run').onclick=()=>{state.step=1;render()};wire(['feedback','changes'],render);render()}
function replanning(){shell(`${ctl('Disruptions','disrupt',0,3,1)}${ctl('Replanning cost','cost',0,5,2)}<div class="control"><label>Strategy</label><select id="strategy"><option value="adaptive">Replan after failure</option><option value="fixed">Keep original plan</option></select></div>${buttons('Execute plan')}`);state={ran:false};let render=()=>{let d=+q('#disrupt').value,c=+q('#cost').value,a=q('#strategy').value==='adaptive',done=state.ran?(a?Math.max(1,4-Math.floor(d/2)):Math.max(0,4-d)):0,time=state.ran?(8+d*3+(a&&d?c:0)):0;let tasks=['Print posters','Book room','Pick up cable','Email guests'];q('#viz').innerHTML=metrics([['tasks completed',done+'/4'],['elapsed minutes',time],['plan revisions',state.ran&&a?d:0]])+`<div class="track">${tasks.map((t,i)=>`<div class="node ${state.ran&&i<done?'done':state.ran&&i===done?'active':''}">${t}</div>${i<3?'<div class="arrow"></div>':''}`).join('')}</div><div class="log">${state.ran&&d?`<div class="event bad">Disruption: ${['printer offline','room locked','cable unavailable'][Math.min(2,d-1)]}</div><div class="event ${a?'good':'bad'}">${a?'Agent updates the remaining plan using the new state.':'Agent preserves the original sequence and loses tasks.'}</div>`:'<div class="prompt">Add disruptions and compare both strategies. Replanning is useful, but not free.</div>'}</div>`};q('#run').onclick=()=>{state.ran=true;render()};q('#strategy').onchange=render;wire(['disrupt','cost'],render);render()}
const memories=[['2024','User likes window seats',.82],['Today','Flight UA 508 delayed',.95],['2025','User visited Tokyo',.35],['Today','Meeting starts at 4 PM',.7],['2023','Old passport expired',.55],['Today','New passport ends 8842',.9],['Yesterday','User prefers concise updates',.62],['2022','Favorite café closed',.18]];
function memoryDemo(){shell(`${ctl('Relevance weight','rel',0,100,70)}${ctl('Recency weight','rec',0,100,30)}${ctl('Memory slots','slots',1,6,3)}${buttons('Retrieve memories')}`);state={ran:false};let render=()=>{let rw=+q('#rel').value/100,cw=+q('#rec').value/100,n=+q('#slots').value;let ranked=memories.map((m,i)=>({m,i,s:m[2]*rw+([1,3,5].includes(i)?1:.15)*cw})).sort((a,b)=>b.s-a.s);let picked=state.ran?ranked.slice(0,n).map(x=>x.i):[];q('#viz').innerHTML=metrics([['stored',8],['retrieved',picked.length],['useful today',picked.filter(i=>[1,3,5,6].includes(i)).length]])+`<div class="prompt">Request: “Help me prepare for today’s trip and meeting.”</div><div class="memory">${memories.map((m,i)=>`<div class="mem ${picked.includes(i)?'on':''}"><b>${m[0]}</b><br>${m[1]}</div>`).join('')}</div><div class="prompt">${state.ran?'Retrieval scores combine relevance and recency; capacity determines what reaches the active context.':'Predict which three memories should be retrieved.'}</div>`};q('#run').onclick=()=>{state.ran=true;render()};wire(['rel','rec','slots'],render);render()}
function contextDemo(){shell(`${ctl('Context budget','budget',6,18,10)}${ctl('Conversation history','history',1,10,5)}${ctl('Evidence chunks','evidence',1,10,5)}${buttons('Pack context')}`);state={ran:false};let render=()=>{let b=+q('#budget').value,h=+q('#history').value,e=+q('#evidence').value,needed=2+h+e,overflow=Math.max(0,needed-b),kept=Math.min(e,Math.max(0,b-2-Math.min(h,4))),grounded=kept>=3;let toks=Array.from({length:18},(_,i)=>`<div class="token ${i<b?'hot':''} ${state.ran&&i>=b-overflow&&i<b?'used':''}"></div>`).join('');q('#viz').innerHTML=metrics([['budget',b],['requested',needed],['evidence kept',state.ran?kept:'—']])+`<div class="budget">${toks}</div><div class="legend"><span>🟧 available context</span><span>⬜ unavailable</span><span>⬛ displaced content</span></div><div class="track"><div class="node done">Instructions<br><small>2 units</small></div><div class="arrow"></div><div class="node ${state.ran?'done':''}">History<br><small>${h} units</small></div><div class="arrow"></div><div class="node ${state.ran&&(grounded?'done':'active')}">Evidence<br><small>${e} units</small></div></div><div class="prompt">${state.ran?(grounded?'Enough evidence survived packing for the answer to cite its source.':'Conversation history crowded out evidence. Increase budget or compress history.'):'Finite context turns prompt assembly into a resource allocation problem.'}</div>`};q('#run').onclick=()=>{state.ran=true;render()};wire(['budget','history','evidence'],render);render()}
function verify(){shell(`${ctl('Claims drafted','claims',3,9,6)}${ctl('Checks allowed','checks',0,9,3)}${ctl('Check accuracy','accuracy',50,100,90)}${buttons('Draft + verify')}`);state={ran:false};let render=()=>{let n=+q('#claims').value,k=Math.min(n,+q('#checks').value),a=+q('#accuracy').value/100;let wrong=[1,4,7],caught=state.ran?wrong.filter(i=>i<n&&i<k&&((i*37+13)%100)/100<a):[];let remain=state.ran?wrong.filter(i=>i<n&&!caught.includes(i)).length:0;q('#viz').innerHTML=metrics([['claims',n],['checked',state.ran?k:0],['errors remaining',state.ran?remain:'—']])+`<div class="claims">${Array.from({length:n},(_,i)=>{let bad=wrong.includes(i),c=caught.includes(i);return `<div class="claim ${state.ran?(c?'fail':bad&&i<k?'pass':''):''}"><span>Claim ${i+1}: ${['venue seats 220','deadline is Friday','budget is $900','speaker confirmed','permit approved','doors open at 5','catering is vegan','Wi-Fi tested','recording enabled'][i]}</span><b>${state.ran?(c?'✕ corrected':i<k?'✓ checked':'not checked'):'draft'}</b></div>`}).join('')}</div><div class="prompt">${state.ran?'Verification is a separate operation with its own budget and fallibility. It reduces risk; it does not guarantee truth.':'Predict how many errors survive when only the first claims are checked.'}</div>`};q('#run').onclick=()=>{state.ran=true;render()};wire(['claims','checks','accuracy'],render);render()}
function coordination(){shell(`${ctl('Agents','count',1,3,2)}${ctl('Handoff cost','handoff',0,8,3)}${ctl('Task coupling','coupling',0,10,5)}${buttons('Coordinate team')}`);state={ran:false};let render=()=>{let n=+q('#count').value,h=+q('#handoff').value,c=+q('#coupling').value,base=18,parallel=base/n,over=(n-1)*h*(.5+c/10),time=Math.round((parallel+over)*10)/10,quality=Math.min(98,60+n*13-Math.round(c*(n-1)*1.3));let names=['Researcher','Builder','Reviewer'];q('#viz').innerHTML=metrics([['agents active',state.ran?n:0],['completion time',state.ran?time+' min':'—'],['quality score',state.ran?quality+'/100':'—']])+`<div class="agents">${names.map((x,i)=>`<div class="agent-card ${state.ran&&i<n?'active':''}"><h3>${x}</h3><div class="status">${state.ran&&i<n?['collects sources','assembles launch','checks constraints'][i]:'idle'}</div><p>${state.ran&&i<n?['Evidence packet','Working prototype','Issue report'][i]:'—'}</p></div>`).join('')}</div><div class="score"><i style="width:${state.ran?quality:0}%"></i></div><div class="log">${state.ran&&n>1?`<div class="event">${n-1} handoff${n>2?'s':''} × cost ${h}; coupling ${c}/10 adds coordination overhead.</div>`:''}<div class="prompt">${state.ran?'More specialists can improve coverage and parallelism, while communication can erase the speed gain.':'Vary team size and predict whether “more agents” is always faster.'}</div></div>`};q('#run').onclick=()=>{state.ran=true;render()};wire(['count','handoff','coupling'],render);render()}
function init(){({ 'observe-act':observe,'replanning':replanning,'memory':memoryDemo,'context':contextDemo,'verification':verify,'coordination':coordination}[mode]||observe)()}init();
