import {params,forward,gradients,trainPair,resetParams,vocab,setRef,getRef,gradRef} from '../train/model.js';
const $=s=>document.querySelector(s), lessons=[{lead:'After lunch,',context:['the','cat'],target:'sat'},{lead:'Outside,',context:['the','dog'],target:'ran'},{lead:'In the morning,',context:['the','sun'],target:'shines'}];
const stages=['Predict','Reveal Target','Measure Loss','Inspect Gradient','Update Weights'];let stage=0,chosen=0,selected={group:'O',idx:[0,vocab.indexOf('sat')]},history=[],last=null,timer=null;
const fmt=x=>(x>=0?'+':'')+x.toFixed(4);const example=()=>lessons[chosen];
function fwd(){return forward(example().context,example().target)}
function stop(){clearInterval(timer);timer=null;$('#auto').textContent='Watch 30 steps'}
function fresh(){stop();resetParams();stage=0;last=null;selected={group:'O',idx:[0,vocab.indexOf(example().target)]};history=[fwd().loss];render('Predict first: which word will this untrained model choose?')}
function step(){stage=4;const before=getRef(selected),r=trainPair(example().context,example().target,+$('#lr').value);last={before,gradient:gradRef(r.g,selected),after:getRef(selected)};history.push(r.after.loss);render(`Update ${params.step}: parameters move according to their own gradients.`,true)}
function chart(){const max=Math.max(...history,1)*1.1,pts=history.map((v,i)=>[30+i*425/Math.max(1,history.length-1),135-v/max*115]);$('#history').innerHTML=`<text x="5" y="17" fill="#adc9d9" font-size="12">Loss</text><path d="M30 20V135H465" stroke="#456275" fill="none"/><polyline points="${pts.map(p=>p.join(',')).join(' ')}" stroke="#52ddbc" fill="none" stroke-width="3"/>${pts.map(([x,y])=>`<circle cx="${x}" cy="${y}" r="3" fill="#ffdb83"/>`).join('')}<text x="35" y="153" fill="#adc9d9" font-size="12">0</text><text x="420" y="153" fill="#adc9d9" font-size="12">${history.length-1} steps</text>`;$('#lossSummary').textContent=`${history[0].toFixed(3)} → ${history.at(-1).toFixed(3)} (same training example)`}
function render(message,changed=false){const e=example(),f=fwd(),g=gradients(e.context,e.target).g,w=getRef(selected),cg=gradRef(g,selected);$('#sentence').innerHTML=`${e.lead} <mark>${e.context.join(' ')}</mark> <span class="blank">${stage>0?e.target:'___'}</span>`;$('#question').textContent=['Which word gets the highest probability?','Does the model favor the observed word?','How expensive is a low target probability?','Which direction should this weight move?','What changed: weights, probabilities, or the sentence?'][stage];$('#target').textContent=stage>0?e.target:'Hidden — make a prediction first';$('#vector').textContent='['+f.e.map(fmt).join(', ')+']';$('#stagebar').innerHTML=stages.map((s,i)=>`<button data-stage="${i}" class="${stage===i?'active':''}">${i+1} · ${s}</button>`).join('');document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{stage=+b.dataset.stage;render('Inspect the current computation; only an update changes the parameters.')});
const group=selected.group;
const defs=[['E','Embedding',`${vocab.length} × 3 weights`,f.e],['W','Hidden', '3 × 4 weights · tanh',f.h],['O','Output',`4 × ${vocab.length} weights`,f.logits.slice(0,4)]];
$('#layers').innerHTML=defs.map(([id,name,shape,values])=>`<button class="layer ${changed?'changed':''}" data-layer="${id}" aria-pressed="${group===id}"><strong>${name}</strong><small>${shape}</small><span class="values">${values.map(fmt).join('<br>')}${id==='O'?'<br>…':''}</span><small>${id==='E'?'Mean embedding':id==='W'?'Hidden activations':'Logits (first 4)'}</small></button>`).join('');
document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{selected={group:b.dataset.layer,idx:[0,0]};last=null;render('Selected layer: its real weights are shown below. Click a number to edit it.')});
$('#matrixLabel').textContent={E:'EMBEDDING WEIGHTS · ROWS = TOKENS · COLUMNS = DIMENSIONS',W:'HIDDEN WEIGHTS · ROWS = INPUT DIMENSIONS · COLUMNS = HIDDEN UNITS',O:'OUTPUT WEIGHTS · ROWS = HIDDEN UNITS · COLUMNS = WORDS'}[group];
$('#matrix').style.gridTemplateColumns=`repeat(${params[group][0].length},1fr)`;
$('#matrix').innerHTML=params[group].map((row,i)=>row.map((v,j)=>`<button class="cell ${selected.idx[0]===i&&selected.idx[1]===j?'selected':''} ${changed?'changed':''}" data-i="${i}" data-j="${j}" title="${group}[${i},${j}]: ${v}">${v.toFixed(2)}</button>`).join('')).join('');
document.querySelectorAll('.cell').forEach(b=>b.onclick=()=>{selected={group,idx:[+b.dataset.i,+b.dataset.j]};last=null;render('This is an actual model weight. Move it and watch the activations and probabilities.')});
$('#readout').textContent=`${group}[${selected.idx.join(', ')}]: ${fmt(w)}`;
$('#slider').value=w;$('#update').textContent=stage>=3?(last?`${last.before.toFixed(4)} − ${$('#lr').value} × (${fmt(last.gradient)}) = ${last.after.toFixed(4)}\n(previous update; current gradient ${fmt(cg)})`:`w(new) = w − η × gradient\n${w.toFixed(4)} − ${$('#lr').value} × (${fmt(cg)})`):'Select a number. Move the weight slider.';$('#update').style.whiteSpace='pre-wrap';$('#update').style.fontSize='15px';$('#bars').innerHTML=vocab.map((t,i)=>({t,p:f.probs[i],i})).sort((a,b)=>b.p-a.p).map(x=>`<div class="bar ${stage>0&&x.i===f.y?'target':''}"><span>${x.t}</span><div class="track"><div class="fill" style="width:${100*x.p}%"></div></div><span>${(x.p*100).toFixed(1)}%</span></div>`).join('');$('#loss').textContent=stage>=2?`P(${e.target}) = ${f.probs[f.y].toFixed(4)}\nLoss = −ln(${f.probs[f.y].toFixed(4)})\n     = ${f.loss.toFixed(4)}`:'Reveal the target to compare.';$('#loss').style.whiteSpace='pre-wrap';$('#next').textContent=stage<4?stages[stage+1]+' →':'Take one gradient step →';$('#event').textContent=message||'All values are computed from the current parameters.';$('#step').textContent=`Training updates: ${params.step}`;chart();if(changed)setTimeout(()=>document.querySelectorAll('.changed').forEach(c=>c.classList.remove('changed')),450);window.__story={loss:f.loss,prob:f.probs[f.y],sum:f.probs.reduce((a,b)=>a+b,0),step:params.step,history:[...history]}}
$('#next').onclick=()=>{if(stage<4){stage++;render()}else step()};$('#one').onclick=step;$('#slider').oninput=e=>{stop();setRef(selected,+e.target.value);last=null;history=[fwd().loss];render('Manual edit: probabilities recomputed. Loss history restarts at these parameters.')};$('#auto').onclick=()=>{if(timer){stop();return}let n=0;$('#auto').textContent='Pause';timer=setInterval(()=>{step();if(++n>=30)stop()},450)};$('#reset').onclick=fresh;$('#example').onchange=e=>{chosen=+e.target.value;fresh()};$('#lr').onchange=()=>{last=null;render()};fresh();
