import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
const $=id=>document.getElementById(id);let trace,selected=0,archive,meshes=[],live=false;
const view=$('scene'),scene=new THREE.Scene();scene.background=new THREE.Color('#091421');
const camera=new THREE.PerspectiveCamera(40,1,.01,1000);camera.position.set(8,6,10);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));view.append(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;
scene.add(new THREE.AmbientLight(0xffffff,2));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(5,10,6);scene.add(light);
scene.add(new THREE.GridHelper(12,12,0x456176,0x203748));scene.add(new THREE.AxesHelper(4));let pathGroup=new THREE.Group();scene.add(pathGroup);
new ResizeObserver(()=>{const w=view.clientWidth,h=view.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()}).observe(view);
function animate(){requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)}animate();
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down;
renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);
renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(meshes);if(hit[0]){selected=hit[0].object.userData.index;updateState()}});
function bars(id,items){const el=$(id);el.replaceChildren();for(const o of items){const row=document.createElement('div');row.className='row';const label=document.createElement('span');label.textContent=JSON.stringify(o.token);label.title=o.token;const bar=document.createElement('div');bar.className='bar';const fill=document.createElement('div');fill.className='fill';fill.style.width=Math.max(0,Math.min(100,o.p*100))+'%';bar.append(fill);const val=document.createElement('span');val.textContent=(o.p*100).toFixed(1)+'%';row.append(label,bar,val);el.append(row)}}
function draw(){pathGroup.traverse(x=>{x.geometry?.dispose();if(x.material)x.material.dispose()});scene.remove(pathGroup);pathGroup=new THREE.Group();scene.add(pathGroup);meshes=[];const states=trace.states;let max=Math.max(1,...states.flatMap(s=>s.position.map(Math.abs)));const pts=states.map(s=>new THREE.Vector3(...s.position.map(v=>v/max*4)));if(pts.length>1)pathGroup.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0x4ddfc7})));pts.forEach((p,i)=>{const m=new THREE.Mesh(new THREE.SphereGeometry(.19,24,16),new THREE.MeshStandardMaterial({color:0x4ddfc7}));m.position.copy(p);m.userData.index=i;pathGroup.add(m);meshes.push(m)});$('stateButtons').replaceChildren();states.forEach((s,i)=>{const b=document.createElement('button');b.textContent=i+1;b.onclick=()=>{selected=i;updateState()};$('stateButtons').append(b)});$('answer').textContent=trace.answer||'(empty output)';$('expected').textContent=trace.expectedAnswer?'Dataset answer: '+trace.expectedAnswer:'Custom question: no ground-truth answer supplied.';$('timing').textContent=`${trace.inputTokens} input tokens · ${trace.elapsedSeconds}s measured inference · ${trace.answerTokens.length} generated tokens`;$('projection').textContent='PCA view of 768 dimensions. Variance retained: '+(100*trace.explainedVariance.reduce((a,b)=>a+b,0)).toFixed(1)+'%. Coordinates rescale for this trajectory.';$('decodeToken').replaceChildren();(trace.decodeSteps||[{token:'First token',top:trace.firstTokenProbabilities}]).forEach((d,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${i+1}: ${JSON.stringify(d.token)}`;$('decodeToken').append(o)});$('decodeToken').onchange=()=>bars('probs',trace.decodeSteps?.[Number($('decodeToken').value)]?.top||trace.firstTokenProbabilities);$('decodeToken').onchange();updateState()}
function updateState(){selected=Math.max(0,Math.min(selected,trace.states.length-1));const s=trace.states[selected];meshes.forEach((m,i)=>{m.material.color.setHex(i===selected?0xffcb62:0x4ddfc7);m.scale.setScalar(i===selected?1.6:1)});Array.from($('stateButtons').children).forEach((b,i)=>b.classList.toggle('selected',i===selected));$('stepLabel').textContent=s?`State ${selected+1} / ${trace.states.length}`:'No latent steps';$('stats').textContent=s?`‖h‖ = ${s.norm.toFixed(4)} · 768 values`:'Answer decoded directly after the boundary marker.';$('vector').replaceChildren();if(s){const offset=Number($('offset').value);s.vector.slice(offset,offset+16).forEach((v,i)=>{const el=document.createElement('div');el.textContent=`h[${i+offset}] ${v.toFixed(4)}`;$('vector').append(el)});bars('probe',s.probe)}else $('probe').replaceChildren();$('previous').disabled=!s||selected===0;$('next').disabled=!s||selected>=trace.states.length-1}
for(let i=0;i<768;i+=16){const o=document.createElement('option');o.value=i;o.textContent=`${i}–${i+15}`;$('offset').append(o)}$('offset').onchange=updateState;
$('next').onclick=()=>{selected++;updateState()};$('previous').onclick=()=>{selected--;updateState()};$('reset').onclick=()=>{camera.position.set(8,6,10);controls.target.set(0,0,0);selected=0;updateState()};$('steps').oninput=()=>{$('stepsValue').textContent=$('steps').value};
$('download').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(trace,null,2)],{type:'application/json'}));a.download='measured-latent-states.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
function choose(i){trace=structuredClone(archive.traces[i]);selected=0;$('question').value=trace.question;$('steps').value=trace.latentSteps;$('stepsValue').textContent=trace.latentSteps;$('mode').textContent='Recorded real inference · Replay';draw()}
$('sample').onchange=()=>choose(Number($('sample').value));
$('run').onclick=async()=>{if(!live)return;$('run').disabled=true;$('mode').textContent='Running actual local model…';try{const response=await fetch('/api/latent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:$('question').value,steps:Number($('steps').value)})});const r=await response.json();if(!response.ok)throw new Error(r.error||'Inference failed');trace=r;selected=0;$('sample').value='custom';$('mode').textContent='Live local inference · Actual measured states';draw()}catch(e){$('mode').textContent='Inference error: '+e.message}finally{$('run').disabled=false}};
try{const r=await fetch('./recorded-traces.json');if(!r.ok)throw new Error('Recorded traces unavailable');archive=await r.json();const custom=document.createElement('option');custom.value='custom';custom.textContent='Custom live run';custom.disabled=true;$('sample').append(custom);archive.traces.forEach((t,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`Question ${t.datasetIndex+1} · ${t.latentSteps} latent steps`;$('sample').append(o)});choose(0);window.latentDemo={getTrace:()=>trace,select:i=>{selected=i;updateState()}}}catch(e){$('mode').textContent=e.message}
try{if(location.hostname.endsWith('github.io'))throw new Error('Static hosting');const r=await fetch('/api/health');const d=await r.json();live=d.latent===true}catch{}$('run').disabled=!live;$('server').textContent=live?'Local inference server connected. New runs use the real checkpoint.':'Recorded real model runs · GitHub Pages cannot execute the Python model. Inspect all states here; use the included local server for new questions.';
