import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {examples,vocab,params,forward,gradients,trainPair,resetParams,getRef,setRef,gradRef,state,shape} from './model.js';
const $=s=>document.querySelector(s), fmt=(x,n=3)=>Number(x).toFixed(n);
const full=[
  'After lunch, the cat ___','At sunrise, the dog ___','In the morning, the sun ___',
  'On the rug, the cat sat ___','Above the hills, the sun shines ___','After the storm, the sky shines bright ___','The cat sat on the ___',
  'The students submitted their final ___','To reduce the loss, update the ___'
];
let ex=examples[0],exIndex=0,stage='predict',selected=null,lastGradient=null,lastDelta=new Map(),lossHistory=[],scene,camera,renderer,controls,raycaster,mouse,cells=[],layerGroup;
const select=$('#example'); examples.forEach((e,i)=>select.add(new Option(full[i].replace('___','?'),i)));
function refName(r){return `${r.group}[${r.idx.join(', ')}]`}
function snapshotFlat(s){const m=new Map;for(const n of ['E','W','O'])for(let i=0;i<s[n].length;i++)for(let j=0;j<s[n][i].length;j++)m.set(`${n}[${i}, ${j}]`,s[n][i][j]);for(const n of ['b','c'])for(let i=0;i<s[n].length;i++)m.set(`${n}[${i}]`,s[n][i]);return m}
function delta(before,after){const a=snapshotFlat(before),b=snapshotFlat(after),m=new Map;for(const[k,v]of b)m.set(k,v-a.get(k));return m}
function vector(a){return `[ ${a.map(v=>(v>=0?'+':'')+fmt(v)).join('  ')} ]`}
function sentenceHTML(){const words=full[exIndex].split(' '),blank=words.pop(),b=words.splice(-2),a=words;return `<span class="past">${a.join(' ')}</span> <span class="context">${b.join(' ')}</span> <span class="blank">${blank}</span>`}
function render(){const f=forward(ex.context,ex.target),order=f.probs.map((p,i)=>({p,i})).sort((a,b)=>b.p-a.p);$('#steps').textContent=params.step;$('#sentence').innerHTML=sentenceHTML();$('#target').classList.toggle('hidden',stage==='predict');$('#target strong').textContent=ex.target;$('#inputVec').textContent=vector(f.e);$('#hiddenVec').textContent=vector(f.h);$('#targetProb').textContent=stage==='predict'?'hidden':`${(100*f.probs[f.y]).toFixed(1)}%`;$('#loss').textContent=['loss','gradient','update'].includes(stage)?fmt(f.loss):'hidden';$('#bars').innerHTML=order.map(({p,i})=>`<div class="bar ${i===f.y&&stage!=='predict'?'target':''}"><span class="token">${vocab[i]}</span><div class="track"><div class="fill" style="width:${Math.max(1,p*100)}%"></div></div><code>${(100*p).toFixed(1)}%</code></div>`).join('');$('#winner').textContent=vocab[order[0].i];$('#winnerP').textContent=`${(100*order[0].p).toFixed(1)}%`;const show=selected&&lastGradient&&['gradient','update'].includes(stage);$('#gradient').classList.toggle('hidden',!show);if(show){$('#gradientLabel').textContent=stage==='update'?'GRADIENT USED FOR THIS UPDATE':'CURRENT CELL GRADIENT';$('#gradient strong').textContent=fmt(gradRef(lastGradient,selected),6)}if(selected){const v=getRef(selected);$('#weight').disabled=false;$('#weightNum').disabled=false;$('#weight').value=v;$('#weightNum').value=fmt(v,5);const d=lastDelta.get(refName(selected));$('#change').textContent=d===undefined?'current':`${fmt(v-d,4)} → ${fmt(v,4)}  Δ${d>=0?'+':''}${fmt(d,5)}`}else{$('#weight').disabled=true;$('#weightNum').disabled=true}document.querySelectorAll('[data-stage]').forEach(b=>b.classList.toggle('active',b.dataset.stage===stage));drawChart();buildLayers(f,order.slice(0,4));}
select.onchange=()=>{exIndex=+select.value;ex=examples[exIndex];stage='predict';lastGradient=null;lastDelta.clear();lossHistory=[];render();prompt('New example. Which token will the current weights predict?')};
function prompt(t){$('#prompt').textContent=t}
const copy={predict:'Forward pass only: parameters are fixed.',target:'The target comes from the training corpus.',loss:'Loss is −log P(the true next token).',gradient:'Backpropagation gives every parameter a loss gradient.',update:'Every visible layer now shows the updated parameters.'};
document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{stage=b.dataset.stage;if(stage==='gradient')lastGradient=gradients(ex.context,ex.target).g;if(stage==='update'){const before=state(),r=trainPair(ex.context,ex.target,+$('#lr').value),after=state();lastGradient=r.g;lastDelta=delta(before,after);lossHistory.push({step:params.step,loss:r.after.loss});flashLargeDeltas()}render();prompt(copy[stage])});
$('#train20').onclick=()=>{for(let i=0;i<20;i++){const before=state(),r=trainPair(ex.context,ex.target,+$('#lr').value),after=state();lastDelta=delta(before,after);lossHistory.push({step:params.step,loss:forward(ex.context,ex.target).loss})}lastGradient=selected?gradients(ex.context,ex.target).g:null;stage='update';render();prompt('20 real SGD updates completed; the chart preserves each measured loss.')};
$('#reset').onclick=()=>{resetParams();stage='predict';selected=null;lastGradient=null;lastDelta.clear();lossHistory=[];$('#cellName').textContent='Click a numbered cell';$('#change').textContent='—';render();prompt('Seeded initial parameters restored.')};
function change(v){if(!selected)return;const before=getRef(selected);setRef(selected,+v);lastDelta=new Map([[refName(selected),+v-before]]);lastGradient=gradients(ex.context,ex.target).g;render();prompt('Manual parameter edit: vectors, logits, softmax, and loss recomputed.')}
$('#weight').oninput=e=>change(e.target.value);$('#weightNum').oninput=e=>change(e.target.value);

function init3D(){const root=$('#layers3d');scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(35,root.clientWidth/root.clientHeight,.1,100);camera.position.set(0,.8,8);renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(root.clientWidth,root.clientHeight);root.appendChild(renderer.domElement);controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,0,0);raycaster=new THREE.Raycaster();mouse=new THREE.Vector2();scene.add(new THREE.AmbientLight(0xffffff,2.4));const d=new THREE.DirectionalLight(0xffffff,2.5);d.position.set(4,7,8);scene.add(d);renderer.domElement.onclick=e=>{const r=renderer.domElement.getBoundingClientRect();mouse.x=(e.clientX-r.left)/r.width*2-1;mouse.y=-(e.clientY-r.top)/r.height*2+1;raycaster.setFromCamera(mouse,camera);const hit=raycaster.intersectObjects(cells,false)[0];if(hit){selected=hit.object.userData.ref;lastGradient=gradients(ex.context,ex.target).g;$('#cellName').textContent=refName(selected);render();prompt('Selected a real trainable parameter. Drag the control to perturb it.')}};function loop(){requestAnimationFrame(loop);controls.update();renderer.render(scene,camera)}loop()}
function textSprite(text,color='#fff',scale=.52){const c=document.createElement('canvas');c.width=220;c.height=72;const x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.fillStyle='rgba(3,12,20,.83)';x.roundRect(2,2,216,68,9);x.fill();x.font='700 25px ui-monospace, monospace';x.textAlign='center';x.textBaseline='middle';x.fillStyle=color;x.fillText(text,110,37);const t=new THREE.CanvasTexture(c),m=new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false,depthWrite:false}),s=new THREE.Sprite(m);s.renderOrder=20;s.scale.set(1.55*scale,.5*scale,1);return s}
function slabTitle(text,x,color){const s=textSprite(text,color,1);s.position.set(x,2.25,0);layerGroup.add(s)}
function cell(ref,x,y,z,color){const v=getRef(ref),g=new THREE.BoxGeometry(.64,.48,.10),m=new THREE.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.13,roughness:.42}),o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.userData={ref};const d=lastDelta.get(refName(ref))||0;if(Math.abs(d)>1e-8){o.material.emissiveIntensity=Math.min(1.8,.35+Math.abs(d)*12);o.scale.setScalar(1+Math.min(.28,Math.abs(d)*5))}const label=textSprite(fmt(v,2),'#ffffff',.57);label.position.copy(o.position);label.position.z+=.12;label.renderOrder=20;layerGroup.add(o,label);cells.push(o)}
function buildLayers(f,top){if(layerGroup)scene.remove(layerGroup);layerGroup=new THREE.Group();cells=[];scene.add(layerGroup);const rows=f.xs;slabTitle('INPUT E',-3.0,'#2dd4bf');for(let r=0;r<2;r++)for(let i=0;i<shape.D;i++)cell({group:'E',idx:[rows[r],i]},-3.0+(r-.5)*.72,(i-1)*.62,0,0x2dd4bf);slabTitle('HIDDEN W',0,'#ffd166');for(let i=0;i<shape.D;i++)for(let j=0;j<shape.H;j++)cell({group:'W',idx:[i,j]},(i-1)*.7,(j-1.5)*.58,0,0xffd166);slabTitle('TOP OUTPUT O',3.0,'#ff7182');for(let j=0;j<shape.H;j++)for(let k=0;k<top.length;k++)cell({group:'O',idx:[j,top[k].i]},3.0+(k-1.5)*.58,(j-1.5)*.58,0,0xff7182)}
function flashLargeDeltas(){/* intensity is derived from exact deltas when layers rebuild */}
function drawChart(){const svg=$('#lossChart'),line=$('#lossLine'),dot=$('#lossDot');if(!lossHistory.length){line.setAttribute('points','');dot.setAttribute('cx',0);dot.setAttribute('cy',100);$('#historyReadout').textContent=`step ${params.step}`;return}const data=lossHistory.slice(-100),max=Math.max(...data.map(d=>d.loss),.001),min=Math.min(...data.map(d=>d.loss)),span=Math.max(.001,max-min),pts=data.map((d,i)=>`${data.length===1?350:i/(data.length-1)*700},${100-(d.loss-min)/span*88}`).join(' ');line.setAttribute('points',pts);const last=pts.split(' ').at(-1).split(',');dot.setAttribute('cx',last[0]);dot.setAttribute('cy',last[1]);$('#historyReadout').textContent=`step ${data.at(-1).step} · loss ${fmt(data.at(-1).loss)}`}
init3D();render();
