import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {kernels,sigmoid,image,patch,correlate,relu,pool,network} from './math.js';
const $=id=>document.getElementById(id), gold=0xffd36b,teal=0x58ded1,pink=0xed8299;
const nn=t=>`https://www.youtube.com/watch?v=aircAruvnKk&t=${t}s`,cv=t=>`https://www.youtube.com/watch?v=KuXjwB4LzSA&t=${t}s`;
const chapters=[
 ['01 / Pixels','An image becomes a vector','Keep the values. Change only how they are arranged.',nn(187),'How many values change when the image becomes a vector?','An 8 × 8 image is unfolded into 64 inputs. Each cube carries the same brightness from the image into the column. The gold cube is one value followed through the rearrangement.','Source uses 28 × 28 = 784 pixels. This smaller grid keeps every value inspectable. No inference or training happens here.'],
 ['02 / One neuron','Nine inputs. One activation.','Multiply each input by its weight, add a bias, then apply sigmoid.',nn(519),'What happens when a negative weight is made more negative?','Teal connections carry positive contributions; rose connections carry negative ones. The intermediate sum can be negative, but sigmoid maps it into (0, 1).','Weights are hand-set for inspection, not trained. A bright neuron means a high activation, not necessarily a probability.'],
 ['03 / Layers','Signals travel through layers','Watch a complete, numerically computed forward pass.',nn(187),'Does increasing every weight always increase every output?','The 8 → 4 → 2 network uses fixed signed weights. The pulse reveals the input, hidden activations and output activations in sequence.','Small illustrative network. Outputs are independent sigmoid activations, not class probabilities; no trained digit-recognition claim. Features need not match human concepts.'],
 ['04 / Products','Unfold one convolution step','Separate the image patch, the kernel and the nine products.',cv(538),'With an averaging kernel, where must the result fall relative to the nine inputs?','Each matching pair is multiplied. All nine products are summed to make exactly one output value. Use the timeline to pull the layers apart.','Stride 1, valid padding, no bias. CNN-style cross-correlation: the kernel is not flipped. Mathematical convolution flips it by 180°.'],
 ['05 / Sliding','One kernel visits every position','The same nine weights are reused across the entire image.',cv(538),'Why does an 8 × 8 input produce a 6 × 6 output here?','Move the scan to inspect any patch. The highlighted output is the sum of the highlighted 3 × 3 input patch times the selected kernel.','Valid padding excludes windows that would cross the border. Signed outputs are shown without clipping; teal is positive and rose is negative.'],
 ['06 / Gaussian','A bell-shaped neighborhood','In 3D, height is weight: nearby pixels contribute more.',cv(635),'How does widening the bell change the balance between center and neighbors?','A normalized 7 × 7 Gaussian kernel is drawn as a surface. Its 49 weights add to one; changing sigma redistributes that fixed total.','Original 3D extension of the source’s tilted image and Gaussian-weight visualization. Discrete normalized kernel, not a continuous density integral.'],
 ['07 / Signed edges','An edge has a direction','Equal neighborhoods cancel. Opposite edges reverse the sign.',cv(661),'If black and white exchange sides, what happens to the output sign?','Use the flip control to reverse the edge. Source kernel: [0.25, 0, −0.25; 0.5, 0, −0.5; 0.25, 0, −0.25]. Positive and negative responses remain visible.','Uses the source coefficient arrangement as cross-correlation. Black-left / white-right produces −1. Flipping the kernel changes that sign.'],
 ['08 / RGB','Color is three parallel calculations','Blur the red, green and blue channels independently.',cv(560),'Does ordinary RGB blur mix red into the green channel?','Three channel planes each pass through the same averaging kernel. The three output values form a new RGB pixel; they are not added together.','This is per-channel RGB blur, as in the source. A learned CNN kernel can instead sum across input channels; that is a different operation.'],
 ['09 / Filter bank','One image, several feature maps','Different weights ask different questions of the same pixels.',cv(745),'Which map responds strongly to a vertical boundary?','A blur, a vertical difference and a horizontal difference produce three distinct 6 × 6 output maps from one input. Rotate the view to see the stack.','Hand-selected filters illustrate a mechanism. Learned filters need not represent these specific concepts. Depth here means channel index, not physical depth.'],
 ['10 / A CNN block','Convolve → activate → reduce','Follow actual values through a small, inspectable CNN block.',cv(745),'Which values survive ReLU? What is lost by max pooling?','The signed 6 × 6 feature map passes through ReLU, then non-overlapping 2 × 2 max pooling produces a 3 × 3 map. Inspect all three stages.','Added teaching extension, not a scene claimed to appear in the source. This is a computed block with hand-set weights, not a trained CNN.']
];
let state={chapter:0,p:0,kernel:'blur',pattern:'ring',gain:1,bias:0,sigma:1,flip:0},playing=false,lastTime=0,dirty=true,pendingFit=true;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.1,150);let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));$('stage').appendChild(renderer.domElement);$('loading').hidden=true;$('loading').style.display='none';}catch(e){$('loading').textContent='WebGL could not start. Try a browser with hardware acceleration enabled.';throw e;}
const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.dampingFactor=.08;orbit.minDistance=9;orbit.maxDistance=55;
scene.add(new THREE.AmbientLight(0xffffff,2));let light=new THREE.DirectionalLight(0xffffff,3);light.position.set(0,10,20);scene.add(light);
let group=new THREE.Group();scene.add(group);let labelPoints=[];const cubeGeo=new THREE.BoxGeometry(1,1,1),sphereGeo=new THREE.SphereGeometry(1,18,12);
function clear(){group.traverse(o=>{if(o.material){(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>{if(m.map)m.map.dispose();m.dispose();});}if(o.geometry&&o.geometry!==cubeGeo&&o.geometry!==sphereGeo)o.geometry.dispose();});scene.remove(group);group=new THREE.Group();scene.add(group);$('labels').replaceChildren();labelPoints=[];}
function color(v,signed=false){if(signed)return new THREE.Color(v<0?pink:teal).multiplyScalar(.2+.8*Math.min(1,Math.abs(v)));return new THREE.Color().setRGB(.06+.8*v,.1+.82*v,.18+.8*v);}
function box(x,y,z,w,h,d,c,opacity=1){let m=new THREE.Mesh(cubeGeo,new THREE.MeshStandardMaterial({color:c,transparent:opacity<1,opacity,roughness:.7}));m.position.set(x,y,z);m.scale.set(w,h,d);group.add(m);return m;}
function ball(x,y,z,r,c){let m=new THREE.Mesh(sphereGeo,new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:.13}));m.position.set(x,y,z);m.scale.setScalar(r);group.add(m);return m;}
function line(a,b,c=0x62758e,opacity=.5){let g=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(...a),new THREE.Vector3(...b)]);let l=new THREE.Line(g,new THREE.LineBasicMaterial({color:c,transparent:true,opacity}));group.add(l);}
function label(txt,x,y,z,c='#dce8fa'){let el=document.createElement('div');el.className='label';el.textContent=txt;el.style.color=c;$('labels').appendChild(el);labelPoints.push({el,p:new THREE.Vector3(x,y,z)});}
function grid(a,n,cx,cy,z,s=.47,signed=false,numbers=false){a.forEach((v,i)=>{let x=cx+(i%n-(n-1)/2)*s,y=cy+((n-1)/2-Math.floor(i/n))*s;box(x,y,z,s*.91,s*.91,.10,color(v,signed));if(numbers)number(v,x,y,z+.065,s*.72);});}
function number(v,x,y,z,size=.28){let cn=document.createElement('canvas');cn.width=128;cn.height=64;let c=cn.getContext('2d');c.font='bold 28px monospace';c.textAlign='center';c.textBaseline='middle';c.fillStyle='#07111e';c.fillRect(0,0,128,64);c.fillStyle='#fff';c.fillText(typeof v==='string'?v:Math.abs(v)<.0005?'0':v.toFixed(2),64,33);let tx=new THREE.CanvasTexture(cn);let m=new THREE.Mesh(new THREE.PlaneGeometry(size*1.6,size*.8),new THREE.MeshBasicMaterial({map:tx,transparent:true,side:THREE.DoubleSide}));m.position.set(x,y,z);group.add(m);}
function frame(cx,cy,z,w,h,c=gold){let p=[[cx-w/2,cy-h/2,z],[cx+w/2,cy-h/2,z],[cx+w/2,cy+h/2,z],[cx-w/2,cy+h/2,z],[cx-w/2,cy-h/2,z]];for(let i=0;i<4;i++)line(p[i],p[i+1],c,1);}
function arrow(a,b,c=gold){let va=new THREE.Vector3(...a),vb=new THREE.Vector3(...b),d=vb.clone().sub(va);group.add(new THREE.ArrowHelper(d.clone().normalize(),va,d.length(),c,.24,.13));}
const f=n=>n.toFixed(3);function read(eq,values){$('equation').textContent=eq;$('values').textContent=values;}
function selectControl(id,title,options,value,handler){let wrap=document.createElement('div');wrap.className='control';let l=document.createElement('label');l.htmlFor=id;l.textContent=title;let s=document.createElement('select');s.id=id;options.forEach(([v,t])=>{let o=document.createElement('option');o.value=v;o.textContent=t;s.appendChild(o);});s.value=value;s.onchange=()=>handler(s.value);wrap.append(l,s);$('controls').appendChild(wrap);}
function slider(id,title,min,max,step,value,handler){let w=document.createElement('div');w.className='control';let l=document.createElement('label');l.htmlFor=id;let t=document.createElement('span');t.textContent=title;let o=document.createElement('output');o.textContent=value;l.append(t,o);let r=document.createElement('input');r.type='range';r.id=id;r.min=min;r.max=max;r.step=step;r.value=value;r.oninput=()=>{o.textContent=r.value;handler(+r.value);};w.append(l,r);$('controls').appendChild(w);}
function configure(){let s=state.chapter,c=chapters[s];$('eyebrow').textContent=`${String(s+1).padStart(2,'0')} / 10 · ${s<3?'NEURAL NETWORKS':'CONVOLUTIONS'}`;$('title').textContent=c[1];$('subtitle').textContent=c[2];$('source').href=c[3];$('question').textContent=c[4];$('explanation').textContent=c[5];$('boundary').textContent=c[6];$('controls').replaceChildren();if(![1,5,6,7].includes(s))selectControl('pattern','Input image',[['ring','Loop'],['edge','Vertical edge'],['diagonal','Diagonal']],state.pattern,v=>{state.pattern=v;dirty=true;});if([3,4,9].includes(s))selectControl('kernel','Kernel',[['blur','Average · 1/9'],['vertical','Vertical difference'],['horizontal','Horizontal difference'],['sharpen','Sharpen']],state.kernel,v=>{state.kernel=v;dirty=true;});if([1,2].includes(s)){slider('gain','Weight multiplier',-2,2,.1,state.gain,v=>{state.gain=v;dirty=true;});slider('bias','Bias',-4,4,.1,state.bias,v=>{state.bias=v;dirty=true;});}if(s===5)slider('sigma','Gaussian width σ',.4,2.5,.05,state.sigma,v=>{state.sigma=v;dirty=true;pendingFit=true;});if(s===6)selectControl('flip','Edge direction',[['0','Black → white'],['1','White → black']],String(state.flip),v=>{state.flip=+v;dirty=true;});$('progress-label').textContent=['Unfold','Accumulate','Forward pass','Separate','Scan','Lift surface','Inspect','Separate','Separate','Reveal'][s];document.querySelectorAll('#chapters button').forEach((b,i)=>b.classList.toggle('active',i===s));dirty=true;}
function renderScene(){clear();let s=state.chapter,p=state.p,a=image(state.pattern),k=kernels[state.kernel],result={chapter:s+1,progress:p};
 if(s===0){for(let i=0;i<64;i++){let x0=(i%8-3.5)*.58-3,y0=(3.5-Math.floor(i/8))*.58,x1=3,y1=(31.5-i)*.105;let x=x0+(x1-x0)*p,y=y0+(y1-y0)*p,z=Math.sin(p*Math.PI)*(i%8)*.12;box(x,y,z,.48*(1-p)+.35*p,.48*(1-p)+.078*p,.16,i===27?gold:color(a[i]));}label('8 × 8 image',-3,3.25,0);label('64 × 1 vector',3,4,0);read('8 × 8 = 64',`Same values · different arrangement\nHighlighted pixel: ${f(a[27])}\nInput order: row by row\nUnfold: ${Math.round(p*100)}%`);result.values=a;}
 if(s===1){let x=[1,.8,.1,.7,.2,.05,.1,.6,1],w=[1,.5,-1,.7,-.5,-.8,.2,.6,1].map(v=>v*state.gain),count=Math.floor(p*9),sum=x.reduce((v,a,i)=>v+a*w[i],state.bias),partial=x.slice(0,count).reduce((v,a,i)=>v+a*w[i],state.bias);for(let i=0;i<9;i++){let y=(4-i)*.63;ball(-4,y,0,.20,color(x[i]));number(x[i],-4.65,y,0,.25);line([-3.8,y,0],[1.7,0,0],w[i]<0?pink:teal,i<count?1:.15);number(w[i],-1.2,y*.8,.05,.3);if(i<count)ball(-3.7+(i/9)*5.2,y*(1-i/9),.1,.055,gold);}ball(2,0,0,.48,color(sigmoid(partial)));arrow([2.6,0,0],[4.1,0,0]);ball(4.7,0,0,.5,color(sigmoid(sum)));label('Inputs',-4,3.5,0);label('Signed weights',-1.2,3.5,0);label('σ(partial sum)',2,-1.2,0);label('σ(z)',4.7,1.1,0);read(`σ(${f(sum)}) = ${f(sigmoid(sum))}`,`z = Σ wᵢxᵢ + b\nBias b = ${f(state.bias)}\nRevealed terms: ${count} / 9\nPartial sum = ${f(partial)}\nσ(z) = 1 / (1 + exp(−z))`);result={...result,sum,activation:sigmoid(sum),partial};}
 if(s===2){let inputs=a.slice(24,32),n=network(inputs,state.gain,state.bias),sets=[inputs,n.h,n.o],positions=sets.map((ar,j)=>ar.map((v,i)=>[-5+j*5,(ar.length-1-2*i)*.42,j===1?.7:0]));for(let j=0;j<2;j++)positions[j].forEach((pos,i)=>positions[j+1].forEach((to,q)=>{let w=j===0?n.weights[q][i]:n.ow[q][i];line(pos,to,w<0?pink:teal,p>(j+.5)/3?.55:.09);}));sets.forEach((ar,j)=>ar.forEach((v,i)=>{let pos=positions[j][i];ball(...pos,.23,j/3<=p?color(v):0x182337);if(j===2)number(v,pos[0]+.8,pos[1],pos[2],.3);}));label('8 input activations',-5,4,0);label('4 hidden activations',0,3,.7);label('2 outputs',5,2,0);read('a⁽ˡ⁺¹⁾ = σ(Wa⁽ˡ⁾ + b)',`Hidden: ${n.h.map(f).join(', ')}\nOutput: ${n.o.map(f).join(', ')}\nTeal: positive weight\nRose: negative weight\nAll values computed from this input`);result={...result,...n};}
 if(s===3){let v=patch(a,2,2),products=v.map((x,i)=>x*k[i]),sum=products.reduce((s,x)=>s+x,0),spread=1+p*3;grid(v,3,-spread,0,0,.8,false,true);grid(k,3,0,0,1.8*p,.8,true,true);grid(products,3,spread,0,3.6*p,.8,true,true);label('Input patch',-spread,2,0);label('Kernel',0,2,1.8*p);label('Products',spread,2,3.6*p);if(p>.4){arrow([spread, -1.8,3.6*p],[spread,-2.6,3.6*p]);label(`Σ = ${f(sum)}`,spread,-3.1,3.6*p,'#ffd36b');}read(`Σ (xᵢ × kᵢ) = ${f(sum)}`,products.map((v,i)=>`${f(patch(a,2,2)[i])} × ${f(k[i])} = ${f(v)}`).join('\n'));result={...result,products,sum};}
 if(s===4){let ix=Math.min(35,Math.floor(p*36)),r=Math.floor(ix/6),c=ix%6,out=correlate(a,k);grid(a,8,-4,0,0,.62);grid(out.map((v,i)=>i<=ix?v:0),6,3.4,0,.7,.62,true);frame(-4+(c+1-3.5)*.62,(3.5-r-1)*.62,.17,1.84,1.84);frame(3.4+(c-2.5)*.62,(2.5-r)*.62,.85,.61,.61);line([-4+(c+1-3.5)*.62,(3.5-r-1)*.62,.17],[3.4+(c-2.5)*.62,(2.5-r)*.62,.85],gold,1);label('Input · 8 × 8',-4,3.1,0);label('Output · 6 × 6',3.4,2.6,.7);read(`y[${r},${c}] = ${f(out[ix])}`,`Position ${ix+1} of 36\nΣ patch × kernel\nStride = 1 · padding = 0\n8 − 3 + 1 = 6\nTeal + · rose −\nUnvisited cells are dark`);result={...result,index:ix,output:out};}
 if(s===5){let raw=Array.from({length:49},(_,i)=>Math.exp(-((i%7-3)**2+(Math.floor(i/7)-3)**2)/(2*state.sigma**2))),sum=raw.reduce((x,y)=>x+y),w=raw.map(x=>x/sum),max=Math.max(...w);grid(image('ring'),8,0,0,-.10,.75);const sg=new THREE.PlaneGeometry(4.5,4.5,48,48),sp=sg.attributes.position;for(let j=0;j<sp.count;j++){let x=sp.getX(j)/.75,y=sp.getY(j)/.75;sp.setZ(j,Math.exp(-(x*x+y*y)/(2*state.sigma**2))/sum*18*p+.02);}sg.computeVertexNormals();group.add(new THREE.Mesh(sg,new THREE.MeshStandardMaterial({color:teal,transparent:true,opacity:.65,side:THREE.DoubleSide,roughness:.35})));frame(0,0,.02,5.25,5.25,teal);w.forEach((v,i)=>{let x=(i%7-3)*.75,y=(3-Math.floor(i/7))*.75,z=v*18*p;ball(x,y,z+.04,.035,gold);if(i%7<6)line([x,y,z],[x+.75,y,w[i+1]*18*p],gold,.7);if(i<42)line([x,y,z],[x,y-.75,w[i+7]*18*p],gold,.7);});label('Normalized 7 × 7 Gaussian',0,3.3,0);label('Height = weight × fixed scale',0,-3.3,0);read(`Σ kᵢ = ${f(w.reduce((x,y)=>x+y))}`,`σ = ${state.sigma.toFixed(2)}\nCenter weight = ${f(w[24])}\nCorner weight = ${f(w[0])}\n49 non-negative weights\nTaller center → more local influence`);result={...result,weights:w};}
 if(s===6){let edge=Array.from({length:9},(_,i)=>{let col=i%3;return state.flip?1-col/2:col/2;}),ek=[.25,0,-.25,.5,0,-.5,.25,0,-.25],prod=edge.map((v,i)=>v*ek[i]),sum=prod.reduce((a,b)=>a+b);grid(edge,3,-4,0,0,.9,false,true);grid(ek,3,0,0,p*1.7,.9,true,true);grid(prod,3,4,0,0,.9,true,true);label('Brightness',-4,2.2,0);label('Signed kernel',0,2.2,p*1.7);label('Products',4,2.2,0);label(`Sum: ${f(sum)}`,4,-2.4,0,sum<0?'#ed8299':'#58ded1');read(`Edge response = ${f(sum)}`,`Left → right: ${state.flip?'white → black':'black → white'}\nKernel weights sum to 0\nUniform image response = 0\nReversing the edge reverses the sign\nNo clipping of negative values`);result={...result,sum};}
 if(s===7){let channels=[Array.from({length:9},(_,i)=>(i%3)/2),Array.from({length:9},(_,i)=>Math.floor(i/3)/2),[.1,.2,.3,.2,1,.2,.3,.2,.1]],means=channels.map(ar=>ar.reduce((a,b)=>a+b)/9),tints=[0xff7777,0x74e7a3,0x82a7ff];channels.forEach((ar,j)=>{let z=(j-1)*(1+p*2);ar.forEach((v,i)=>box(-3+(i%3-1)*.85,(1-Math.floor(i/3))*.85,z,.76,.76,.13,new THREE.Color(tints[j]).multiplyScalar(.12+.88*v)));label(['Red channel','Green channel','Blue channel'][j],-3,2.5+j*1.1,z);arrow([-1.4,0,z],[1.7,0,z],tints[j]);ball(2.2,0,z,.23,tints[j]);number(means[j],2.9,0,z,.35);});box(5,0,0,1.5,1.5,1.5,new THREE.Color(...means));label('Recombine RGB',5,2,0);read(`RGB = (${means.map(v=>v.toFixed(2)).join(', ')})`,`R′ = average of red patch\nG′ = average of green patch\nB′ = average of blue patch\nSame 1/9 kernel on each channel\nChannels are not summed together`);result={...result,means};}
 if(s===8){grid(a,8,-4,0,0,.58);label('One input',-4,3,0);['blur','vertical','horizontal'].forEach((key,j)=>{let z=(j-1)*(1+p*2.2);grid(correlate(a,kernels[key]),6,3,0,z,.52,true);label(['Average','Vertical','Horizontal'][j],3,2.4+j*1.1,z);arrow([-1.2,0,0],[1.25,0,z],[gold,teal,pink][j]);});read('1 input → 3 feature maps',`3 independent kernels\nEach map: 6 × 6\nStack: 6 × 6 × 3\nSame image, different responses\nZ separation = channel index`);result.outputs=['blur','vertical','horizontal'].map(key=>correlate(a,kernels[key]));}
 if(s===9){let conv=correlate(a,k),act=relu(conv),pooled=pool(act);grid(conv,6,-4.5,0,0,.56,true);grid(act,6,0,0,p*.8,.56,true);grid(pooled,3,4.5,0,p*1.6,.8,true,true);arrow([-2.6,0,0],[-1.9,0,p*.8]);arrow([1.9,0,p*.8],[3,0,p*1.6]);label('Convolution · 6 × 6',-4.5,2.8,0);label('ReLU · 6 × 6',0,2.8,p*.8);label('Max pool · 3 × 3',4.5,2.8,p*1.6);frame(-4.5-2*.56,2*.56,.2,1.12,1.12);frame(-2*.56,2*.56,p*.8+.2,1.12,1.12);frame(3.7,.8,p*1.6+.2,.8,.8);read('ReLU(x) = max(0, x)',`Negative inputs removed: ${conv.filter(x=>x<0).length}\nPool: 2 × 2 maximum, stride 2\nHighlighted pool result: ${f(pooled[0])}\n36 values → 9 values\nSpatial detail is discarded`);result={...result,convolution:conv,activation:act,pooled};}
 window.vision3D.last=result;dirty=false;}
function go(n){state={chapter:(n+chapters.length)%chapters.length,p:0,kernel:'blur',pattern:'ring',gain:1,bias:0,sigma:1,flip:0};if(state.chapter===9)state.kernel='vertical';state.p=[0,1,1,.8,.35,1,.65,.7,.7,.7][state.chapter];playing=false;$('play').textContent='▶ Play';$('progress').value=state.p;$('progress-value').textContent=`${Math.round(state.p*100)}%`;configure();home();}
function fit(front=false){if(!group.children.length)return;orbit.enableDamping=false;orbit.update();camera.up.set(0,state.chapter===5&&!front?0:1,state.chapter===5&&!front?1:0);const bounds=new THREE.Box3().setFromObject(group);labelPoints.forEach(q=>bounds.expandByPoint(q.p));const envelopes={0:[[-5.5,-3.6,-.3],[3.8,4.5,1.1]],3:[[-5.4,-3.6,-.2],[5.4,2.5,3.9]],7:[[-4.5,-1.5,-3.3],[5.8,3,3.3]],8:[[-6.4,-2.4,-3.4],[4.8,3.5,3.4]]};if(envelopes[state.chapter]){for(const v of envelopes[state.chapter])bounds.expandByPoint(new THREE.Vector3(...v));}const center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3());const dir=(front?new THREE.Vector3(0,0,1):state.chapter===5?new THREE.Vector3(1,-1,1.2):new THREE.Vector3(.22,.22,1)).normalize();const right=camera.up.clone().cross(dir).normalize(),up=dir.clone().cross(right).normalize(),tan=Math.tan(camera.fov*Math.PI/360);let needed=0;for(let ix of [-1,1])for(let iy of [-1,1])for(let iz of [-1,1]){let v=new THREE.Vector3(ix*size.x/2,iy*size.y/2,iz*size.z/2),z=v.dot(dir);needed=Math.max(needed,(Math.abs(v.dot(right))+.45)/(tan*camera.aspect)+z,(Math.abs(v.dot(up))+.45)/tan+z);}const distance=Math.max(7,needed*1.13);orbit.target.copy(center);camera.position.copy(center).addScaledVector(dir,distance);orbit.update();orbit.enableDamping=true;}function home(){pendingFit=true;dirty=true;}
chapters.forEach((c,i)=>{let b=document.createElement('button');b.textContent=c[0];b.onclick=()=>go(i);$('chapters').appendChild(b);});$('progress').oninput=()=>{state.p=+$('progress').value;playing=false;$('play').textContent='▶ Play';dirty=true;};$('play').onclick=()=>{playing=!playing;if(playing&&state.p>=1)state.p=0;$('play').textContent=playing?'❚❚ Pause':'▶ Play';};$('reset').onclick=()=>go(state.chapter);$('prev').onclick=()=>go(state.chapter-1);$('next').onclick=()=>go(state.chapter+1);$('front').onclick=()=>fit(true);$('oblique').onclick=home;$('home').onclick=home;$('fullscreen').onclick=()=>{document.body.classList.toggle('present');resize();};
function resize(){let w=$('stage').clientWidth,h=$('stage').clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();pendingFit=true;dirty=true;}new ResizeObserver(resize).observe($('stage'));
window.vision3D={get state(){return {...state};},last:null,go,math:{image,patch,correlate,relu,pool,network,kernels,sigmoid},camera};go(0);resize();
function animate(t){requestAnimationFrame(animate);let dt=Math.min(.05,(t-lastTime)/1000||0);lastTime=t;if(playing){state.p=Math.min(1,state.p+dt/10);dirty=true;if(state.p===1){playing=false;$('play').textContent='▶ Play';}}if(dirty){renderScene();if(pendingFit){fit();pendingFit=false;}$('progress').value=state.p;$('progress-value').textContent=`${Math.round(state.p*100)}%`;}orbit.update();renderer.render(scene,camera);let w=$('stage').clientWidth,h=$('stage').clientHeight;labelPoints.forEach(({el,p})=>{let q=p.clone().project(camera);el.style.left=(q.x*.5+.5)*w+'px';el.style.top=(-q.y*.5+.5)*h+'px';el.hidden=q.z>1||q.z<-1||Math.abs(q.x)>1.1||Math.abs(q.y)>1.1;});}requestAnimationFrame(animate);
