import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {words,trace,multi,cross,parameters,dot,mul,softmax} from './math.js';
import {lessons} from './lessons.js';
const $=s=>document.querySelector(s),C={q:'#ffcc72',k:'#6ddbd5',v:'#ba9af7',a:'#ff8d8d',white:'#e8eef8',muted:'#758ba3'};
const defaults={query:3,head:0,pos:1,mask:true,temp:1,gain:1,qx:2,qy:2,enabled:[true,true,true],context:0,eiffel:true,miniature:false,contextSize:32,layers:96,depth:1};
let s={...defaults,enabled:[...defaults.enabled]},chapter=0,progress=1,playing=false,model,mix,root,labels=[],pickables=[],qHandle=null,frames=0,dragging=false;
let renderer,scene=new T.Scene(),camera=new T.PerspectiveCamera(40,1,.1,150),orbit;
try{renderer=new T.WebGLRenderer({canvas:$('#canvas'),antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=T.SRGBColorSpace;orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.enablePan=false;orbit.minDistance=5;orbit.maxDistance=35;scene.add(new T.AmbientLight('#d5e6ff',2));const light=new T.DirectionalLight('#d9eaff',3);light.position.set(2,7,6);scene.add(light);}catch(e){$('#fallback').hidden=false}
const vec=a=>new T.Vector3(...a),f=x=>Number.isFinite(x)?x.toFixed(3):'−∞',fmt=a=>'['+a.map(f).join(', ')+']';
function clear(){if(root){root.traverse(o=>{o.geometry?.dispose();for(const m of [o.material].flat())m?.dispose()});scene.remove(root)}root=new T.Group();scene.add(root);labels=[];pickables=[];qHandle=null;$('#labels').replaceChildren()}
function label(text,pos,color=C.white,major=false){const el=document.createElement('span');el.className='label'+(major?' major':'');el.textContent=text;el.style.color=color;$('#labels').append(el);labels.push({el,pos:vec(pos)});}
function line(a,b,color=C.muted,opacity=.4){root.add(new T.Line(new T.BufferGeometry().setFromPoints([vec(a),vec(b)]),new T.LineBasicMaterial({color,transparent:true,opacity})))}
function box(pos,size,color,opacity=.8){const b=new T.Mesh(new T.BoxGeometry(...size),new T.MeshStandardMaterial({color,transparent:true,opacity,roughness:.5}));b.position.copy(vec(pos));root.add(b);return b}
function arrow(a,b,color,width=.035){const d=vec(b).sub(vec(a)),len=d.length();if(len<1e-7)return;const g=new T.Group();g.position.copy(vec(a));g.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d.normalize());const mat=new T.MeshBasicMaterial({color}),tip=Math.min(.2,len*.3);const shaft=new T.Mesh(new T.CylinderGeometry(width,width,Math.max(.001,len-tip),10),mat);shaft.position.y=(len-tip)/2;const head=new T.Mesh(new T.ConeGeometry(width*3,tip,12),mat);head.position.y=len-tip/2;g.add(shaft,head);root.add(g);return g}
function ball(pos,color,size=.11){const b=new T.Mesh(new T.SphereGeometry(size,16,12),new T.MeshBasicMaterial({color}));b.position.copy(vec(pos));root.add(b);return b}
function grid(){const g=new T.GridHelper(14,28,'#345064','#1b3040');g.position.y=-2;g.material.transparent=true;g.material.opacity=.4;root.add(g)}
function vector(a,pos,color,title){const x=pos[0],y=pos[1],z=pos[2];a.forEach((n,i)=>{box([x,y+(a.length-1)/4-i*.5,z],[.85,.4,.18],n<0?C.a:color,.2+Math.min(.7,Math.abs(n)*.3));label(n.toFixed(2),[x,y+(a.length-1)/4-i*.5,z+.15],color)});label(title,[x,y+a.length/4+.55,z],color)}
function home(){if(!renderer)return;const name=lessons[chapter].scene;camera.position.set(...(['pattern','mask'].includes(name)?[8,10,11]:name==='dot'?[0,0,14]:['values','context','tower','multi'].includes(name)?[3,2.5,9]:[6,4,14]));if(innerWidth<760)camera.position.multiplyScalar(1.2);orbit.target.set(0,0,0);camera.lookAt(orbit.target);orbit.update()}
function compute(){model=trace({...s,mask:chapter===6?false:s.mask});mix=multi(s)}
function contextScene(){grid();const start=[0,0,1.5],choices=[[2,1,1.5],[-2,1.7,1.5],[.2,-1.4,1.5]],names=['animal','amount of substance','skin lesion'];arrow([0,0,0],start,C.white);label('same “mole” embedding',[-1,-.5,1.5]);choices.forEach((p,i)=>{ball(p,i===s.context?C.a:C.muted,.09);label(names[i],p.map((x,j)=>x+(j===1?.4:0)),i===s.context?C.a:C.muted)});const end=start.map((x,i)=>x+(choices[s.context][i]-x)*progress);arrow(start,end,C.k);arrow([0,0,0],end,C.a);label(['American shrew mole','one mole of carbon dioxide','biopsy of the mole'][s.context],[0,3,0],C.k,true)}
function towerScene(){grid();const base=[0,2.2,0],after=[s.eiffel?2:0,2.2,0],end=[after[0],s.miniature?.55:2.2,s.miniature?1:0];arrow([0,0,0],base,C.white);arrow(base,after,C.k);arrow(after,after.map((x,i)=>x+(end[i]-x)*progress),C.v);arrow([0,0,0],end,C.a);label('generic tower',[-1.1,2.6,0]);label('identity →',[3,-.7,0],C.k);label('size ↑',[-1,3,0],C.muted);label((s.miniature?'miniature ':'')+(s.eiffel?'Eiffel ':'')+'tower',[0,-1.2,1],C.a,true);}
function tokensScene(){grid();words.forEach((w,i)=>{const x=(i-3.5)*1.2,z=i%2*.3;vector(model.X[i],[x,0,z],i===s.query?C.q:C.k,w);const b=box([x,-1.65,z],[1,.12,.6],i===s.query?C.q:C.muted,.3);b.userData={query:i};pickables.push(b)});label('descriptor 1 / descriptor 2 / noun / position',[0,2.3,0],C.muted)}
function projectionScene(){grid();vector(model.X[s.query],[-4,0,0],C.white,words[s.query]);[['Q',model.Q,C.q,2],['K',model.K,C.k,0],['V',model.V,C.v,-2]].forEach(([name,values,col,y],i)=>{arrow([-3.4,0,0],[0,y,0],col);box([0,y,0],[1.6,.85,.4],col,.15);label('W'+name,[0,y,.3],col,true);arrow([1,y,0],[2.8,y,0],col);if(progress>=i/3)vector(values[s.query],[3.5,y,0],col,name+' (2D)')})}
function dotScene(){for(let i=-4;i<=4;i++){line([i,-4,0],[i,4,0],C.muted,.2);line([-4,i,0],[4,i,0],C.muted,.2)}arrow([-4,0,0],[4,0,0],C.muted,.012);arrow([0,-4,0],[0,4,0],C.muted,.012);[1,2,6].forEach((j,n)=>{const k=model.K[j];arrow([0,0,0],[...k,0],C.k,.024);label('k: '+words[j],[k[0]+.35,k[1]+.3+n*.1,0],C.k)});const q=model.Q[s.query];arrow([0,0,.06],[q[0],q[1],.06],C.q,.045);qHandle=ball([q[0],q[1],.06],C.q,.16);label('drag Q',[q[0],q[1]+.5,.1],C.q,true);label('same plane; orbit to inspect',[0,-3.3,0],C.muted)}
function patternScene(){const step=.85;for(let i=0;i<8;i++){label(words[i],[-4.05,.1,(i-3.5)*step],i===s.query?C.q:C.muted);label(words[i],[(i-3.5)*step,.1,3.8],C.k);for(let j=0;j<8;j++){const x=(j-3.5)*step,z=(i-3.5)*step,w=model.A[i][j],val=chapter===5?model.S[i][j]:w;box([x,-.04,z],[.77,.04,.77],i===s.query?C.q:C.k,.12);const h=chapter===5?Math.max(-1.2,Math.min(2.5,val*.55))*progress:w*3*progress,b=box([x,h/2,z],[.5,Math.max(.025,Math.abs(h)),.5],i===s.query?C.q:C.k,w===0&&chapter!==5?.08:.8);b.userData={query:i,key:j};pickables.push(b)}}label('source Keys →',[0,.1,4.65],C.k);label('receiving Queries',[-3.5,2,-3],C.q);}
function softmaxScene(){const row=model.A[s.query];words.forEach((w,j)=>{const x=(j-3.5)*1.1,h=row[j]*5*progress;box([x,h/2-1.3,0],[.7,Math.max(.02,h),.7],C.k);label(w,[x,-1.75,0],C.muted);label((row[j]*100).toFixed(1)+'%',[x,h-1.0,0],C.k)});label('Σ weights = '+row.reduce((a,b)=>a+b,0).toFixed(6),[0,3,0],C.q,true)}
function valuesScene(){grid();const scale=2.8,origin=[-1.2,-.8,-1],base=model.X[s.query].slice(0,3).map((x,i)=>origin[i]+x*scale);arrow(origin,base,C.white);label('original e',[-2,0,1],C.white);let current=[...base];model.A[s.query].forEach((w,j)=>{const part=model.V[j].map(x=>x*w);const d=[part[0]*scale,part[1]*scale,0],t=Math.max(0,Math.min(1,progress*8-j)),end=current.map((x,i)=>x+d[i]*t);arrow(current,end,[C.muted,C.v,C.k,C.q][j%4],.03);if(w>.1)label(words[j]+' × '+w.toFixed(2),[end[0]+.2,end[1]+.4+(j%2)*.3,end[2]],j===1?C.v:C.k);current=end});arrow(origin,current,C.a,.025);ball(current,C.a);label('e′ first 3 coordinates',[0,3.1,0],C.a,true)}
function lowrankScene(){grid();vector(model.X[s.query],[-4,0,0],C.white,'input (4)');vector(model.V[s.query],[0,0,0],C.v,'value (2)');vector(mul([model.V[s.query]],model.UP)[0],[4,0,0],C.a,'update (4)');arrow([-3.3,0,0],[-.9,0,0],C.v);arrow([.9,0,0],[3.3,0,0],C.a);label('WV: 4 × 2',[-2,1.8,0],C.v);label('Wup: 2 × 4',[2,1.8,0],C.a);label('rank(WV Wup) ≤ 2',[0,-2,0],C.q,true)}
function crossScene(){grid();const data=cross(s);['le','chat','dort'].forEach((w,j)=>{const p=[(j-1)*3,2,0];box(p,[1,.55,.5],C.k);label(w,[p[0],2.5,0],C.k);['the','cat'].forEach((q,i)=>{const end=[(i-.5)*3,-1.5,1],weight=data.A[i][j];line(p,end,i?C.v:C.q,.1+weight*.85);const bead=p.map((x,k)=>x+(end[k]-x)*progress);ball(bead,i?C.v:C.q,.04+weight*.12)})});['the','cat'].forEach((w,i)=>{const x=(i-.5)*3;box([x,-1.5,1],[1,.55,.5],C.q);label(w,[x,-2.1,1],C.q)});label('SOURCE: Keys + Values',[0,3.2,0],C.k);label('TARGET: Queries',[0,-2.8,1],C.q)}
function multiScene(){grid();let cur=[0,-1,0];const origin=[...cur],colors=[C.k,C.v,C.q];mix.heads.forEach((h,j)=>{const x=(j-1)*3;box([x,1.5,0],[2.1,1.1,.7],colors[j],s.enabled[j]?.5:.07);label('HEAD '+(j+1),[x,1.6,.5],s.enabled[j]?colors[j]:C.muted);if(s.enabled[j]){const d=h.delta[s.query].slice(0,3),end=cur.map((v,i)=>v+d[i]*2*progress);arrow(cur,end,colors[j]);cur=end;line([x,1,0],end,colors[j],.4)}});arrow(origin,cur,C.a,.025);label('sum of head updates',[0,-2,0],C.a,true);}
function scaleScene(){const n=Math.min(24,s.contextSize);for(let i=0;i<n;i++)for(let j=0;j<n;j++)box([(i-(n-1)/2)*.23,(j-(n-1)/2)*.23,0],[.18,.18,.08],C.k,.4);label(s.contextSize.toLocaleString()+'² = '+(s.contextSize*s.contextSize).toLocaleString()+' pairs',[0,3.5,0],C.q,true);label('display capped at 24 × 24 cells',[0,-3.5,0],C.muted)}
function stackScene(){grid();for(let i=0;i<6;i++){const x=(i-2.5)*1.6,y=i*.25-1,z=-i*.35;box([x,y,z],[1.1,1.4,.5],i<s.depth?C.k:C.muted,i<s.depth?.5:.1);label('A + MLP',[x,y+1,z],i<s.depth?C.k:C.muted);if(i<5)arrow([x+.6,y,z],[x+1,y+.25,z-.35],C.v,.02)}label('input vectors',[-3.6,-2,0],C.white);label('last vector → logits',[3,2.4,-1],C.a);label('schematic blocks • not a simulated forward pass',[0,3.3,0],C.muted)}
const builders={context:contextScene,tower:towerScene,tokens:tokensScene,projection:projectionScene,dot:dotScene,pattern:patternScene,softmax:softmaxScene,mask:patternScene,values:valuesScene,lowrank:lowrankScene,cross:crossScene,multi:multiScene,scale:scaleScene,stack:stackScene};
function build(){clear();builders[lessons[chapter].scene]();}
const table=(title,rows,headers)=>'<h4>'+title+'</h4><div class="table-wrap"><table>'+(headers?'<tr>'+headers.map(h=>'<th>'+h+'</th>').join('')+'</tr>':'')+rows.map(r=>'<tr>'+r.map(v=>'<td>'+(typeof v==='number'?f(v):v)+'</td>').join('')+'</tr>').join('')+'</table></div>';
const metrics=items=>'<div class="metrics">'+items.map(([name,val])=>'<div class="metric"><small>'+name+'</small><strong>'+val+'</strong></div>').join('')+'</div>';
function numerical(){const i=s.query,row=model.A[i],raw=trace({...s,mask:false}),max=Math.max(...model.L[i]);let html='';
 if(chapter<=1){html=metrics([['Illustration','3D'],['Token lookup','unchanged'],['Context','changed']]);}
 else if(chapter===2)html=table('Input = content + position',model.X.map((r,j)=>[words[j],...r]),['token','descriptor 1','descriptor 2','noun','position']);
 else if(chapter===3)html=table('Selected token: '+words[i],[['x',...model.X[i]],['q',...model.Q[i]],['k',...model.K[i]],['v',...model.V[i]]]);
 else if(chapter===4)html=table('Live dot-product arithmetic',words.map((w,j)=>[w,model.Q[i].map((v,k)=>f(v)+' × '+f(model.K[j][k])).join(' + '),dot(model.Q[i],model.K[j]),model.S[i][j],row[j]]),['source','component products','dot product','÷ √2','attention']);
 else if(chapter===5||chapter===7){html='<h4>Click a pair — rows receive, columns supply</h4><div class="table-wrap"><table><tr><th>Q ↓ / K →</th>'+words.map(w=>'<th>'+w+'</th>').join('')+'</tr>'+words.map((w,r)=>'<tr><th>'+w+'</th>'+words.map((_,j)=>'<td class="'+(r===i?'selected':'')+'"><button data-pair="'+r+','+j+'" aria-label="'+w+' receiving from '+words[j]+'">'+f(chapter===5?model.S[r][j]:model.A[r][j])+'</button></td>').join('')+'</tr>').join('')+'</table></div>';html+=metrics([['Selected receiver',words[i]],['Weight sum',f(row.reduce((a,b)=>a+b,0))],['Future weight',f(row.slice(i+1).reduce((a,b)=>a+b,0))]]);}
 else if(chapter===6)html=table('Stable softmax for '+words[i],words.map((w,j)=>[w,model.S[i][j],model.L[i][j],Math.exp(model.L[i][j]-max),row[j]]),['source','score','score / τ','exp(logit − max)','normalized']);
 else if(chapter===8)html=table('Each source contributes to '+words[i],words.map((w,j)=>[w,row[j],fmt(model.V[j]),fmt(model.delta[i].map((_,k)=>row[j]*mul([model.V[j]],model.UP)[0][k]))]),['source','weight','Value (2D)','weighted lifted Value (4D)'])+table('Residual addition',[['original',...model.X[i]],['update',...model.delta[i]],['result',...model.Y[i]]]);
 else if(chapter===9)html=table('Down → up calculation',[['input',fmt(model.X[i])],['input × WV',fmt(model.V[i])],['Value × Wup',fmt(mul([model.V[i]],model.UP)[0])]])+table('WV (4×2)',model.WV)+table('Wup (2×4)',model.UP)+table('Effective map WV Wup (4×4)',mul(model.WV,model.UP));
 else if(chapter===10){const c=cross(s);html=table('Rectangular cross-attention (2×3)',c.A.map((r,i)=>[['the','cat'][i],...r]),['target query','le','chat','dort'])+table('Output = attention × source Values',c.O);}
 else if(chapter===11){const sum=[0,0,0,0];mix.heads.forEach((h,j)=>h.delta[i].forEach((x,k)=>sum[k]+=s.enabled[j]?x:0));html=table('Separate head contributions',mix.heads.map((h,j)=>['head '+(j+1)+(s.enabled[j]?' ON':' OFF'),fmt(h.O[i]),fmt(h.delta[i])]),['head','low-dimensional output','projected update (before switch)'])+table('Two equivalent implementations',[['sum of enabled head updates',fmt(sum)],['concat × WO',fmt(mix.delta[i])],['maximum difference',Math.max(...sum.map((v,j)=>Math.abs(v-mix.delta[i][j]))).toExponential(2)],['residual result',fmt(mix.Y[i])]]);}
 else if(chapter===12){const p=parameters(12288,96,128,s.layers);html=metrics([['Pairs per head',(s.contextSize**2).toLocaleString()],['Parameters per head',p.perHead.toLocaleString()],['Parameters per block',p.block.toLocaleString()],['Across '+s.layers+' layers',p.total.toLocaleString()]])+table('Value map parameter comparison',[['full d × d per head',p.fullValue.toLocaleString()],['factored 2 × d × dₖ per head',p.factoredValue.toLocaleString()]]);}
 else html=table('What each operation does',[['Attention','mixes across positions'],['MLP','transforms each position'],['Residual','adds an update to the existing stream'],['Normalization','stabilizes activations; details vary'],['Readout','maps the final position to vocabulary logits'],['Softmax + sampling','turns logits into a distribution; chooses a next token']]);
 $('#numbers').innerHTML=html;$('#numbers').querySelectorAll('[data-pair]').forEach(b=>b.onclick=()=>{const [r,j]=b.dataset.pair.split(',').map(Number);s.query=r;refresh();$('#insight').textContent=words[r]+' ← '+words[j]+': score '+f(model.S[r][j])+', logit '+f(model.L[r][j])+', weight '+f(model.A[r][j])+'. '+(s.mask&&j>r?'This source is in the future.':'This source is allowed.');renderControls()});
 $('#matrices').innerHTML=table('X (8×4)',model.X)+table('WQ (4×2)',model.WQ)+table('WK (4×2)',model.WK)+table('WV (4×2)',model.WV)+table('Q (after explicit Query intervention, if any)',model.Q)+table('K',model.K)+table('V (after fluffy gain, if any)',model.V)+table('Scores',model.S)+table('Logits (mask and temperature)',model.L)+table('Attention',model.A)+table('AV',model.O)+table('WO for three heads (6×4)',mix.WO);
}
const sliders={pos:['Position strength',0,2,.05],qx:['Query x offset + 2',-3,4,.05],qy:['Query y offset + 2',-3,4,.05],temp:['Attention temperature',.2,3,.05],gain:['fluffy Value gain',-2,2,.05],contextSize:['Context length',8,256,8],layers:['Number of distinct layers',1,96,1],depth:['Highlighted blocks',1,6,1]};
function renderControls(){let html='';for(const key of lessons[chapter].controls){if(sliders[key]){const [name,min,max,step]=sliders[key];html+='<label for="'+key+'">'+name+'<output id="out-'+key+'">'+s[key]+'</output></label><input id="'+key+'" data-slider="'+key+'" type="range" min="'+min+'" max="'+max+'" step="'+step+'" value="'+s[key]+'">';}
 else if(key==='tokens')html+='<label>Receiving / selected token</label><div class="tokens">'+words.map((w,i)=>'<button data-token="'+i+'" class="'+(s.query===i?'active':'')+'" aria-pressed="'+(s.query===i)+'">'+w+'</button>').join('')+'</div>';
 else if(key==='head')html+='<label for="head">Attention head</label><select id="head">'+['balanced descriptors','descriptor 1 bias','descriptor 2 bias'].map((t,i)=>'<option value="'+i+'" '+(s.head===i?'selected':'')+'>'+ (i+1)+' · '+t+'</option>').join('')+'</select>';
 else if(key==='heads')html+=[0,1,2].map(i=>'<label><span>Head '+(i+1)+'</span><input type="checkbox" data-head="'+i+'" '+(s.enabled[i]?'checked':'')+'></label>').join('');
 else if(key==='context')html+='<label for="context">Context for mole</label><select id="context">'+['American shrew mole','one mole of carbon dioxide','biopsy of the mole'].map((t,i)=>'<option value="'+i+'" '+(s.context===i?'selected':'')+'>'+t+'</option>').join('')+'</select>';
 else html+='<label><span>'+({mask:'Causal mask',eiffel:'Add Eiffel',miniature:'Add miniature'}[key])+'</span><input id="'+key+'" data-check="'+key+'" type="checkbox" '+(s[key]?'checked':'')+'></label>';
 }$('#controls').innerHTML=html;$('#controls').querySelectorAll('[data-slider]').forEach(el=>el.oninput=()=>{s[el.dataset.slider]=+el.value;$('#out-'+el.dataset.slider).textContent=el.value;refresh()});$('#controls').querySelectorAll('[data-token]').forEach(el=>el.onclick=()=>{s.query=+el.dataset.token;refresh();renderControls()});$('#controls').querySelectorAll('[data-check]').forEach(el=>el.onchange=()=>{s[el.dataset.check]=el.checked;refresh()});$('#controls').querySelectorAll('[data-head]').forEach(el=>el.onchange=()=>{s.enabled[+el.dataset.head]=el.checked;refresh()});for(const id of ['context','head'])if($('#'+id))$('#'+id).onchange=e=>{s[id]=+e.target.value;refresh()};}
function refresh(){compute();build();numerical();$('#insight').textContent=lessons[chapter].note;}
function go(i){chapter=Math.max(0,Math.min(lessons.length-1,i));s={...defaults,enabled:[true,true,true]};progress=1;playing=false;$('#progress').value=1;$('#progress-out').textContent='100%';$('#animate').textContent='Animate step';const c=lessons[chapter];$('#number').textContent='CHAPTER '+String(chapter+1).padStart(2,'0')+' / '+lessons.length;$('#title').textContent=c.title;$('#idea').textContent=c.idea;$('#explain').textContent=c.text;$('#formula').textContent=c.formula;$('#task').textContent=c.task;$('#answer').textContent=c.answer;$('#answer').hidden=true;$('#reveal').textContent='Reveal explanation';$('#source').href='https://www.youtube.com/watch?v=eMlx5fFNoYc&t='+c.time+'s';$('#position').textContent=(chapter+1)+' / '+lessons.length;$('#previous').disabled=chapter===0;$('#next').disabled=chapter===lessons.length-1;$('#chapters').querySelectorAll('button').forEach((b,j)=>{b.classList.toggle('active',j===chapter);b.setAttribute('aria-current',j===chapter?'step':'false')});renderControls();refresh();home();history.replaceState(null,'','#chapter-'+(chapter+1));}
$('#chapters').innerHTML=lessons.map((c,i)=>'<button><small>'+String(i+1).padStart(2,'0')+'</small>'+c.name+'</button>').join('');$('#chapters').querySelectorAll('button').forEach((b,i)=>b.onclick=()=>go(i));$('#previous').onclick=()=>go(chapter-1);$('#next').onclick=()=>go(chapter+1);$('#home').onclick=home;$('#reset').onclick=()=>go(chapter);$('#reveal').onclick=()=>{const a=$('#answer');a.hidden=!a.hidden;$('#reveal').textContent=a.hidden?'Reveal explanation':'Hide explanation'};$('#progress').oninput=e=>{playing=false;progress=+e.target.value;$('#animate').textContent='Animate step';$('#progress-out').textContent=Math.round(progress*100)+'%';build()};$('#animate').onclick=()=>{playing=!playing;if(playing&&progress>=1)progress=0;$('#animate').textContent=playing?'Pause':'Animate step'};
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON','A'].includes(e.target.tagName))return;if(e.code==='ArrowRight'){e.preventDefault();go(chapter+1)}if(e.code==='ArrowLeft'){e.preventDefault();go(chapter-1)}if(e.code==='Space'){e.preventDefault();$('#animate').click()}});
const ray=new T.Raycaster();function getRay(e){const r=$('#canvas').getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2),camera);return ray}
let down;
$('#canvas').addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY];if(chapter===4&&qHandle&&getRay(e).intersectObject(qHandle).length){dragging=true;orbit.enabled=false;$('#canvas').setPointerCapture(e.pointerId);e.stopImmediatePropagation()}},true);
$('#canvas').addEventListener('pointermove',e=>{if(!dragging)return;const p=new T.Vector3();getRay(e).ray.intersectPlane(new T.Plane(new T.Vector3(0,0,1),-.06),p);const base=trace({...s,qx:2,qy:2}).Q[s.query];s.qx=Math.max(-3,Math.min(4,p.x-base[0]+2));s.qy=Math.max(-3,Math.min(4,p.y-base[1]+2));refresh();for(const key of ['qx','qy']){$('#'+key).value=s[key];$('#out-'+key).textContent=s[key].toFixed(2)}});
function release(){dragging=false;if(orbit)orbit.enabled=true}
$('#canvas').addEventListener('pointercancel',release);$('#canvas').addEventListener('pointerup',e=>{if(dragging){release();return}if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5||!renderer)return;const hit=getRay(e).intersectObjects(pickables)[0];if(hit){s.query=hit.object.userData.query;refresh();renderControls()}});
let last=0;function tick(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(playing&&!document.hidden){progress=Math.min(1,progress+dt/5);$('#progress').value=progress;$('#progress-out').textContent=Math.round(progress*100)+'%';build();if(progress>=1){playing=false;$('#animate').textContent='Animate step'}}if(renderer){const r=$('#stage').getBoundingClientRect();if(renderer.domElement.width!==Math.floor(r.width*renderer.getPixelRatio())||renderer.domElement.height!==Math.floor(r.height*renderer.getPixelRatio()))renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();orbit.update();renderer.render(scene,camera);for(const {el,pos} of labels){const p=pos.clone().project(camera),x=(p.x+1)*r.width/2,y=(1-p.y)*r.height/2;el.style.display=p.z<1&&x>10&&x<r.width-10&&y>112&&y<r.height-85?'block':'none';el.style.left=x+'px';el.style.top=y+'px'}}frames++;requestAnimationFrame(tick)}
window.explorer={go,get state(){return {...s,chapter,progress,frames,webgl:renderer?!renderer.getContext().isContextLost():false,drawCalls:renderer?.info.render.calls??0}},trace:()=>structuredClone(model),multi:()=>structuredClone(mix),cross:()=>cross(s),get labels(){return labels.map(x=>({text:x.el.textContent,visible:x.el.style.display!=='none'}))},get queryScreen(){if(!qHandle)return null;const p=qHandle.position.clone().project(camera),r=$('#canvas').getBoundingClientRect();return {x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2}}};
go(Math.max(0,(parseInt(location.hash.replace('#chapter-',''))||1)-1));requestAnimationFrame(tick);
