import {singleHead} from './single-head.js';
import * as THREE from 'three';
import {OrbitControls} from '../vendor/OrbitControls.js';
import {words,trace,softmax,add,scale,parameterCounts} from '../math.js';
const $=s=>document.querySelector(s),host=$('#stage'),overlay=$('#labels');
import {encode,decode} from './tokenizer.js';
const inputData=await(await fetch('./gpt2-input.json')).json();
let inputText=inputData.cases[0].text,inputIds=encode(inputText),inputIndex=0,positionOn=false;
const data=await(await fetch('../embeddings.json')).json();
const colors={gray:'#aaaaaa',white:'#eeeeee',blue:'#58c4dd',yellow:'#ffff62',teal:'#5cd0b3',red:'#fc6255',pink:'#d147bd',green:'#83c167'};
const definitions=[
{id:'tokens',name:'1 · Text → embeddings',title:'From text to vectors, in one view',source:199,chapter:5,cue:'Read the sentence at the top, then click a token. Follow its yellow ID into the highlighted W_E column and the vector on the right. The whole path stays visible. Try bank bank bank, then add position: repeated IDs share the same token embedding, but position changes the input.',context:'Actual GPT-2 BPE and pretrained 768D embeddings. Top: token order; lower left: a vocabulary subset of W_E; lower right: vector components 0–2. ␠ marks a space. These three axes are displayed components, not the whole semantic space.'},
{id:'meaning',name:'2 · Embedding directions',title:'A meaningful direction in embedding space',source:915,chapter:5,cue:'Translate the yellow man→woman difference to the tip of king. Orbit to inspect the arrows: the endpoint is not exactly queen. Switch to the family pair to compare the same calculation.',context:'3D projection of the same real GloVe 50D data used by the source. Dot products and analogy residuals use all 50 dimensions. Camera and origin-relative layout are reconstructed for clarity.'},
{id:'queries',name:'3 · Where queries come from',title:'One query per token, per head',source:380,chapter:6,cue:'Slides 69–70: choose creature and inspect q = W_Q x. All tokens use the same W_Q within this head, but each has its own query. Eight tokens give eight queries, not one question for the entire sentence. Natural-language questions are analogies for learned numeric patterns.',context:'Exact calculations in a deliberately chosen 3D teaching head, not measured GPT weights. Inputs, Q/K/V and matrices are fully inspectable. GPT-2-small uses 64 dimensions per head; the source’s GPT-3 example uses 128.'},
{id:'single',name:'4 · Single-head attention',title:'Q/K → weights → values → updated vector',source:535,chapter:6,cue:'Slides 70–73: select creature receiving from blue. Read the dot product, divide by sqrt(3), mask, then softmax. Change the Q projection and watch weights and the final vector move. Change only V: the weights stay fixed, but the result changes. Animate the weighted values into a sum.',context:'One exact 3D teaching head: q=W_Q x, k=W_K x, v=W_V x; weights=softmax(mask(q·k/√3)); z=Σ weight×v; x′=x+W_O z. W_O is identity here. The source uses larger, illustrative vectors; these smaller numbers expose every arithmetic step.'},
{id:'heads',name:'5 · Multiple heads',title:'Separate heads, separate proposals',source:1245,chapter:6,cue:'Start with four heads and click planes to compare reading patterns. Then show 12 and 96. Distinct Q/K/V produce distinct updates, not copies of one table. Expand the stack and inspect it from the side.',context:'Each plane is one attention head with query × key axes; plane position separates heads. All 96 are selectable. Additional patterns are illustrative, not measured in trained GPT-3.'},
{id:'pipeline',name:'6 · Inside the Transformer',title:'Walk through the Transformer',source:315,chapter:5,cue:'After single-head and multi-head attention, start obliquely to show processing stages in depth. Each vertical bundle is one token. Expand the blocks to separate attention and MLP; compare cross-position attention lines with position-wise MLP processing.',context:'x: token position; y: displayed vector component; z: processing stage. This spatial architecture diagram is not a three-axis semantic space.'}
];
const state={view:'pipeline',token:3,source:2,bias:0,value:1,phase:'weights',mask:true,heads:4,head:0,family:false,progress:1,playing:false};
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor('#000');renderer.outputColorSpace=THREE.SRGBColorSpace;host.prepend(renderer.domElement);
const scene=new THREE.Scene();scene.add(new THREE.AmbientLight('#ffffff',1.2));const light=new THREE.DirectionalLight('#c2e5ff',2);light.position.set(4,8,10);scene.add(light);
const camera=new THREE.PerspectiveCamera(37,1,.1,300);const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.dampingFactor=.1;orbit.minDistance=3;orbit.maxDistance=100;
let root=new THREE.Group();scene.add(root);let labels=[],targets=[],animators=[],dirty=true,renderedView='',frames=0,last=0,modelTrace=trace({mask:true});const raycaster=new THREE.Raycaster();
const V=a=>new THREE.Vector3(...a);const lerp=(a,b,p)=>a.map((x,i)=>x+(b[i]-x)*p);const lerpScalar=(a,b,p)=>a+(b-a)*p;
function clear(){const geometry=new Set(),material=new Set();root.traverse(o=>{if(o.geometry)geometry.add(o.geometry);if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])material.add(m)});for(const g of geometry)g.dispose();for(const m of material){m.map?.dispose();m.dispose()}scene.remove(root);root=new THREE.Group();scene.add(root);overlay.replaceChildren();labels=[];targets=[];animators=[];}
function label(text,pos,color=colors.white,parent=root,{size=17,priority=1}={}){const anchor=new THREE.Object3D();anchor.position.copy(V(pos));parent.add(anchor);const el=document.createElement('span');el.className='label';el.textContent=text;el.style.color=color;el.style.fontSize=size+'px';const leader=document.createElement('span');leader.className='leader';leader.style.background=color;overlay.append(leader,el);labels.push({el,leader,anchor,priority});return anchor;}
function lines(points,color=colors.gray,opacity=.45,parent=root){const geo=new THREE.BufferGeometry().setFromPoints(points.map(V));const l=new THREE.LineSegments(geo,new THREE.LineBasicMaterial({color,transparent:true,opacity}));parent.add(l);return l;}
function segment(a,b,color=colors.gray,opacity=.6,parent=root){return lines([a,b],color,opacity,parent)}
function curve(a,b,bend=1,color=colors.teal,opacity=.5,parent=root){const va=V(a),vb=V(b),mid=va.clone().lerp(vb,.5);mid.y+=bend;const c=new THREE.QuadraticBezierCurve3(va,mid,vb);const geo=new THREE.BufferGeometry().setFromPoints(c.getPoints(24));const mesh=new THREE.Line(geo,new THREE.LineBasicMaterial({color,transparent:true,opacity}));parent.add(mesh);return mesh;}
function arrow(a,b,color=colors.white,parent=root,width=.035){const delta=V(b).sub(V(a));const length=delta.length();const g=new THREE.Group();g.position.copy(V(a));if(length>.00001){const material=new THREE.MeshBasicMaterial({color});const body=new THREE.Mesh(new THREE.CylinderGeometry(width,width,Math.max(.01,length-.15),8),material);body.position.y=(length-.15)/2;const tip=new THREE.Mesh(new THREE.ConeGeometry(width*3,.2,12),material);tip.position.y=length-.1;g.add(body,tip);g.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());}parent.add(g);return g;}
function plane(w,h,pos,color=colors.gray,parent=root,opacity=.08){const mesh=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({color,transparent:true,opacity,side:THREE.DoubleSide,depthWrite:false}));mesh.position.copy(V(pos));parent.add(mesh);const edge=new THREE.LineSegments(new THREE.EdgesGeometry(mesh.geometry),new THREE.LineBasicMaterial({color,transparent:true,opacity:.55}));mesh.add(edge);return mesh;}
function axes(size=4,parent=root){for(let d=0;d<3;d++){let a=[0,0,0],b=[0,0,0];a[d]=-size;b[d]=size;segment(a,b,'#888',.7,parent)}const p=[];for(let i=-size;i<=size;i++){p.push([i,0,-size],[i,0,size],[-size,0,i],[size,0,i]);}lines(p,'#3c5a64',.35,parent)}
function tokenLabel(word,pos,action,color=colors.white,parent=root,size=.9){const g=new THREE.Group();g.position.copy(V(pos));parent.add(g);const mesh=plane(size,.4,[0,0,0],color,g,.13);mesh.userData.action=action;targets.push(mesh);label(word,[0,.02,.06],color,g,{size:16});return g;}
function vectorColumns(parent,values,{w=11,h=3.2,highlight=state.token,color=colors.gray}={}){const rows=values[0].length,cols=values.length;const inst=new THREE.InstancedMesh(new THREE.BoxGeometry(.095,.095,.06),new THREE.MeshBasicMaterial({color:'#fff'}),rows*cols);const m=new THREE.Matrix4(),c=new THREE.Color();values.forEach((v,j)=>{const x=(j-(cols-1)/2)*w/(cols-1);for(let i=0;i<rows;i++){const val=v[i];m.makeTranslation(x,1.3-i*h/(rows-1),.04);m.scale(new THREE.Vector3(1+Math.min(2,Math.abs(val))*.5,1,1));inst.setMatrixAt(j*rows+i,m);c.set(j===highlight?colors.yellow:color).multiplyScalar(.35+Math.min(1,Math.abs(val)/4)*.65);inst.setColorAt(j*rows+i,c);}const yy=1.6;lines([[x-.24,yy,0],[x-.34,yy,0],[x-.34,yy,0],[x-.34,yy-h-.45,0],[x-.34,yy-h-.45,0],[x-.24,yy-h-.45,0],[x+.24,yy,0],[x+.34,yy,0],[x+.34,yy,0],[x+.34,yy-h-.45,0],[x+.34,yy-h-.45,0],[x+.24,yy-h-.45,0]],j===highlight?colors.yellow:colors.gray,.7,parent)});parent.add(inst);return inst;}
function pattern(head,mask=state.mask){if(head<4)return trace({mask,bias:state.bias,value:state.value,head}).attention;const score=Array.from({length:8},(_,i)=>Array.from({length:8},(_,j)=>mask&&i>j?-Infinity:3*Math.sin((head+1)*.77+i*1.97+j*2.31)+2*Math.cos(head+i*j*.5)));const result=Array.from({length:8},()=>Array(8));for(let j=0;j<8;j++){const p=softmax(score.map(r=>r[j]));p.forEach((v,i)=>result[i][j]=v)}return result;}
function attentionPlane(a,size=8,parent=root,selected=-1){const mesh=plane(size,size,[0,0,0],colors.gray,parent,.08);const cw=size/8;const ps=[];for(let i=0;i<=8;i++)ps.push([-size/2+i*cw,-size/2,.005],[-size/2+i*cw,size/2,.005],[-size/2,-size/2+i*cw,.005],[size/2,-size/2+i*cw,.005]);lines(ps,'#555',.5,parent);const dots=new THREE.InstancedMesh(new THREE.CircleGeometry(.4,16),new THREE.MeshBasicMaterial({color:'#ddd',side:THREE.DoubleSide}),64);const m=new THREE.Matrix4(),c=new THREE.Color();for(let i=0;i<8;i++)for(let j=0;j<8;j++){m.makeScale(Math.max(.025,Math.sqrt(a[i][j]))*cw,Math.max(.025,Math.sqrt(a[i][j]))*cw,1);m.setPosition((j-3.5)*cw,(3.5-i)*cw,.03);dots.setMatrixAt(i*8+j,m);c.set(j===selected?colors.yellow:'#aaa');dots.setColorAt(i*8+j,c);}parent.add(dots);return mesh;}
function buildPipeline(){const tokenX=i=>(i-3.5)*1.48;for(let i=0;i<8;i++)tokenLabel(words[i],[tokenX(i),3.8,2.2],()=>chooseToken(i),i===state.token?colors.yellow:i===1||i===2?colors.blue:colors.gray,root,words[i].length*.13+.3);
const layers=['Embedding','Attention','MLP','Attention','MLP','Unembedding'];layers.forEach((name,l)=>{const g=new THREE.Group();root.add(g);g.position.z=-l*2.8;animators.push(p=>g.position.z=-l*lerpScalar(.65,2.8,p));plane(12.6,5.2,[0,0,0],name==='Attention'?colors.teal:name==='MLP'?'#a1a1d1':colors.gray,g,.07);label(name,[-6.4,2.6,.02],name==='Attention'?colors.teal:name==='MLP'?'#b4b4ee':colors.white,g,{size:20});const vectors=words.map((word,j)=>Array.from({length:10},(_,d)=>l===0?(data.vectors[word]?.[d]||0):Math.sin(j*4+d*1.7+l)*3+modelTrace.delta[j][d%3]));vectorColumns(g,vectors);if(name==='Attention'){for(let i=0;i<8;i++){const w=modelTrace.attention[i][state.token];if(w>.002)curve([tokenX(i),1.7,.25],[tokenX(state.token),-2.1,.25],1.2,i===2?colors.blue:colors.teal,w*.9+.1,g)}}if(name==='MLP'){for(let j=0;j<8;j++){segment([tokenX(j),1.7,.2],[tokenX(j),-2.1,.2],'#b4b4ee',j===state.token?.8:.15,g)}}});for(let j=0;j<8;j++)arrow([tokenX(j),3.45,2],[tokenX(j),1.85,.15],j===state.token?colors.yellow:colors.gray,root,.014);
label('Same token positions, richer vectors',[0,-3,-7],colors.gray,root,{size:17});const out=new THREE.Group();root.add(out);animators.push(p=>out.position.z=-5*lerpScalar(.65,2.8,p));arrow([tokenX(7),-.3,0],[7.3,-.3,0],colors.yellow,out,.03);label('P(next token)',[7.4,-.3,0],colors.yellow,out);}
function chooseToken(i){state.token=i;dirty=true;syncControls()}
function buildQK(){const g=new THREE.Group();g.rotation.x=-Math.PI/2;root.add(g);attentionPlane(modelTrace.attention,8,g,state.token);const cw=1;for(let j=0;j<8;j++){const x=j-3.5;tokenLabel(words[j],[x,2.3,-5.2],()=>chooseToken(j),j===state.token?colors.yellow:colors.gray,root,words[j].length*.13+.3);arrow([x,2,-5.2],[x,.15,-4.1],colors.yellow,root,.015)}for(let i=0;i<8;i++){const z=i-3.5;tokenLabel(words[i],[-6,.5,z],()=>{state.source=i;dirty=true},i===state.source?colors.teal:colors.gray,root,words[i].length*.13+.3);arrow([-5.4,.2,z],[-4.15,.1,z],colors.teal,root,.015)}label('Queries / receivers',[0,3.1,-5.2],colors.yellow);label('Keys / sources',[-6.1,1.4,0],colors.teal);
for(let i=0;i<8;i++)for(let j=0;j<8;j++){const a=modelTrace.attention[i][j],x=j-3.5,z=i-3.5,raw=modelTrace.logits[i][j];let height=state.phase==='scores'?(raw===-Infinity?0:raw/32):a*4;const color=j===state.token?(i===2?colors.blue:i===1?colors.teal:colors.yellow):'#777';if(Math.abs(height)>.04){const ar=arrow([x,.04,z],[x,height,z],color,root,j===state.token?.055:.018);animators.push(p=>ar.scale.y=Math.max(.001,p));}const hit=new THREE.Mesh(new THREE.BoxGeometry(.9,.12,.9),new THREE.MeshBasicMaterial({visible:false}));hit.position.set(x,0,z);hit.userData.action=()=>{state.token=j;state.source=i;dirty=true;syncControls()};root.add(hit);targets.push(hit);if(j===state.token&&(a>.02||i===state.source)){const num=state.phase==='scores'?(raw===-Infinity?'−∞':raw.toFixed(2)):a.toFixed(3);label(`${words[i]}: ${num}`,[x+.08,height+.23,z],color,root,{size:17,priority:2})}}
const selX=state.token-3.5;const highlight=new THREE.Mesh(new THREE.BoxGeometry(.96,.025,8),new THREE.MeshBasicMaterial({color:colors.yellow,transparent:true,opacity:.1,depthWrite:false}));highlight.position.set(selX,.05,0);root.add(highlight);label(state.phase==='scores'?'Height = q · k':'Height = attention weight',[4.8,3.1,2],colors.white);}
function buildValues(){axes(4);const j=state.token,base=modelTrace.base[j],origin=[0,0,0];arrow(origin,base,colors.yellow,root,.045);label('E('+words[j]+')',base,colors.yellow,root);let current=[...base];let number=0;for(let i=0;i<8;i++){const weight=modelTrace.attention[i][j];if(weight<.015)continue;const weighted=scale(modelTrace.values[i],weight);if(Math.hypot(...weighted)<.005)continue;const color=i===2?colors.blue:i===1?colors.teal:colors.red;const start=[...current],end=add(start,weighted),g=new THREE.Group();root.add(g);arrow([0,0,0],weighted,color,g,.04);label(`${weight.toFixed(2)} v_${words[i]}`,weighted,color,g,{size:18});const exploded=[-4+number*3.6,2.2,-2.5+number*.35];animators.push(p=>g.position.copy(V(lerp(exploded,start,p))));current=end;number++;}
const result=arrow(origin,current,colors.white,root,.04);animators.push(p=>result.visible=p>.75);const name=label('E′ = E + ΔE',current,colors.white,root,{size:20});animators.push(p=>name.visible=p>.75);label('Separate contributions → head-to-tail sum',[-1,3.5,-1],colors.gray,root,{size:18});label('x',[4.1,0,0],colors.gray);label('y',[0,4.1,0],colors.gray);label('z',[0,0,4.1],colors.gray);}
function buildHeads(){const n=state.heads;const all=n===96;const cols=all?4:n===12?3:2,rows=Math.ceil(n/cols),size=all?1.6:3.2;const gap=all?2.05:4.1;for(let h=0;h<n;h++){const g=new THREE.Group();root.add(g);const layer=all?Math.floor(h/24):0;const local=all?h%24:h,rr=Math.floor(local/cols),cc=local%cols;const target=[(cc-(cols-1)/2)*gap,((all?6:rows)-1)/2*gap-rr*gap,-layer*1.6];const compact=[0,0,-h*.085];animators.push(p=>g.position.copy(V(lerp(compact,target,p))));const a=pattern(h);const hit=attentionPlane(a,size,g,h===state.head?state.token:-1);hit.userData.action=()=>{state.head=h;dirty=true;syncControls()};targets.push(hit);if(h===state.head||n<=12)label('Head '+(h+1),[-size*.5,size*.58,0],h===state.head?colors.yellow:colors.gray,g,{size:all?17:18});if(h===state.head){const edge=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.PlaneGeometry(size+.12,size+.12)),new THREE.LineBasicMaterial({color:colors.yellow}));g.add(edge);}}
label(n+' distinct attention patterns',[0,all?7.3:(rows*gap)/2+.6,0],colors.white,root,{size:20});if(!all)label('Each head proposes ΔE; add the proposals.',[0,-rows*gap/2-.6,0],colors.teal,root,{size:18});}
function buildMeaning(){axes(5);const a=state.family?'uncle':'king',b='woman',c='man',d=state.family?'aunt':'queen';const xyz=(w,shift)=>add(data.xyz[w].map((v,i)=>i<2?-v*(i===1?2:1):v),shift);const va=xyz(a,[-4,-1,-1]),vb=xyz(b,[0,-1,0]),vc=xyz(c,[0,-1,0]),vd=xyz(d,[-4,-1,-1]),diff=add(vb,scale(vc,-1));arrow([0,0,0],va,colors.blue);arrow([0,0,0],vb,colors.red);arrow([0,0,0],vc,colors.gray);arrow(vc,vb,colors.yellow);label(a,va,colors.blue);label(b,vb,colors.red);label(c,vc,colors.gray);const translated=arrow([0,0,0],diff,colors.yellow);animators.push(p=>translated.position.copy(V(lerp(vc,va,p))));const actual=arrow([0,0,0],vd,colors.pink);animators.push(p=>actual.visible=p>.7);const mark=label(d+' (actual)',vd,colors.pink);animators.push(p=>mark.visible=p>.7);label(`${a} + (woman − man) ≈ ${d}`,[0,6.2,0],colors.white,root,{size:21});segment(add(va,diff),vd,colors.gray,.5);}
function piece(id){return decode([id]).replaceAll(' ','␠').replaceAll('\n','↵')}
function selectInput(i){inputIndex=i;dirty=true;controls()}
function buildInput(){
 const n=inputIds.length,spacing=Math.min(1.55,14/Math.max(1,n-1)),tokenX=i=>(i-(n-1)/2)*spacing;
 const id=inputIds[inputIndex],v=inputData.wte[id];
 label('“'+inputText+'”',[0,5,0],colors.white,root,{size:19});
 for(let i=0;i<n;i++){
  const x=tokenX(i),y=i%2?3.1:3.9,c=i===inputIndex?colors.yellow:colors.blue;
  tokenLabel(piece(inputIds[i]),[x,y,0],()=>selectInput(i),c,root,Math.min(1.4,spacing*.85));
  label(String(inputIds[i]),[x,y-1.1,0],c,root,{size:15});
  segment([x,y-.22,0],[x,y-.85,0],c,.7);
 }
 const allIds=[...new Set(inputIds)],selectedCol=allIds.indexOf(id),offset=Math.max(0,Math.min(selectedCol-3,allIds.length-7)),ids=allIds.slice(offset,offset+7),k=ids.indexOf(id),dx=1.25;
 label('W_E · ID selects a learned column',[-3.25,1,0],colors.blue,root,{size:16});
 for(let j=0;j<ids.length;j++){
  const x=-7+j*dx,c=ids[j]===id?colors.yellow:colors.gray;
  tokenLabel(String(ids[j]),[x,.35,0],()=>selectInput(inputIds.indexOf(ids[j])),c,root,.95);
  const vec=inputData.wte[ids[j]],canvas=document.createElement('canvas');canvas.width=180;canvas.height=700;const ctx=canvas.getContext('2d');ctx.fillStyle=c;ctx.font='30px monospace';ctx.textAlign='center';
  for(let r=0;r<8;r++)ctx.fillText(vec?vec[r].toFixed(3):'—',90,65+r*77);
  ctx.strokeStyle=c;ctx.lineWidth=3;ctx.strokeRect(4,4,172,684);
  const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;
  const column=new THREE.Mesh(new THREE.PlaneGeometry(1.03,3.4),new THREE.MeshBasicMaterial({map:texture,transparent:true,side:THREE.DoubleSide}));column.position.set(x,-1.75,0);root.add(column);
 }
 const start=[tokenX(inputIndex),(inputIndex%2?3.1:3.9)-1.35,.1],lookup=[-7+k*dx,.65,.1],origin=[4,-2,0];
 curve(start,lookup,.35,colors.yellow,.9);
 label('768 numbers per token · 8 shown',[-3.25,-3.9,0],colors.gray,root,{size:13});
 if(!v){label('Vector not bundled for this ID',[4,-1,0],colors.yellow,root,{size:15});label('Choose a preset for real weights',[4,-2,0],colors.gray,root,{size:13});return;}
 const pos=inputData.wpe[inputIndex],end=v.slice(0,3).map((x,i)=>origin[i]+x*12),sum=v.slice(0,3).map((x,i)=>origin[i]+(x+(positionOn?pos[i]:0))*12);
 label('Selected token → vector',[4,1,0],colors.yellow,root,{size:16});
 arrow(origin,end,colors.blue);label('e(token)',end,colors.blue,root,{size:16});
 if(positionOn){arrow(end,sum,colors.red);arrow(origin,sum,colors.yellow);label('x = e + p',sum,colors.yellow);}
 for(let axis=0;axis<3;axis++){const to=[...origin];to[axis]+=2.2;arrow(origin,to,colors.gray,root,.012);label('component '+axis,to,colors.gray,root,{size:11});}
 const exit=[-7+k*dx,-3.5,0];curve(exit,origin,-.4,colors.yellow,.7);
 label(positionOn?'x = W_E[:, ID] + W_P[:, position]':'e(token) = W_E[:, ID]',[4,-4.5,0],colors.yellow,root,{size:16});
 const dot=new THREE.Mesh(new THREE.SphereGeometry(.095,16,12),new THREE.MeshBasicMaterial({color:colors.yellow}));root.add(dot);
 animators.push(p=>{const points=[start,lookup,exit,end],part=Math.min(2,Math.floor(p*3));dot.position.copy(V(lerp(points[part],points[part+1],Math.min(1,p*3-part))));});
}

function inputControls(){
 const host=$('#controls');host.replaceChildren();
 const title=document.createElement('label');title.textContent='Choose an example';host.append(title);
 const select=document.createElement('select');select.id='input-example';select.style.width='100%';
 inputData.cases.forEach(c=>{const o=document.createElement('option');o.textContent=c.text;o.value=c.text;select.append(o)});select.value=inputText;host.append(select);
 function change(text){const ids=encode(text);if(ids.length>16||!ids.length){note.textContent='Use between 1 and 16 tokens for this spatial view.';return}inputText=text;inputIds=ids;inputIndex=0;dirty=true;controls();}
 select.onchange=()=>change(select.value);
 if(state.view==='tokens'){
 const custom=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Try your own text';custom.append(summary);host.append(custom);
 const label=document.createElement('label');label.textContent='Or enter text (up to 16 tokens)';custom.append(label);
 const field=document.createElement('textarea');field.className='input-text';field.id='input-text';field.value=inputText;field.maxLength=300;custom.append(field);
 const b=document.createElement('button');b.id='tokenize';b.textContent='Tokenize';b.onclick=()=>change(field.value);custom.append(b);
 }
 const note=document.createElement('p');note.className='input-note';note.textContent=state.view==='tokens'?'Click a token to follow its ID into the learned vector. ␠ marks a space. Presets include real GPT-2 weights.':'Click a token position below. Presets include real 768D GPT-2 embedding vectors. Custom tokens outside the bundled subset have no vector here; no invented fallback is used.';host.append(note);
 const buttons=document.createElement('div');buttons.className='buttons';inputIds.forEach((id,i)=>{const b=document.createElement('button');b.textContent=i+': '+piece(id);b.classList.toggle('active',i===inputIndex);b.dataset.inputIndex=i;b.onclick=()=>selectInput(i);buttons.append(b)});host.append(buttons);
 if(state.view==='tokens'){const b=document.createElement('button');b.id='add-position';b.textContent=positionOn?'Position added: ON':'Add position: OFF';b.onclick=()=>{positionOn=!positionOn;dirty=true;controls()};host.append(b);}
 const next=document.createElement('a');next.className='input-next';next.href='#pipeline';next.textContent='Next: inside the Transformer →';host.append(next);
}
function inputReadout(){
 const id=inputIds[inputIndex],v=inputData.wte[id],p=inputData.wpe[inputIndex];$('#selected').textContent=piece(id)+' · ID '+id;
 const out=$('#numbers');out.replaceChildren();const pre=document.createElement('div');
 pre.textContent=`${inputIds.length} tokens · round-trip: ${decode(inputIds)===inputText?'exact':'FAILED'}\n`+(v?`Position ${inputIndex} · 768 dimensions\nFirst 8 values (${positionOn?'e + p':'e'}):\n`+v.slice(0,8).map((x,i)=>`[${i}] ${positionOn?x.toFixed(5)+' + '+p[i].toFixed(5)+' = ':''}${(x+(positionOn?p[i]:0)).toFixed(5)}`).join('\n'):'Pretrained vector not bundled. Choose a preset.');
 pre.style.whiteSpace='pre-wrap';out.append(pre);
 if(v){const d=document.createElement('details'),s=document.createElement('summary'),a=document.createElement('pre');s.textContent='Inspect all 768 components';a.className='vector-numbers';a.textContent=v.map((x,i)=>`[${i}] ${(x+(positionOn?p[i]:0)).toFixed(7)}`).join('\n');d.append(s,a);out.append(d);}
}

function computeSingle(){return singleHead({focus:state.focus??0,key:state.keyStrength??1,value:state.value,mask:state.mask,query:state.token})}
const fmt=n=>Number.isFinite(n)?n.toFixed(3):'−∞';const vec=v=>'['+v.map(fmt).join(', ')+']';
function texturedTable(rows,position,width,height,{highlight=-1}={}){
 const canvas=document.createElement('canvas');canvas.width=1440;canvas.height=960;const ctx=canvas.getContext('2d');ctx.fillStyle='#070b0d';ctx.fillRect(0,0,1440,960);const rh=960/rows.length;
 rows.forEach((cells,r)=>{if(r===highlight){ctx.fillStyle='#343318';ctx.fillRect(0,r*rh,1440,rh)}ctx.fillStyle=r===0?'#58c4dd':r===highlight?'#ffff62':'#eeeeee';ctx.font=(r===0?'bold ':'')+(cells.length===4?'36':'44')+'px monospace';cells.forEach((c,j)=>ctx.fillText(String(c),(cells.length===4?[20,220,620,1020][j]:22+j*(1400/cells.length)),r*rh+rh*.61));ctx.strokeStyle='#35434b';ctx.beginPath();ctx.moveTo(0,(r+1)*rh);ctx.lineTo(1440,(r+1)*rh);ctx.stroke();});
 const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=renderer.capabilities.getMaxAnisotropy();const p=new THREE.Mesh(new THREE.PlaneGeometry(width,height),new THREE.MeshBasicMaterial({map:texture,side:THREE.DoubleSide}));p.position.copy(V(position));root.add(p);return p;
}
function buildQueries(){
 const t=computeSingle();label('ONE HEAD · 8 tokens → 8 queries, 8 keys, 8 values',[0,4.8,0],colors.white,root,{size:20});
 for(let i=0;i<8;i++){const x=(i-3.5)*1.9;tokenLabel(words[i],[x,3.6,0],()=>{state.token=i;dirty=true;controls()},i===state.token?colors.yellow:colors.gray,root,1.7);}
 const compact=v=>'['+v.map(x=>x.toFixed(2)).join(',')+']';const rows=[['token','q = W_Q x','k = W_K x','v = W_V x'],...words.map((w,i)=>[w,compact(t.Q[i]),compact(t.K[i]),compact(t.V[i])])];texturedTable(rows,[0,-.1,0],16,6,{highlight:state.token+1});
 label('Shared matrices; different token inputs → different queries (table rounded to 2 decimals).',[0,-3.9,0],colors.teal,root,{size:16});
 const marker=new THREE.Mesh(new THREE.SphereGeometry(.08,12,12),new THREE.MeshBasicMaterial({color:colors.yellow}));root.add(marker);animators.push(p=>marker.position.set((state.token-3.5)*1.9,3.4-p*1.3,.15));
}
function buildSingle(){
 const t=computeSingle(),j=state.token,i=state.source;
 label('ONE HEAD · Q/K choose weights → V supplies content',[0,5.1,0],colors.white,root,{size:20});
 label('Receiver: '+words[j]+' · q = '+vec(t.Q[j]),[-3.7,4.2,0],colors.yellow,root,{size:16});
 const rows=[['source','q · k','÷ √3','masked','weight'],...words.map((w,k)=>[w,fmt(t.raw[k]),fmt(t.scaled[k]),fmt(t.logits[k]),t.weights[k].toFixed(3)])];texturedTable(rows,[-4,.2,0],9.4,6.7,{highlight:i+1});
 for(let k=0;k<8;k++){const hit=new THREE.Mesh(new THREE.PlaneGeometry(9.4,.72),new THREE.MeshBasicMaterial({visible:false,side:THREE.DoubleSide}));hit.position.set(-4,2.43-k*.744,.05);root.add(hit);hit.userData.action=()=>{state.source=k;dirty=true;controls()};targets.push(hit);}
 label('Scale → mask → softmax (weights sum to 1)',[-4,-3.65,0],colors.teal,root,{size:14});
 label(words[i]+': '+fmt(t.exp[i])+' / '+fmt(t.Z)+' = '+t.weights[i].toFixed(3),[4,3.35,0],colors.teal,root,{size:14});label(t.weights[i].toFixed(3)+' × v_'+words[i]+' = '+vec(t.contributions[i]),[4,2.65,0],colors.red,root,{size:13});
 const origin=[3.5,-1.5,0],magnify=1.65;let tip=t.input.map((x,d)=>origin[d]+x*magnify);
 const vectorStart=root.children.length;arrow(origin,tip,colors.yellow);label('x('+words[j]+')',tip,colors.yellow,root,{size:15});
 for(let k=0;k<8;k++){
  const amount=t.contributions[k];if(Math.hypot(...amount)<.002)continue;
  const next=tip.map((x,d)=>x+amount[d]*magnify),c=k===2?colors.blue:k===1?colors.teal:colors.red;const g=new THREE.Group();root.add(g);arrow([0,0,0],amount.map(x=>x*magnify),c,g,.035);const start=[...tip];animators.push(p=>g.position.copy(V(lerp([2.3+(k%3)*1.5,2.5,-.6],start,p)).sub(V(origin))));label(`${t.weights[k].toFixed(2)} v_${words[k]}`,amount.map(x=>x*magnify),c,g,{size:14});tip=next;
 }
 const out=arrow(origin,tip,colors.white,root,.035);animators.push(p=>out.visible=p>.75);label('x′ = x + W_O z',tip,colors.white,root,{size:17});const vectorObjects=root.children.slice(vectorStart),vectorGroup=new THREE.Group();vectorGroup.position.copy(V(origin));root.add(vectorGroup);for(const o of vectorObjects)vectorGroup.attach(o);vectorGroup.rotation.set(-.4,-.65,0);
 label('z = Σ weight × value',[4,4.2,0],colors.red,root,{size:17});label('W_O = I here (identity output projection)',[4,-3.7,0],colors.gray,root,{size:13});label('Result: '+vec(t.output),[3.7,-4.65,0],colors.white,root,{size:17});
}
function singleControls(){
 const host=$('#controls');host.innerHTML='<label>Receiving token / query</label><select id="single-query" aria-label="Receiving token"></select>';
 const query=$('#single-query');query.style.width='100%';words.forEach((w,i)=>query.add(new Option(`${i+1}: ${w}`,i)));query.value=state.token;query.onchange=()=>{state.token=+query.value;dirty=true;controls()};
 if(state.view==='single'){
  const l=document.createElement('label');l.textContent='Source token / key and value';host.append(l);const source=document.createElement('select');source.id='single-source';source.style.width='100%';words.forEach((w,i)=>source.add(new Option(`${i+1}: ${w}`,i)));source.value=state.source;source.onchange=()=>{state.source=+source.value;dirty=true;controls()};host.append(source);
 }
 const sl=document.createElement('div');sl.innerHTML=slider('focus','Q projection: fluffy ↔ blue',-2,2,.05)+slider('keyStrength','K projection: blue component',0,2,.05)+slider('value','Blue value component strength',-2,3,.05);host.append(sl);sl.querySelectorAll('input').forEach(el=>el.oninput=()=>{state[el.dataset.control]=+el.value;dirty=true;syncControls()});
 if(state.view==='single'){const btn=document.createElement('button');btn.id='single-mask';btn.textContent=state.mask?'Causal mask: ON':'Causal mask: OFF';btn.onclick=()=>{state.mask=!state.mask;dirty=true;controls()};host.append(btn);}
 if(state.view==='queries'){
  const label=document.createElement('label');label.textContent='How many query vectors per layer?';host.append(label);const sel=document.createElement('select');sel.id='query-count';sel.style.width='100%';[[1,'One head'],[12,'GPT-2-small: 12 heads'],[96,'GPT-3 175B: 96 heads']].forEach(([v,s])=>sel.add(new Option(s,v)));sel.value=state.countHeads??1;sel.onchange=()=>{state.countHeads=+sel.value;singleReadout()};host.append(sel);const total=document.createElement('p');total.id='query-count-summary';total.style.color='#ffff62';total.style.fontSize='15px';host.append(total);
  const note=document.createElement('p');note.textContent='Count reference only: the displayed calculations still use ONE 3D teaching head. Heads may learn previous-token, modifier, or entity-reference patterns; they are not assigned a fixed list of English questions.';host.append(note);
 }
 const details=document.createElement('details');details.innerHTML='<summary>Inspect the shared Q/K/V matrices</summary><pre id="single-matrices"></pre>';host.append(details);
 const next=document.createElement('a');next.className='input-next';next.href=state.view==='queries'?'#single':'#heads';next.textContent=state.view==='queries'?'Next: calculate the whole head →':'Next: multiple heads →';host.append(next);
}
function singleReadout(){
 const t=computeSingle(),j=state.token,i=state.source;$('#selected').textContent=words[j]+' ← '+words[i];const m=$('#single-matrices');if(m)m.textContent=['W_Q',...t.WQ.map(vec),'W_K',...t.WK.map(vec),'W_V',...t.WV.map(vec)].join('\n');
 if(state.view==='queries'){
  $('#selected').textContent=words[j]+' · its own query';const h=state.countHeads??1;if($('#query-count-summary'))$('#query-count-summary').textContent=`8 tokens × ${h} heads = ${8*h} queries per layer`;$('#numbers').textContent=`8 tokens × ${h} head${h===1?'':'s'} = ${8*h} query vectors per layer.\n\nFor each head: 8 queries, 8 keys, 8 values.\n\nHere: x = ${vec(t.input)}\nq = W_Q x = ${vec(t.Q[j])}\nk = ${vec(t.K[j])}\nv = ${vec(t.V[j])}\n\n3D toy: d_k = 3\nGPT-2-small: d_k = 64\nGPT-3 175B: d_k = 128`;return;
 }
 const product=t.Q[j].map((x,d)=>`${fmt(x)} × ${fmt(t.K[i][d])}`).join(' + ');
 $('#numbers').textContent=`q · k = ${product}\n= ${fmt(t.raw[i])}\n\nScale: ${fmt(t.raw[i])} / √3 = ${fmt(t.scaled[i])}\nMask: ${fmt(t.logits[i])}\n\nStable softmax:\nexp(score − max) / Σ exp\n= ${fmt(t.exp[i])} / ${fmt(t.Z)}\n= ${t.weights[i].toFixed(6)}\n\nweight × v_${words[i]}\n= ${t.weights[i].toFixed(3)} × ${vec(t.V[i])}\n= ${vec(t.contributions[i])}\n\nz = ${vec(t.z)}\nx′ = x + W_O z\n= ${vec(t.output)}`;
}

const builders={queries:buildQueries,single:buildSingle,tokens:buildInput,pipeline:buildPipeline,qk:buildQK,values:buildValues,heads:buildHeads,meaning:buildMeaning};
function rebuild(){dirty=false;clear();modelTrace=trace({mask:state.mask,bias:state.bias,value:state.value});builders[state.view]();applyProgress();renderedView=state.view;updateReadout();}
function applyProgress(){for(const f of animators)f(state.progress);$('#progress').value=state.progress;$('#progress-value').value=Math.round(state.progress*100)+'%';}
function fitCamera(kind='angle'){let pos,target;if(['queries','single'].includes(state.view)){target=[0,0,0];pos=kind==='front'?[0,0,19]:[1,2,19]}else if(['tokens','embedding'].includes(state.view)){target=[0,0,0];pos=kind==='front'?[0,0,21]:[1,2,21]}else if(state.view==='pipeline'){target=[0,0,-5.7];pos=kind==='front'?[0,1,24]:[16,10,20]}else if(state.view==='qk'){target=[-.8,0,0];pos=kind==='front'?[0,20,.01]:[12,13,16]}else if(state.view==='values'){target=[.3,.8,0];pos=kind==='front'?[0,3,12]:[7,6,-10]}else if(state.view==='heads'){target=[0,0,state.heads===96?-2:0];pos=kind==='front'?[0,0,state.heads===4?22:34]:[state.heads===96?16:state.heads===12?12:9,state.heads===12?9:7,state.heads===96?27:state.heads===12?31:20]}else {target=[0,2.1,0];pos=kind==='front'?[0,2,21]:[10,7,16]};camera.position.copy(V(pos));orbit.target.copy(V(target));orbit.update();}
function updateLabels(){const rect=host.getBoundingClientRect(),used=[];root.updateMatrixWorld(true);for(const l of [...labels].sort((a,b)=>b.priority-a.priority)){const v=new THREE.Vector3();l.anchor.getWorldPosition(v);v.project(camera);const px=(v.x+1)/2*rect.width,py=(1-v.y)/2*rect.height;const hide=!l.anchor.visible||v.z>1||px<0||px>rect.width||py<35||py>rect.height-45;l.el.style.display=l.leader.style.display=hide?'none':'';if(hide)continue;const w=l.el.offsetWidth,h=l.el.offsetHeight;let x=Math.max(5,Math.min(rect.width-w-5,px+(['tokens','embedding','queries','single'].includes(state.view)?-w/2:5))),y=Math.max(36,Math.min(rect.height-h-47,py));for(let i=0;i<(state.view==='tokens'?0:20);i++){if(!used.some(r=>x<r.x+r.w+4&&x+w+4>r.x&&y<r.y+r.h+3&&y+h+3>r.y))break;y=Math.max(36,Math.min(rect.height-h-47,py+(i%2?1:-1)*Math.ceil((i+1)/2)*(h+4)));}used.push({x,y,w,h});l.el.style.left=x+'px';l.el.style.top=y+'px';const dx=x-px,dy=y+h/2-py;l.leader.style.left=px+'px';l.leader.style.top=py+'px';l.leader.style.width=Math.hypot(dx,dy)+'px';l.leader.style.transform='rotate('+Math.atan2(dy,dx)+'rad)';}}
function slider(key,label,min,max,step){return `<label>${label}<output data-out="${key}">${state[key]}</output></label><input data-control="${key}" aria-label="${label}" type="range" min="${min}" max="${max}" step="${step}" value="${state[key]}">`}
function buttons(key,items){return `<div class="buttons">${items.map(([value,name])=>`<button data-set="${key}" data-value="${value}" class="${state[key]===value?'active':''}">${name}</button>`).join('')}</div>`}
function controls(){if(['queries','single'].includes(state.view)){singleControls();return}if(['tokens','embedding'].includes(state.view)){inputControls();return}let h='<label>Updated token / query</label>'+buttons('token',words.map((w,i)=>[i,w]));if(state.view==='qk'){h+=buttons('phase',[['scores','Dot-product scores'],['weights','Softmax weights']])+slider('bias','blue → creature score change',-6,6,.05)+buttons('mask',[[true,'Mask future'],[false,'No mask']]);}if(state.view==='values'){h+=slider('value','blue Value strength',-2,3,.05)+slider('bias','blue → creature score change',-6,6,.05)}if(state.view==='heads'){h+=buttons('heads',[[4,'4 heads'],[12,'12 heads'],[96,'96 heads']])+slider('head','Selected head',0,state.heads-1,1)}if(state.view==='meaning'){h=buttons('family',[[false,'king / queen'],[true,'uncle / aunt']])+'<p>Real GloVe 50D data, matching the source, projected into 3D.</p>';}if(state.view==='pipeline')h+='<p>Use Expand to separate blocks. Select a token to highlight its column and attention information flow.</p>';
$('#controls').innerHTML=h;$('#controls').querySelectorAll('[data-control]').forEach(el=>el.oninput=()=>{state[el.dataset.control]=+el.value;dirty=true;syncControls()});$('#controls').querySelectorAll('[data-set]').forEach(el=>el.onclick=()=>{const key=el.dataset.set;let v=el.dataset.value;v=v==='true'?true:v==='false'?false:Number.isNaN(+v)?v:+v;state[key]=v;if(key==='heads'){state.head=Math.min(state.head,v-1);fitCamera()}if(key==='family')fitCamera();dirty=true;controls()});}
function syncControls(){for(const el of $('#controls').querySelectorAll('[data-out]'))el.textContent=Number(state[el.dataset.out]).toFixed(el.dataset.out==='head'?0:2);for(const el of $('#controls').querySelectorAll('[data-control]'))el.value=state[el.dataset.control];for(const el of $('#controls').querySelectorAll('[data-set]'))el.classList.toggle('active',String(state[el.dataset.set])===el.dataset.value);}
function updateReadout(){if(['queries','single'].includes(state.view)){singleReadout();return}if(['tokens','embedding'].includes(state.view)){inputReadout();return}const j=state.token;$('#selected').textContent=state.view==='meaning'?(state.family?'uncle → aunt':'king → queen'):state.view==='heads'?'Head '+(state.head+1)+' / '+words[j]:words[j];let a=state.view==='heads'?pattern(state.head):modelTrace.attention;const ranked=words.map((w,i)=>[w,a[i][j]]).sort((a,b)=>b[1]-a[1]);let h=ranked.slice(0,4).map(([w,p])=>`${w.padEnd(9,' ')} ${(p*100).toFixed(2)}%`).join('<br>')+`<br>Σ = ${a.reduce((s,r)=>s+r[j],0).toFixed(6)}`;if(state.view==='values')h+=`<br>ΔE = [${modelTrace.delta[j].map(v=>v.toFixed(3)).join(', ')}]<br>E′ = [${modelTrace.output[j].map(v=>v.toFixed(3)).join(', ')}]`;if(state.view==='pipeline')h='<span>Illustrative activations (not GPT weights)<br>8 token columns<br>Attention mixes positions<br>MLP works per position<br>Final vector → next token</span>';if(state.view==='heads')h+=`<br><br>GPT-3: 96 heads/block<br>${parameterCounts.block.toLocaleString()} weights/block`;if(state.view==='meaning'){const key=state.family?'family':'analogy';h=`50 dimensions used<br>Residual norm: ${data.analogies[key].errorNorm.toFixed(3)}<br>Not an exact equality`}$('#numbers').innerHTML=h;}
function setView(id){if(id==='embedding')id='tokens';if(['qk','values'].includes(id))id='single';state.view=id;state.progress=1;state.playing=false;state.head=0;state.heads=4;state.token=3;state.bias=0;state.focus=0;state.keyStrength=1;state.value=1;state.countHeads=1;state.phase='weights';state.mask=true;state.family=false;$('#play').textContent='▶ Animate';const d=definitions.find(d=>d.id===id);$('#title').textContent=d.title;$('#eyebrow').textContent='THREE.JS · INTERACTIVE 3D · '+d.name;$('#cue').textContent=d.cue;$('#context').textContent=d.context;$('#source').href=`https://www.youtube.com/watch?v=${d.chapter===5?'wjZofJX0v4M':'eMlx5fFNoYc'}&t=${d.source}s`;$('#views').querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));document.querySelector('.legend').style.display=['tokens','embedding','queries','single'].includes(id)?'none':'';history.replaceState(null,'','#'+id);controls();dirty=true;fitCamera();}
$('#views').innerHTML=definitions.map(d=>`<button data-view="${d.id}">${d.name}</button>`).join('');$('#views').querySelectorAll('button').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#front').onclick=()=>fitCamera('front');$('#angle').onclick=()=>fitCamera('angle');$('#home').onclick=()=>fitCamera();$('#reset').onclick=()=>setView(state.view);$('#project').onclick=()=>document.body.classList.toggle('project');$('#progress').oninput=e=>{state.progress=+e.target.value;state.playing=false;$('#play').textContent='▶ Animate';applyProgress()};$('#play').onclick=()=>{if(state.progress>=1)state.progress=0;state.playing=!state.playing;$('#play').textContent=state.playing?'Ⅱ Pause':'▶ Animate'};
let down=null;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const r=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=raycaster.intersectObjects(targets,false)[0];hit?.object.userData.action?.();});
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if((['embedding','qk','values'].includes(id)||definitions.some(d=>d.id===id))&&id!==state.view)setView(id)});window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','BUTTON','SELECT'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();$('#play').click()}});
function tick(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;const r=host.getBoundingClientRect(),sz=new THREE.Vector2();renderer.getSize(sz);if(sz.x!==r.width||sz.y!==r.height){renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}if(dirty)rebuild();if(state.playing){state.progress=Math.min(1,state.progress+dt/9);applyProgress();if(state.progress>=1){state.playing=false;$('#play').textContent='▶ Animate'}}orbit.update();renderer.render(scene,camera);updateLabels();frames++;requestAnimationFrame(tick)}
window.attention3d={single:()=>computeSingle(),input:()=>({text:inputText,ids:inputIds,pieces:inputIds.map(i=>decode([i])),index:inputIndex,positionOn,embedding:inputData.wte[inputIds[inputIndex]],position:inputData.wpe[inputIndex]}),get state(){return {...state,renderedView,frames,camera:camera.position.toArray(),target:orbit.target.toArray(),objects:renderer.info.render.calls,triangles:renderer.info.render.triangles,geometries:renderer.info.memory.geometries,textures:renderer.info.memory.textures,webgl:renderer.getContext().isContextLost()?'lost':'ok',labels:labels.length,targets:targets.length}},trace:()=>trace({mask:state.mask,bias:state.bias,value:state.value}),pattern,layout:()=>root.children.filter(o=>o.isGroup).map(o=>({position:o.position.toArray(),scale:o.scale.toArray(),visible:o.visible})),views:definitions,setView,set:values=>{Object.assign(state,values);dirty=true;syncControls()},projectTarget:(i)=>{const p=new THREE.Vector3();targets[i].getWorldPosition(p);p.project(camera);const r=host.getBoundingClientRect();return {x:r.x+(p.x+1)/2*r.width,y:r.y+(1-p.y)/2*r.height}},numeric:{softmax}};
setView(['#qk','#values'].includes(location.hash)?'single':location.hash==='#embedding'?'tokens':definitions.some(d=>d.id===location.hash.slice(1))?location.hash.slice(1):'tokens');requestAnimationFrame(tick);
